package com.rfm.edubot.mobile.core.localization

/** Spanish. Tested to carry exactly the keys [englishCatalog] has. */
internal val spanishCatalog: Map<String, String> = mapOf(
    Txt.ACTION_SAVE to "Guardar",
    Txt.ACTION_CANCEL to "Cancelar",
    Txt.ACTION_CONFIRM to "Confirmar",
    Txt.ACTION_RETRY to "Reintentar",
    Txt.ACTION_REFRESH to "Actualizar",
    Txt.ACTION_BACK to "Volver",
    Txt.ACTION_CLOSE to "Cerrar",
    Txt.ACTION_NEW to "Nuevo",
    Txt.ACTION_SEND to "Enviar",
    Txt.ACTION_SEARCH to "Buscar",
    Txt.ACTION_SIGN_IN to "Iniciar sesión",
    Txt.ACTION_SIGN_OUT to "Cerrar sesión",
    Txt.ACTION_APPROVE to "Aprobar",
    Txt.ACTION_REJECT to "Rechazar",
    Txt.ACTION_DONE to "Completar",
    Txt.ACTION_REOPEN to "Reabrir",
    Txt.ACTION_PAUSE to "Pausar",
    Txt.ACTION_RESUME to "Reanudar",
    Txt.ACTION_MARK_PAID to "Marcar como pagada",
    Txt.ACTION_MARK_ALL_READ to "Marcar todas como leídas",
    Txt.ACTION_LOAD_MORE to "Ver más",
    Txt.ACTION_SHOW to "Mostrar",
    Txt.ACTION_HIDE to "Ocultar",

    Txt.LABEL_ALL to "Todas",
    Txt.LABEL_OPEN to "Abiertas",
    Txt.LABEL_TODAY to "Hoy",
    Txt.LABEL_OPTIONAL to "opcional",
    Txt.LABEL_REQUIRED to "obligatorio",
    Txt.LABEL_NONE to "Ninguno",
    Txt.LABEL_TOTAL to "Total",
    Txt.LABEL_UNTITLED to "Sin título",

    Txt.LOGIN_TITLE to "Iniciar sesión",
    Txt.LOGIN_DESCRIPTION to "Gestiona tu asistente desde cualquier lugar.",
    Txt.LOGIN_EMAIL to "Email",
    Txt.LOGIN_PASSWORD to "Contraseña",
    Txt.LOGIN_ERROR_MISSING to "Introduce tu email y tu contraseña.",
    Txt.LOGIN_ERROR_INVALID to "No se aceptaron esos datos. Compruébalos e inténtalo otra vez.",
    Txt.LOGIN_ERROR_EXPIRED to "Tu sesión ha caducado. Vuelve a iniciar sesión.",
    Txt.LOGIN_ERROR_INACTIVE to "Esta cuenta no está activa. Pide a un administrador que la active.",
    Txt.LOGIN_ERROR_CONNECTION to "No se pudo conectar con el panel. Comprueba tu conexión.",
    Txt.LOGIN_SECURITY_NOTE to "Tus datos quedan limitados a la empresa de esta cuenta.",

    Txt.ERROR_UNAUTHORIZED to "Tu sesión ha terminado.",
    Txt.ERROR_FORBIDDEN to "Tu plan o tu perfil no incluye esto.",
    Txt.ERROR_NOT_FOUND to "Esto ya no existe.",
    Txt.ERROR_OFFLINE to "Sin conexión con el panel.",
    Txt.ERROR_SERVER to "El panel tuvo un problema. Inténtalo en un momento.",
    Txt.ERROR_REJECTED to "No se pudo guardar.",
    "error.code.tax_id_required" to "El NIF es obligatorio.",
    "error.code.address_required" to "La dirección es obligatoria.",
    "error.code.invalid_email" to "Ese email no es válido.",
    "error.code.address_too_long" to "Esa dirección es demasiado larga.",
    "error.code.tax_id_too_long" to "Ese NIF es demasiado largo.",
    "error.code.id_taken" to "Otro artículo ya usa ese código.",
    "error.code.phone_taken" to "Otro registro ya usa ese número.",
    "error.code.in_use" to "Esto se usa en otro sitio y no se puede eliminar.",
    "error.code.name_required" to "El nombre es obligatorio.",
    "error.code.invalid_time" to "Esa hora no es válida.",
    "error.code.slot_taken" to "Esa hora ya está ocupada.",
    "error.code.outside_hours" to "Esa hora está fuera de tu horario.",
    "error.code.client_not_found" to "Ningún cliente coincide.",
    "error.code.no_user_account" to "Una sesión de soporte no puede cambiar la cuenta.",

    Txt.OFFLINE_SNAPSHOT to "Mostrando los últimos datos guardados",
    Txt.OFFLINE_SNAPSHOT_DETAIL to "Guardados en este dispositivo. Se actualizan en cuanto haya conexión.",
    Txt.EMPTY_TITLE to "Aquí no hay nada todavía",

    Txt.NAV_MORE to "Más",
    Txt.NAV_GROUP_HOME to "Inicio",
    Txt.NAV_GROUP_INBOX to "Bandeja de entrada",
    Txt.NAV_GROUP_BUSINESS to "Negocio",
    Txt.NAV_GROUP_AUTOMATION to "Automatización",
    Txt.NAV_GROUP_SETUP to "Configuración",
    Txt.NAV_WEB_ONLY to "En el panel web",
    Txt.NAV_WEB_ONLY_DETAIL to "Tu plan los incluye y la aplicación todavía no los muestra.",

    Txt.OVERVIEW_SNAPSHOT to "Resumen operativo",
    Txt.OVERVIEW_NEEDS_YOU to "Te necesita",
    Txt.OVERVIEW_NEEDS_YOU_EMPTY to "Nada está esperándote.",
    Txt.OVERVIEW_AGENDA to "Agenda",
    Txt.OVERVIEW_MESSAGES_TODAY to "Mensajes de hoy",
    Txt.OVERVIEW_WAITING to "En espera",
    Txt.OVERVIEW_CONTACTS to "Contactos",
    Txt.OVERVIEW_CONVERSATIONS to "Conversaciones",
    Txt.OVERVIEW_COLLECTED_MONTH to "Recibido este mes",
    Txt.OVERVIEW_OUTSTANDING to "Por cobrar",
    Txt.OVERVIEW_OVERDUE to "Vencido",
    Txt.OVERVIEW_PIPELINE_OPEN to "Presupuestos abiertos",
    Txt.OVERVIEW_BOOKINGS_TODAY to "Reservas hoy",
    Txt.OVERVIEW_BOOKINGS_PENDING to "Por confirmar",
    Txt.OVERVIEW_APPROVALS to "Aprobaciones",
    Txt.OVERVIEW_TASKS to "Tareas abiertas",
    Txt.OVERVIEW_GENERATED_AT to "Actualizado a las {time}",

    Txt.INBOX_TITLE to "Bandeja de entrada",
    Txt.INBOX_FILTER_NEEDS_REPLY to "Sin responder",
    Txt.INBOX_FILTER_UNREAD to "No leídas",
    Txt.INBOX_FILTER_PAUSED to "IA en pausa",
    Txt.INBOX_EMPTY to "Todavía no hay conversaciones.",
    Txt.INBOX_MESSAGE_PLACEHOLDER to "Escribe un mensaje",
    Txt.INBOX_AUTO_REPLY_ON to "El asistente está respondiendo",
    Txt.INBOX_AUTO_REPLY_OFF to "El asistente está en pausa aquí",
    Txt.INBOX_WINDOW_CLOSED to "La ventana de 24 horas se cerró. Solo se puede enviar una plantilla aprobada.",
    Txt.INBOX_SEND_FAILED to "No entregado",
    Txt.INBOX_ATTACHMENT to "Adjunto",
    Txt.INBOX_WRITTEN_BY_AGENT to "Enviado por {name}",
    Txt.INBOX_WEB_REPLY_UNAVAILABLE to "Responder a los chats del sitio todavía no está disponible en la aplicación.",
    "inbox.messagesCount.one" to "{count} mensaje",
    "inbox.messagesCount.other" to "{count} mensajes",

    Txt.CONTACTS_TITLE to "Contactos",
    Txt.CONTACTS_EMPTY to "Todavía no hay contactos.",
    Txt.CONTACTS_BLOCK to "Bloquear",
    Txt.CONTACTS_UNBLOCK to "Desbloquear",
    Txt.CONTACTS_LAST_SEEN to "Visto {time}",

    Txt.CRM_CLIENTS_TITLE to "Clientes",
    Txt.CRM_CLIENTS_EMPTY to "Todavía no hay clientes.",
    Txt.CRM_CLIENT_NAME to "Nombre",
    Txt.CRM_CLIENT_PHONE to "Teléfono",
    Txt.CRM_CLIENT_TAX_ID to "NIF",
    Txt.CRM_CLIENT_TAX_ID_HINT to "Sin él no se pueden emitir presupuestos ni facturas.",
    Txt.CRM_CLIENT_ADDRESS to "Dirección",
    Txt.CRM_CLIENT_EMAIL to "Email",
    Txt.CRM_CLIENT_CITY to "Localidad",
    Txt.CRM_CLIENT_POSTAL_CODE to "Código postal",
    Txt.CRM_CLIENT_CREATE to "Añadir cliente",
    Txt.CRM_QUOTES_TITLE to "Presupuestos",
    Txt.CRM_QUOTES_EMPTY to "Todavía no hay presupuestos.",
    Txt.CRM_QUOTE_CONVERT to "Convertir en factura",
    Txt.CRM_QUOTE_VALID_UNTIL to "Válido hasta",
    Txt.CRM_INVOICES_TITLE to "Facturas",
    Txt.CRM_INVOICES_EMPTY to "Todavía no hay facturas.",
    Txt.CRM_INVOICE_DUE_DATE to "Fecha de vencimiento",
    Txt.CRM_INVOICE_OVERDUE to "Vencida",
    Txt.CRM_CATALOG_TITLE to "Catálogo",
    Txt.CRM_CATALOG_EMPTY to "Todavía no hay artículos.",
    Txt.CRM_CATALOG_ITEM_TITLE to "Título",
    Txt.CRM_CATALOG_ITEM_CODE to "Código",
    Txt.CRM_CATALOG_CATEGORY to "Categoría",
    Txt.CRM_CATALOG_UNIT to "Unidad",
    Txt.CRM_CATALOG_PRICE to "Precio unitario",
    Txt.CRM_CATALOG_TYPE_SERVICE to "Servicio",
    Txt.CRM_CATALOG_TYPE_PRODUCT to "Producto",
    Txt.CRM_SERVICES_TITLE to "Trabajos",
    Txt.CRM_SERVICES_EMPTY to "Todavía no hay trabajos.",
    Txt.CRM_SERVICES_INVOICE_SELECTED to "Facturar {count} seleccionados",
    Txt.CRM_PAYMENTS_TITLE to "Pagos",
    Txt.CRM_PAYMENTS_EMPTY to "Todavía no hay pagos.",
    Txt.CRM_SUPPLIERS_TITLE to "Proveedores",
    Txt.CRM_SUPPLIERS_EMPTY to "Todavía no hay proveedores.",
    Txt.CRM_EMPLOYEES_TITLE to "Empleados",
    Txt.CRM_EMPLOYEES_EMPTY to "Todavía no hay empleados.",
    Txt.CRM_LINE_DESCRIPTION to "Descripción",
    Txt.CRM_LINE_QUANTITY to "Cantidad",
    Txt.CRM_LINE_UNIT_PRICE to "Precio unitario",
    Txt.CRM_LINE_ADD to "Añadir línea",
    Txt.CRM_NOTES to "Notas",
    Txt.CRM_LINES to "Líneas",
    Txt.CRM_PICK_CLIENT to "Elegir cliente",
    Txt.CRM_DATE_FORMAT_HINT to "AAAA-MM-DD",

    Txt.BOOKINGS_TITLE to "Reservas",
    Txt.BOOKINGS_EMPTY to "Nada reservado.",
    Txt.BOOKINGS_UPCOMING to "Próximas",
    Txt.BOOKINGS_NEEDS_CONFIRM to "Por confirmar",
    Txt.BOOKINGS_BILLABLE to "Terminadas, sin facturar",
    Txt.BOOKINGS_OPENING_HOURS to "Horario",
    Txt.BOOKINGS_CLOSED to "Cerrado",
    Txt.BOOKINGS_SERVICE to "Servicio",

    Txt.AGENTS_TITLE to "Agentes",
    Txt.AGENTS_TAB_INBOX to "Por decidir",
    Txt.AGENTS_TAB_AGENTS to "Agentes",
    Txt.AGENTS_TAB_ACTIVITY to "Actividad",
    Txt.AGENTS_APPROVALS to "Esperando aprobación",
    Txt.AGENTS_APPROVALS_EMPTY to "Ningún agente te está esperando.",
    Txt.AGENTS_TASKS to "Tareas",
    Txt.AGENTS_TASKS_EMPTY to "No hay tareas abiertas.",
    Txt.AGENTS_EMPTY to "Todavía no hay agentes.",
    Txt.AGENTS_PAUSED_BY_PLATFORM to "El soporte pausó todos los agentes. Solo el soporte puede reanudarlos.",
    Txt.AGENTS_PAUSED_COMPANY to "Todos los agentes de esta empresa están en pausa.",
    Txt.AGENTS_CANNOT_DECIDE to "Tu perfil no puede decidir esta.",
    Txt.AGENTS_EXPIRES to "Caduca en {days} días",
    Txt.AGENTS_EXPIRES_TODAY to "Caduca hoy",
    Txt.AGENTS_REJECT_REASON to "¿Por qué la rechazas?",
    Txt.AGENTS_RUNS_TODAY to "Ejecuciones hoy",
    Txt.AGENTS_ACTIVE to "Activos",
    Txt.AGENTS_FAILED_WEEK to "Fallos esta semana",
    Txt.AGENTS_ACTIVITY_EMPTY to "Todavía no hubo ejecuciones.",
    Txt.AGENTS_DUE to "Para {date}",
    Txt.AGENTS_BUILDER_WEB_ONLY to "Crea y edita agentes en el panel web.",

    Txt.NOTIFICATIONS_TITLE to "Notificaciones",
    Txt.NOTIFICATIONS_EMPTY to "Nada que informar.",
    Txt.NOTIFICATIONS_GENERIC to "Algo necesita tu atención.",
    Txt.NOTIFICATIONS_UNREAD to "{count} sin leer",
    "notification.agent_approval_pending" to "{agentName} espera tu aprobación.",
    "notification.agent_task_assigned" to "{agentName} te dejó una tarea: {title}",
    "notification.agent_run_failed" to "{agentName} no pudo terminar una ejecución.",
    "notification.agent_paused" to "{agentName} fue pausado.",
    "notification.invoice_overdue" to "La factura {number} está vencida.",
    "notification.quote_accepted" to "El presupuesto {number} fue aceptado.",
    "notification.booking_pending" to "{contactName} pidió una reserva.",
    "notification.integration_disconnected" to "Hay que volver a conectar {provider}.",
    "notification.conversation_waiting" to "{contactName} espera una respuesta.",

    Txt.ASSISTANT_TITLE to "Asistente",
    Txt.ASSISTANT_EMPTY to "Todavía no hay conversaciones con tu asistente.",
    Txt.ASSISTANT_START_THREAD to "Empieza una conversación para trabajar con tu asistente.",
    Txt.ASSISTANT_NEW_THREAD to "Nueva conversación",
    Txt.ASSISTANT_PROMPT_PLACEHOLDER to "Pide algo",
    Txt.ASSISTANT_ACTION_PENDING to "Esperando tu confirmación",
    Txt.ASSISTANT_THREADS to "Conversaciones",

    Txt.PERSONA_TITLE to "Personalidad",
    Txt.PERSONA_INSTRUCTIONS to "Instrucciones",
    Txt.PERSONA_VERSION to "Versión {version}",
    Txt.PERSONA_TOKENS to "{count} tokens",
    Txt.PERSONA_COMPILING to "Reconstruyendo el prompt",
    Txt.PERSONA_REBUILD to "Reconstruir",
    Txt.PERSONA_SOURCES to "Fuentes",
    Txt.PERSONA_SOURCES_EMPTY to "Todavía no hay fuentes.",
    Txt.PERSONA_ADD_NOTE to "Añadir nota",
    Txt.PERSONA_NOTE_PLACEHOLDER to "Algo que el asistente deba saber",
    Txt.PERSONA_TEST to "Probar",
    Txt.PERSONA_TEST_PLACEHOLDER to "Escribe lo que diría un cliente",
    Txt.PERSONA_SOURCE_PENDING to "Todavía fuera del prompt",
    Txt.PERSONA_FILE_WEB_ONLY to "Sube documentos en el panel web.",

    Txt.SETTINGS_TITLE to "Configuración",
    Txt.SETTINGS_CHANNELS to "Canales",
    Txt.SETTINGS_CHANNELS_EMPTY to "Ningún canal conectado.",
    Txt.SETTINGS_LANGUAGE to "Idioma",
    Txt.SETTINGS_APPEARANCE to "Apariencia",
    Txt.SETTINGS_THEME_LIGHT to "Claro",
    Txt.SETTINGS_THEME_DARK to "Oscuro",
    Txt.SETTINGS_THEME_SYSTEM to "Del sistema",
    Txt.SETTINGS_ACCOUNT to "Cuenta",
    Txt.SETTINGS_COMPANIES to "Empresas",
    Txt.SETTINGS_COMPANY_SWITCH to "Cambiar",
    Txt.SETTINGS_WIDGET to "Widget del sitio",
    Txt.SETTINGS_WIDGET_KEY to "Clave pública",
    Txt.SETTINGS_OPERATOR_SESSION to "Has entrado como soporte, solo para esta empresa.",
    Txt.SETTINGS_WEB_FOR_MORE to "Los canales, las plantillas y el diseño de documentos se configuran en el panel web.",

    Txt.VOICE_START to "Voz",
    Txt.VOICE_STOP to "Parar",
    Txt.VOICE_LISTENING to "Escuchando",
    Txt.VOICE_PERMISSION_DENIED to "Se requiere permiso para el micrófono y el reconocimiento de voz.",
    Txt.VOICE_UNAVAILABLE to "El reconocimiento de voz no está disponible en este dispositivo.",
    Txt.VOICE_FAILED to "No se pudo reconocer la voz. Inténtalo de nuevo.",

    "module.overview" to "Inicio",
    "module.overview.subtitle" to "Lo que te necesita hoy",
    "module.conversations" to "Bandeja de entrada",
    "module.conversations.subtitle" to "Mensajes de clientes",
    "module.contacts" to "Contactos",
    "module.contacts.subtitle" to "Quién te escribe",
    "module.instagram" to "Instagram",
    "module.instagram.subtitle" to "Comentarios y respuestas",
    "module.clients" to "Clientes",
    "module.clients.subtitle" to "Tu lista de clientes",
    "module.services" to "Trabajos",
    "module.services.subtitle" to "Trabajo hecho y por facturar",
    "module.quotes" to "Presupuestos",
    "module.quotes.subtitle" to "Lo que has ofrecido",
    "module.invoices" to "Facturas",
    "module.invoices.subtitle" to "Lo que te deben",
    "module.suppliers" to "Proveedores",
    "module.suppliers.subtitle" to "A quién compras",
    "module.employees" to "Empleados",
    "module.employees.subtitle" to "Tu equipo",
    "module.payments" to "Pagos",
    "module.payments.subtitle" to "Lo que debes",
    "module.catalog" to "Catálogo",
    "module.catalog.subtitle" to "Tus servicios y productos",
    "module.bookings" to "Reservas",
    "module.bookings.subtitle" to "Tu agenda",
    "module.persona" to "Personalidad",
    "module.persona.subtitle" to "Cómo habla el asistente",
    "module.ai-assistant" to "Asistente",
    "module.ai-assistant.subtitle" to "Trabaja pidiendo",
    "module.agents" to "Agentes",
    "module.agents.subtitle" to "Aprobaciones y tareas",
    "module.settings" to "Configuración",
    "module.settings.subtitle" to "Idioma, canales, cuenta",

    "module.conversations.short" to "Mensajes",
    "module.ai-assistant.short" to "Asistente",

    "status.ACTIVE" to "Activo",
    "status.DISABLED" to "Desactivado",
    "status.BLOCKED" to "Bloqueado",
    "status.OPEN" to "Abierta",
    "status.DONE" to "Completada",
    "status.CANCELLED" to "Cancelada",
    "status.PENDING" to "Pendiente",
    "status.PENDENTE" to "Pendiente",
    "status.CONFIRMED" to "Confirmada",
    "status.COMPLETED" to "Completada",
    "status.NO_SHOW" to "No se presentó",
    "status.SENT" to "Enviado",
    "status.ENVIADO" to "Enviado",
    "status.ACCEPTED" to "Aceptado",
    "status.ACEITO" to "Aceptado",
    "status.REJECTED" to "Rechazado",
    "status.RECUSADO" to "Rechazado",
    "status.PAID" to "Pagada",
    "status.PAGA" to "Pagada",
    "status.UNPAID" to "No pagada",
    "status.OVERDUE" to "Vencida",
    "status.INVOICED" to "Facturado",
    "status.DRAFT" to "Borrador",
    "status.PAUSED" to "En pausa",
    "status.ARCHIVED" to "Archivado",
    "status.FAILED" to "Falló",
    "status.DELIVERED" to "Entregado",
    "status.READ" to "Leído",
    "status.QUEUED" to "En cola",
    "status.RUNNING" to "En curso",
    "status.WAITING" to "En espera",
    "status.SUCCEEDED" to "Completada",
    "status.COMPILING" to "Reconstruyendo",
    "status.READY" to "Listo",

    "attention.waiting_chat" to "Esperando respuesta",
    "attention.overdue_invoice" to "Factura vencida",
    "attention.due_soon_invoice" to "Factura por vencer",
    "attention.overdue_payment" to "Pago vencido",
    "attention.due_soon_payment" to "Pago por vencer",
    "attention.pending_booking" to "Reserva por confirmar",
    "attention.instagram_comment" to "Comentario por responder",
    "attention.quote_expiring" to "Presupuesto por caducar",
    "attention.assistant_action" to "Acción por confirmar",
    "attention.agent_approval" to "Agente esperando aprobación",
    "attention.agent_task_due" to "Tarea por vencer",
    "attention.agent_failed" to "Falló una ejecución de agente",
    "attention.integration_reconnect" to "Hay que volver a conectar",

    "weekday.1" to "Lunes",
    "weekday.2" to "Martes",
    "weekday.3" to "Miércoles",
    "weekday.4" to "Jueves",
    "weekday.5" to "Viernes",
    "weekday.6" to "Sábado",
    "weekday.7" to "Domingo",
)
