package com.rfm.edubot.mobile.core.localization

/** European Portuguese. Tested to carry exactly the keys [englishCatalog] has. */
internal val portugueseCatalog: Map<String, String> = mapOf(
    Txt.ACTION_SAVE to "Guardar",
    Txt.ACTION_CANCEL to "Cancelar",
    Txt.ACTION_CONFIRM to "Confirmar",
    Txt.ACTION_RETRY to "Tentar novamente",
    Txt.ACTION_REFRESH to "Atualizar",
    Txt.ACTION_BACK to "Voltar",
    Txt.ACTION_CLOSE to "Fechar",
    Txt.ACTION_NEW to "Novo",
    Txt.ACTION_SEND to "Enviar",
    Txt.ACTION_SEARCH to "Procurar",
    Txt.ACTION_SIGN_IN to "Entrar",
    Txt.ACTION_SIGN_OUT to "Sair",
    Txt.ACTION_APPROVE to "Aprovar",
    Txt.ACTION_REJECT to "Recusar",
    Txt.ACTION_DONE to "Concluir",
    Txt.ACTION_REOPEN to "Reabrir",
    Txt.ACTION_PAUSE to "Pausar",
    Txt.ACTION_RESUME to "Retomar",
    Txt.ACTION_MARK_PAID to "Marcar como paga",
    Txt.ACTION_MARK_ALL_READ to "Marcar todas como lidas",
    Txt.ACTION_LOAD_MORE to "Ver mais",
    Txt.ACTION_SHOW to "Mostrar",
    Txt.ACTION_HIDE to "Ocultar",

    Txt.LABEL_ALL to "Todas",
    Txt.LABEL_OPEN to "Abertas",
    Txt.LABEL_TODAY to "Hoje",
    Txt.LABEL_OPTIONAL to "opcional",
    Txt.LABEL_REQUIRED to "obrigatório",
    Txt.LABEL_NONE to "Nenhum",
    Txt.LABEL_TOTAL to "Total",
    Txt.LABEL_UNTITLED to "Sem título",

    Txt.LOGIN_TITLE to "Entrar",
    Txt.LOGIN_DESCRIPTION to "Gira o seu assistente em qualquer lugar.",
    Txt.LOGIN_EMAIL to "Email",
    Txt.LOGIN_PASSWORD to "Palavra-passe",
    Txt.LOGIN_ERROR_MISSING to "Introduza o email e a palavra-passe.",
    Txt.LOGIN_ERROR_INVALID to "Estes dados não foram aceites. Verifique e tente novamente.",
    Txt.LOGIN_ERROR_EXPIRED to "A sessão expirou. Entre novamente.",
    Txt.LOGIN_ERROR_INACTIVE to "Esta conta não está ativa. Peça a um administrador para a ativar.",
    Txt.LOGIN_ERROR_CONNECTION to "Não foi possível ligar ao painel. Verifique a ligação.",
    Txt.LOGIN_SECURITY_NOTE to "Os seus dados ficam restritos à empresa desta conta.",

    Txt.ERROR_UNAUTHORIZED to "A sua sessão terminou.",
    Txt.ERROR_FORBIDDEN to "O seu plano ou o seu perfil não inclui isto.",
    Txt.ERROR_NOT_FOUND to "Isto já não existe.",
    Txt.ERROR_OFFLINE to "Sem ligação ao painel.",
    Txt.ERROR_SERVER to "O painel teve um problema. Tente dentro de pouco.",
    Txt.ERROR_REJECTED to "Não foi possível guardar.",
    "error.code.tax_id_required" to "O NIF é obrigatório.",
    "error.code.address_required" to "A morada é obrigatória.",
    "error.code.invalid_email" to "Esse email não é válido.",
    "error.code.address_too_long" to "Essa morada é demasiado longa.",
    "error.code.tax_id_too_long" to "Esse NIF é demasiado longo.",
    "error.code.id_taken" to "Esse código já é usado por outro artigo.",
    "error.code.phone_taken" to "Outro registo já usa esse número.",
    "error.code.in_use" to "Isto está a ser usado e não pode ser removido.",
    "error.code.name_required" to "O nome é obrigatório.",
    "error.code.invalid_time" to "Essa hora não é válida.",
    "error.code.slot_taken" to "Essa hora já está ocupada.",
    "error.code.outside_hours" to "Essa hora está fora do seu horário.",
    "error.code.client_not_found" to "Nenhum cliente corresponde.",
    "error.code.no_user_account" to "Uma sessão de suporte não pode alterar a conta.",

    Txt.OFFLINE_SNAPSHOT to "A mostrar os últimos dados guardados",
    Txt.OFFLINE_SNAPSHOT_DETAIL to "Guardados neste dispositivo. Atualizam assim que houver ligação.",
    Txt.EMPTY_TITLE to "Ainda não há nada aqui",

    Txt.NAV_MORE to "Mais",
    Txt.NAV_GROUP_HOME to "Início",
    Txt.NAV_GROUP_INBOX to "Caixa de entrada",
    Txt.NAV_GROUP_BUSINESS to "Negócio",
    Txt.NAV_GROUP_AUTOMATION to "Automação",
    Txt.NAV_GROUP_SETUP to "Configuração",
    Txt.NAV_WEB_ONLY to "No painel web",
    Txt.NAV_WEB_ONLY_DETAIL to "O seu plano inclui estes e a aplicação ainda não os mostra.",

    Txt.OVERVIEW_SNAPSHOT to "Resumo operacional",
    Txt.OVERVIEW_NEEDS_YOU to "Precisa de si",
    Txt.OVERVIEW_NEEDS_YOU_EMPTY to "Não há nada à sua espera.",
    Txt.OVERVIEW_AGENDA to "Agenda",
    Txt.OVERVIEW_MESSAGES_TODAY to "Mensagens hoje",
    Txt.OVERVIEW_WAITING to "À espera",
    Txt.OVERVIEW_CONTACTS to "Contactos",
    Txt.OVERVIEW_CONVERSATIONS to "Conversas",
    Txt.OVERVIEW_COLLECTED_MONTH to "Recebido este mês",
    Txt.OVERVIEW_OUTSTANDING to "A receber",
    Txt.OVERVIEW_OVERDUE to "Em atraso",
    Txt.OVERVIEW_PIPELINE_OPEN to "Orçamentos abertos",
    Txt.OVERVIEW_BOOKINGS_TODAY to "Marcações hoje",
    Txt.OVERVIEW_BOOKINGS_PENDING to "Por confirmar",
    Txt.OVERVIEW_APPROVALS to "Aprovações",
    Txt.OVERVIEW_TASKS to "Tarefas abertas",
    Txt.OVERVIEW_GENERATED_AT to "Atualizado às {time}",

    Txt.INBOX_TITLE to "Caixa de entrada",
    Txt.INBOX_FILTER_NEEDS_REPLY to "Por responder",
    Txt.INBOX_FILTER_UNREAD to "Não lidas",
    Txt.INBOX_FILTER_PAUSED to "IA em pausa",
    Txt.INBOX_EMPTY to "Ainda não há conversas.",
    Txt.INBOX_MESSAGE_PLACEHOLDER to "Escreva uma mensagem",
    Txt.INBOX_AUTO_REPLY_ON to "O assistente está a responder",
    Txt.INBOX_AUTO_REPLY_OFF to "O assistente está em pausa aqui",
    Txt.INBOX_WINDOW_CLOSED to "A janela de 24 horas fechou. Só é possível enviar um modelo aprovado.",
    Txt.INBOX_SEND_FAILED to "Não entregue",
    Txt.INBOX_ATTACHMENT to "Anexo",
    Txt.INBOX_WRITTEN_BY_AGENT to "Enviado por {name}",
    Txt.INBOX_WEB_REPLY_UNAVAILABLE to "Responder a conversas do site ainda não está disponível na aplicação.",
    "inbox.messagesCount.one" to "{count} mensagem",
    "inbox.messagesCount.other" to "{count} mensagens",

    Txt.CONTACTS_TITLE to "Contactos",
    Txt.CONTACTS_EMPTY to "Ainda não há contactos.",
    Txt.CONTACTS_BLOCK to "Bloquear",
    Txt.CONTACTS_UNBLOCK to "Desbloquear",
    Txt.CONTACTS_LAST_SEEN to "Visto {time}",

    Txt.CRM_CLIENTS_TITLE to "Clientes",
    Txt.CRM_CLIENTS_EMPTY to "Ainda não há clientes.",
    Txt.CRM_CLIENT_NAME to "Nome",
    Txt.CRM_CLIENT_PHONE to "Telefone",
    Txt.CRM_CLIENT_TAX_ID to "NIF",
    Txt.CRM_CLIENT_TAX_ID_HINT to "Sem ele não é possível emitir orçamentos nem faturas.",
    Txt.CRM_CLIENT_ADDRESS to "Morada",
    Txt.CRM_CLIENT_EMAIL to "Email",
    Txt.CRM_CLIENT_CITY to "Localidade",
    Txt.CRM_CLIENT_POSTAL_CODE to "Código postal",
    Txt.CRM_CLIENT_CREATE to "Adicionar cliente",
    Txt.CRM_QUOTES_TITLE to "Orçamentos",
    Txt.CRM_QUOTES_EMPTY to "Ainda não há orçamentos.",
    Txt.CRM_QUOTE_CONVERT to "Transformar em fatura",
    Txt.CRM_QUOTE_VALID_UNTIL to "Válido até",
    Txt.CRM_INVOICES_TITLE to "Faturas",
    Txt.CRM_INVOICES_EMPTY to "Ainda não há faturas.",
    Txt.CRM_INVOICE_DUE_DATE to "Data de vencimento",
    Txt.CRM_INVOICE_OVERDUE to "Em atraso",
    Txt.CRM_CATALOG_TITLE to "Catálogo",
    Txt.CRM_CATALOG_EMPTY to "Ainda não há artigos.",
    Txt.CRM_CATALOG_ITEM_TITLE to "Título",
    Txt.CRM_CATALOG_ITEM_CODE to "Código",
    Txt.CRM_CATALOG_CATEGORY to "Categoria",
    Txt.CRM_CATALOG_UNIT to "Unidade",
    Txt.CRM_CATALOG_PRICE to "Preço unitário",
    Txt.CRM_CATALOG_TYPE_SERVICE to "Serviço",
    Txt.CRM_CATALOG_TYPE_PRODUCT to "Produto",
    Txt.CRM_SERVICES_TITLE to "Serviços",
    Txt.CRM_SERVICES_EMPTY to "Ainda não há serviços.",
    Txt.CRM_SERVICES_INVOICE_SELECTED to "Faturar {count} selecionados",
    Txt.CRM_PAYMENTS_TITLE to "Pagamentos",
    Txt.CRM_PAYMENTS_EMPTY to "Ainda não há pagamentos.",
    Txt.CRM_SUPPLIERS_TITLE to "Fornecedores",
    Txt.CRM_SUPPLIERS_EMPTY to "Ainda não há fornecedores.",
    Txt.CRM_EMPLOYEES_TITLE to "Funcionários",
    Txt.CRM_EMPLOYEES_EMPTY to "Ainda não há funcionários.",
    Txt.CRM_LINE_DESCRIPTION to "Descrição",
    Txt.CRM_LINE_QUANTITY to "Quantidade",
    Txt.CRM_LINE_UNIT_PRICE to "Preço unitário",
    Txt.CRM_LINE_ADD to "Adicionar linha",
    Txt.CRM_NOTES to "Notas",
    Txt.CRM_LINES to "Linhas",
    Txt.CRM_PICK_CLIENT to "Escolher cliente",
    Txt.CRM_DATE_FORMAT_HINT to "AAAA-MM-DD",

    Txt.BOOKINGS_TITLE to "Marcações",
    Txt.BOOKINGS_EMPTY to "Nada marcado.",
    Txt.BOOKINGS_UPCOMING to "Próximas",
    Txt.BOOKINGS_NEEDS_CONFIRM to "Por confirmar",
    Txt.BOOKINGS_BILLABLE to "Concluídas, não faturadas",
    Txt.BOOKINGS_OPENING_HOURS to "Horário",
    Txt.BOOKINGS_CLOSED to "Fechado",
    Txt.BOOKINGS_SERVICE to "Serviço",

    Txt.AGENTS_TITLE to "Agentes",
    Txt.AGENTS_TAB_INBOX to "Para decidir",
    Txt.AGENTS_TAB_AGENTS to "Agentes",
    Txt.AGENTS_TAB_ACTIVITY to "Atividade",
    Txt.AGENTS_APPROVALS to "À espera de aprovação",
    Txt.AGENTS_APPROVALS_EMPTY to "Nenhum agente está à sua espera.",
    Txt.AGENTS_TASKS to "Tarefas",
    Txt.AGENTS_TASKS_EMPTY to "Não há tarefas abertas.",
    Txt.AGENTS_EMPTY to "Ainda não há agentes.",
    Txt.AGENTS_PAUSED_BY_PLATFORM to "O suporte pausou todos os agentes. Só o suporte os pode retomar.",
    Txt.AGENTS_PAUSED_COMPANY to "Todos os agentes desta empresa estão em pausa.",
    Txt.AGENTS_CANNOT_DECIDE to "O seu perfil não pode decidir esta.",
    Txt.AGENTS_EXPIRES to "Expira em {days} dias",
    Txt.AGENTS_EXPIRES_TODAY to "Expira hoje",
    Txt.AGENTS_REJECT_REASON to "Porque está a recusar?",
    Txt.AGENTS_RUNS_TODAY to "Execuções hoje",
    Txt.AGENTS_ACTIVE to "Ativos",
    Txt.AGENTS_FAILED_WEEK to "Falhas esta semana",
    Txt.AGENTS_ACTIVITY_EMPTY to "Ainda não houve execuções.",
    Txt.AGENTS_DUE to "Para {date}",
    Txt.AGENTS_BUILDER_WEB_ONLY to "Crie e edite agentes no painel web.",

    Txt.NOTIFICATIONS_TITLE to "Notificações",
    Txt.NOTIFICATIONS_EMPTY to "Nada a reportar.",
    Txt.NOTIFICATIONS_GENERIC to "Algo precisa da sua atenção.",
    Txt.NOTIFICATIONS_UNREAD to "{count} não lidas",
    "notification.agent_approval_pending" to "{agentName} está à espera da sua aprovação.",
    "notification.agent_task_assigned" to "{agentName} deixou-lhe uma tarefa: {title}",
    "notification.agent_run_failed" to "{agentName} não conseguiu terminar uma execução.",
    "notification.agent_paused" to "{agentName} foi pausado.",
    "notification.invoice_overdue" to "A fatura {number} está em atraso.",
    "notification.quote_accepted" to "O orçamento {number} foi aceite.",
    "notification.booking_pending" to "{contactName} pediu uma marcação.",
    "notification.integration_disconnected" to "É preciso voltar a ligar {provider}.",
    "notification.conversation_waiting" to "{contactName} está à espera de resposta.",

    Txt.ASSISTANT_TITLE to "Assistente",
    Txt.ASSISTANT_EMPTY to "Ainda não há conversas com o assistente.",
    Txt.ASSISTANT_START_THREAD to "Comece uma conversa para trabalhar com o assistente.",
    Txt.ASSISTANT_NEW_THREAD to "Nova conversa",
    Txt.ASSISTANT_PROMPT_PLACEHOLDER to "Peça algo",
    Txt.ASSISTANT_ACTION_PENDING to "À espera da sua confirmação",
    Txt.ASSISTANT_THREADS to "Conversas",

    Txt.PERSONA_TITLE to "Personalidade",
    Txt.PERSONA_INSTRUCTIONS to "Instruções",
    Txt.PERSONA_VERSION to "Versão {version}",
    Txt.PERSONA_TOKENS to "{count} tokens",
    Txt.PERSONA_COMPILING to "A reconstruir o prompt",
    Txt.PERSONA_REBUILD to "Reconstruir",
    Txt.PERSONA_SOURCES to "Fontes",
    Txt.PERSONA_SOURCES_EMPTY to "Ainda não há fontes.",
    Txt.PERSONA_ADD_NOTE to "Adicionar nota",
    Txt.PERSONA_NOTE_PLACEHOLDER to "Algo que o assistente deve saber",
    Txt.PERSONA_TEST to "Testar",
    Txt.PERSONA_TEST_PLACEHOLDER to "Escreva o que um cliente diria",
    Txt.PERSONA_SOURCE_PENDING to "Ainda fora do prompt",
    Txt.PERSONA_FILE_WEB_ONLY to "Carregue documentos no painel web.",

    Txt.SETTINGS_TITLE to "Definições",
    Txt.SETTINGS_CHANNELS to "Canais",
    Txt.SETTINGS_CHANNELS_EMPTY to "Nenhum canal ligado.",
    Txt.SETTINGS_LANGUAGE to "Idioma",
    Txt.SETTINGS_APPEARANCE to "Aspeto",
    Txt.SETTINGS_THEME_LIGHT to "Claro",
    Txt.SETTINGS_THEME_DARK to "Escuro",
    Txt.SETTINGS_THEME_SYSTEM to "Do sistema",
    Txt.SETTINGS_ACCOUNT to "Conta",
    Txt.SETTINGS_COMPANIES to "Empresas",
    Txt.SETTINGS_COMPANY_SWITCH to "Mudar",
    Txt.SETTINGS_WIDGET to "Widget do site",
    Txt.SETTINGS_WIDGET_KEY to "Chave pública",
    Txt.SETTINGS_OPERATOR_SESSION to "Entrou como suporte, apenas para esta empresa.",
    Txt.SETTINGS_WEB_FOR_MORE to "Canais, modelos e o desenho dos documentos configuram-se no painel web.",

    Txt.VOICE_START to "Voz",
    Txt.VOICE_STOP to "Parar",
    Txt.VOICE_LISTENING to "A ouvir",
    Txt.VOICE_PERMISSION_DENIED to "É necessária autorização para o microfone e reconhecimento de voz.",
    Txt.VOICE_UNAVAILABLE to "O reconhecimento de voz não está disponível neste dispositivo.",
    Txt.VOICE_FAILED to "Não foi possível reconhecer a fala. Tente novamente.",

    "module.overview" to "Início",
    "module.overview.subtitle" to "O que precisa de si hoje",
    "module.conversations" to "Caixa de entrada",
    "module.conversations.subtitle" to "Mensagens de clientes",
    "module.contacts" to "Contactos",
    "module.contacts.subtitle" to "Quem lhe escreve",
    "module.instagram" to "Instagram",
    "module.instagram.subtitle" to "Comentários e respostas",
    "module.clients" to "Clientes",
    "module.clients.subtitle" to "A sua lista de clientes",
    "module.services" to "Serviços",
    "module.services.subtitle" to "Trabalho feito e a faturar",
    "module.quotes" to "Orçamentos",
    "module.quotes.subtitle" to "O que propôs",
    "module.invoices" to "Faturas",
    "module.invoices.subtitle" to "O que tem a receber",
    "module.suppliers" to "Fornecedores",
    "module.suppliers.subtitle" to "A quem compra",
    "module.employees" to "Funcionários",
    "module.employees.subtitle" to "A sua equipa",
    "module.payments" to "Pagamentos",
    "module.payments.subtitle" to "O que tem a pagar",
    "module.catalog" to "Catálogo",
    "module.catalog.subtitle" to "Os seus serviços e produtos",
    "module.bookings" to "Marcações",
    "module.bookings.subtitle" to "A sua agenda",
    "module.persona" to "Personalidade",
    "module.persona.subtitle" to "Como o assistente fala",
    "module.ai-assistant" to "Assistente",
    "module.ai-assistant.subtitle" to "Trabalhe pedindo",
    "module.agents" to "Agentes",
    "module.agents.subtitle" to "Aprovações e tarefas",
    "module.settings" to "Definições",
    "module.settings.subtitle" to "Idioma, canais, conta",

    "module.conversations.short" to "Mensagens",
    "module.ai-assistant.short" to "Assistente",

    "status.ACTIVE" to "Ativo",
    "status.DISABLED" to "Desativado",
    "status.BLOCKED" to "Bloqueado",
    "status.OPEN" to "Aberta",
    "status.DONE" to "Concluída",
    "status.CANCELLED" to "Cancelada",
    "status.PENDING" to "Pendente",
    "status.PENDENTE" to "Pendente",
    "status.CONFIRMED" to "Confirmada",
    "status.COMPLETED" to "Concluída",
    "status.NO_SHOW" to "Não compareceu",
    "status.SENT" to "Enviado",
    "status.ENVIADO" to "Enviado",
    "status.ACCEPTED" to "Aceite",
    "status.ACEITO" to "Aceite",
    "status.REJECTED" to "Recusado",
    "status.RECUSADO" to "Recusado",
    "status.PAID" to "Paga",
    "status.PAGA" to "Paga",
    "status.UNPAID" to "Não paga",
    "status.OVERDUE" to "Em atraso",
    "status.INVOICED" to "Faturado",
    "status.DRAFT" to "Rascunho",
    "status.PAUSED" to "Em pausa",
    "status.ARCHIVED" to "Arquivado",
    "status.FAILED" to "Falhou",
    "status.DELIVERED" to "Entregue",
    "status.READ" to "Lida",
    "status.QUEUED" to "Em fila",
    "status.RUNNING" to "A correr",
    "status.WAITING" to "À espera",
    "status.SUCCEEDED" to "Concluída",
    "status.COMPILING" to "A reconstruir",
    "status.READY" to "Pronto",

    "attention.waiting_chat" to "À espera de resposta",
    "attention.overdue_invoice" to "Fatura em atraso",
    "attention.due_soon_invoice" to "Fatura a vencer",
    "attention.overdue_payment" to "Pagamento em atraso",
    "attention.due_soon_payment" to "Pagamento a vencer",
    "attention.pending_booking" to "Marcação por confirmar",
    "attention.instagram_comment" to "Comentário por responder",
    "attention.quote_expiring" to "Orçamento a expirar",
    "attention.assistant_action" to "Ação por confirmar",
    "attention.agent_approval" to "Agente à espera de aprovação",
    "attention.agent_task_due" to "Tarefa a vencer",
    "attention.agent_failed" to "Execução de agente falhou",
    "attention.integration_reconnect" to "É preciso voltar a ligar",

    // Time clock.
    Txt.TIME_CLOCK to "Registo de ponto",
    Txt.TIME_STATE_OFF to "Sem entrada registada",
    Txt.TIME_STATE_WORKING to "A trabalhar",
    Txt.TIME_STATE_ON_BREAK to "Em pausa",
    Txt.TIME_WORKING_SINCE to "A trabalhar desde as {time}",
    Txt.TIME_ON_BREAK_SINCE to "Em pausa desde as {time}",
    Txt.TIME_OFF_HINT to "Registe a entrada quando começar a trabalhar.",
    Txt.TIME_CLOCK_IN to "Registar entrada",
    Txt.TIME_CLOCK_OUT to "Registar saída",
    Txt.TIME_BREAK_START to "Iniciar pausa",
    Txt.TIME_BREAK_END to "Terminar pausa",
    Txt.TIME_PUNCHED_IN to "Entrada registada",
    Txt.TIME_PUNCHED_OUT to "Saída registada",
    Txt.TIME_PUNCHED_BREAK_START to "Pausa iniciada",
    Txt.TIME_PUNCHED_BREAK_END to "De volta ao trabalho",
    Txt.TIME_TODAY to "Hoje",
    Txt.TIME_WEEK to "Esta semana",
    Txt.TIME_WEEK_OF_LIMIT to "{worked} de {limit} h",
    Txt.TIME_HM to "{h} h {m} min",
    Txt.TIME_MINUTES to "{m} min",
    Txt.TIME_LOCATING to "A verificar a sua localização…",
    Txt.TIME_CONFIRMING to "Confirme que é você…",
    Txt.TIME_LOCATION_NOTE to "A sua localização só é lida quando regista a entrada ou a saída, nunca entretanto.",
    Txt.TIME_LOCATION_OFF_NOTE to "A sua empresa não regista onde marca o ponto.",
    Txt.TIME_LAST to "Último: {what}",
    Txt.TIME_AT_SITE to "Em {site}",
    Txt.TIME_FROM_SITE to "A {distance} de {site}",
    Txt.TIME_NO_LOCATION to "Sem localização",
    Txt.TIME_LOCATED to "Localização registada",
    Txt.TIME_VERIFIED to "Confirmado com impressão digital ou rosto",
    Txt.TIME_NOT_VERIFIED to "Não verificado",
    Txt.TIME_OUTSIDE_SITES to "Está a {distance} de {site}. Registe a entrada quando lá chegar.",
    Txt.TIME_OVERDUE_TITLE to "Continua com a entrada registada desde {when}",
    Txt.TIME_OVERDUE_BODY to "Esqueceu-se de registar a saída? Indique a hora a que terminou e a equipa confirma.",
    Txt.TIME_OVERDUE_END to "Terminei às (HH:MM)",
    Txt.TIME_OVERDUE_SAVE to "Fechar o turno",
    Txt.TIME_OVERDUE_SAVED to "Turno fechado. A equipa vai confirmar.",
    Txt.TIME_HISTORY to "Os meus turnos",
    Txt.TIME_HISTORY_EMPTY to "As suas entradas e saídas aparecem aqui.",
    Txt.TIME_REVIEW_OPEN to "Em curso",
    Txt.TIME_REVIEW_PENDING to "Por rever",
    Txt.TIME_REVIEW_APPROVED to "Aprovado",
    Txt.TIME_BREAKS to "{time} de pausa",
    Txt.TIME_SETUP_TITLE to "Confirme as entradas com a impressão digital ou o rosto",
    Txt.TIME_SETUP_BODY to "O telemóvel confirma que é você e nunca partilha a sua impressão digital ou o seu rosto, nem com a sua empresa.",
    Txt.TIME_SETUP_REQUIRED to "A sua empresa pede-o: configure este telemóvel antes de registar a entrada.",
    Txt.TIME_SETUP_ACTION to "Configurar este telemóvel",
    Txt.TIME_SETUP_DONE to "Este telemóvel está configurado",
    Txt.TIME_PHONE_READY to "As entradas neste telemóvel são confirmadas com a impressão digital ou o rosto.",
    Txt.TIME_PROMPT_TITLE to "Confirme que é você",
    Txt.TIME_PROMPT_SETUP to "Configurar o registo de horas neste telemóvel",
    Txt.TIME_PROMPT_CANCEL to "Cancelar",
    Txt.TIME_PROBLEM_LOCATION_DENIED to "Autorize a localização desta app nas definições do telemóvel para registar a entrada.",
    Txt.TIME_PROBLEM_LOCATION_OFF to "Ligue a localização do telemóvel para registar a entrada.",
    Txt.TIME_PROBLEM_LOCATION_TIMEOUT to "A localização demorou demasiado. Tente novamente no exterior ou perto de uma janela.",
    Txt.TIME_PROBLEM_LOCATION_UNAVAILABLE to "O telemóvel não conseguiu encontrar a sua localização.",
    Txt.TIME_PROBLEM_BIOMETRIC_NONE to "Configure primeiro o desbloqueio com impressão digital ou rosto neste telemóvel.",
    Txt.TIME_PROBLEM_BIOMETRIC_UNAVAILABLE to "Este telemóvel não consegue confirmar que é você com impressão digital ou rosto.",
    Txt.TIME_PROBLEM_BIOMETRIC_LOCKED to "Demasiadas tentativas. Desbloqueie o telemóvel e tente novamente.",
    Txt.TIME_PROBLEM_BIOMETRIC_FAILED to "O telemóvel não conseguiu confirmar que é você. Tente novamente.",
    Txt.TIME_PROBLEM_KEY_CHANGED to "As impressões digitais ou o rosto deste telemóvel mudaram. Configure este telemóvel novamente.",
    Txt.TIME_PROBLEM_SETUP_NEEDED to "Configure este telemóvel antes de registar a entrada.",
    "module.my-hours" to "As minhas horas",
    "module.my-hours.subtitle" to "Registar entradas e saídas",
    "module.my-hours.short" to "Horas",
    "module.my-services" to "Os meus serviços",
    "module.my-services.subtitle" to "O trabalho que regista",
    "module.timesheets" to "Registo de horas",
    "module.timesheets.subtitle" to "As horas da equipa",
    "status.APPROVED" to "Aprovado",
    "time.flag.NO_LOCATION" to "Sem localização",
    "time.flag.LOW_ACCURACY" to "Localização imprecisa",
    "time.flag.MOCK_LOCATION" to "Localização simulada",
    "time.flag.OUTSIDE_SITE" to "Fora dos locais",
    "time.flag.UNVERIFIED" to "Não verificado",
    "time.flag.LONG_SHIFT" to "Turno longo",
    "time.flag.MISSED_CLOCK_OUT" to "Esqueceu a saída",
    "time.flag.EDITED" to "Corrigido",
    "time.flag.MANUAL" to "Adicionado pela equipa",
    "error.code.already_clocked_in" to "Já tem a entrada registada.",
    "error.code.not_clocked_in" to "Não tem a entrada registada.",
    "error.code.on_break" to "Já está em pausa.",
    "error.code.not_on_break" to "Não está em pausa.",
    "error.code.location_required" to "A sua empresa precisa da sua localização para registar a entrada.",
    "error.code.outside_sites" to "Não está em nenhum local de trabalho da sua empresa.",
    "error.code.mock_location" to "O telemóvel indica uma localização simulada, que não pode ser usada para registar a entrada.",
    "error.code.verification_required" to "A sua empresa pede que confirme as entradas com a impressão digital ou o rosto.",
    "error.code.device_not_enrolled" to "Este telemóvel já não está configurado para o registo de horas. Configure-o novamente.",
    "error.code.challenge_expired" to "Demorou demasiado. Tente novamente.",
    "error.code.invalid_signature" to "A confirmação do telemóvel não coincidiu. Configure este telemóvel novamente.",
    "error.code.not_overdue" to "Este turno ainda pode ser fechado registando a saída.",
    "error.code.end_before_last_punch" to "Isso é antes do seu último registo.",
    "error.code.in_future" to "Essa hora ainda não chegou.",
    "error.code.invalid_public_key" to "A chave deste telemóvel não pôde ser usada. Tente configurá-lo novamente.",
    "error.code.page_unavailable" to "A sua empresa não usa esta página.",

    "weekday.1" to "Segunda",
    "weekday.2" to "Terça",
    "weekday.3" to "Quarta",
    "weekday.4" to "Quinta",
    "weekday.5" to "Sexta",
    "weekday.6" to "Sábado",
    "weekday.7" to "Domingo",
)
