package com.rfm.edubot.mobile.core.localization

/**
 * English is the reference catalog: it carries every key, and the other locales are tested against
 * its key set so a new string cannot be added to one language only.
 */
internal val englishCatalog: Map<String, String> = mapOf(
    Txt.ACTION_SAVE to "Save",
    Txt.ACTION_CANCEL to "Cancel",
    Txt.ACTION_CONFIRM to "Confirm",
    Txt.ACTION_RETRY to "Try again",
    Txt.ACTION_REFRESH to "Refresh",
    Txt.ACTION_BACK to "Back",
    Txt.ACTION_CLOSE to "Close",
    Txt.ACTION_NEW to "New",
    Txt.ACTION_SEND to "Send",
    Txt.ACTION_SEARCH to "Search",
    Txt.ACTION_SIGN_IN to "Sign in",
    Txt.ACTION_SIGN_OUT to "Sign out",
    Txt.ACTION_APPROVE to "Approve",
    Txt.ACTION_REJECT to "Reject",
    Txt.ACTION_DONE to "Done",
    Txt.ACTION_REOPEN to "Reopen",
    Txt.ACTION_PAUSE to "Pause",
    Txt.ACTION_RESUME to "Resume",
    Txt.ACTION_MARK_PAID to "Mark paid",
    Txt.ACTION_MARK_ALL_READ to "Mark all read",
    Txt.ACTION_LOAD_MORE to "Load more",
    Txt.ACTION_SHOW to "Show",
    Txt.ACTION_HIDE to "Hide",

    Txt.LABEL_ALL to "All",
    Txt.LABEL_OPEN to "Open",
    Txt.LABEL_TODAY to "Today",
    Txt.LABEL_OPTIONAL to "optional",
    Txt.LABEL_REQUIRED to "required",
    Txt.LABEL_NONE to "None",
    Txt.LABEL_TOTAL to "Total",
    Txt.LABEL_UNTITLED to "Untitled",

    Txt.LOGIN_TITLE to "Sign in",
    Txt.LOGIN_DESCRIPTION to "Manage your assistant from anywhere.",
    Txt.LOGIN_EMAIL to "Email",
    Txt.LOGIN_PASSWORD to "Password",
    Txt.LOGIN_ERROR_MISSING to "Enter your email and password.",
    Txt.LOGIN_ERROR_INVALID to "Those credentials were not accepted. Check them and try again.",
    Txt.LOGIN_ERROR_EXPIRED to "Your session has expired. Please sign in again.",
    Txt.LOGIN_ERROR_INACTIVE to "This account is not active. Ask an administrator to enable it.",
    Txt.LOGIN_ERROR_CONNECTION to "Could not reach the dashboard. Check your connection.",
    Txt.LOGIN_SECURITY_NOTE to "Your data stays scoped to the company this account belongs to.",

    Txt.ERROR_UNAUTHORIZED to "Your session has ended.",
    Txt.ERROR_FORBIDDEN to "Your plan or your role does not include this.",
    Txt.ERROR_NOT_FOUND to "That is no longer there.",
    Txt.ERROR_OFFLINE to "No connection to the dashboard.",
    Txt.ERROR_SERVER to "The dashboard had a problem. Try again shortly.",
    Txt.ERROR_REJECTED to "That could not be saved.",
    "error.code.tax_id_required" to "A NIF is required.",
    "error.code.address_required" to "An address is required.",
    "error.code.invalid_email" to "That email address is not valid.",
    "error.code.address_too_long" to "That address is too long.",
    "error.code.tax_id_too_long" to "That NIF is too long.",
    "error.code.id_taken" to "That code is already used by another item.",
    "error.code.phone_taken" to "Another record already uses that phone number.",
    "error.code.in_use" to "This is used elsewhere and cannot be removed.",
    "error.code.name_required" to "A name is required.",
    "error.code.invalid_time" to "That time is not valid.",
    "error.code.slot_taken" to "Someone already has that time.",
    "error.code.outside_hours" to "That time is outside your opening hours.",
    "error.code.client_not_found" to "No client matches that.",
    "error.code.no_user_account" to "An operator session cannot change account settings.",

    Txt.OFFLINE_SNAPSHOT to "Showing your last snapshot",
    Txt.OFFLINE_SNAPSHOT_DETAIL to "Saved on this device. It refreshes as soon as there is a connection.",
    Txt.EMPTY_TITLE to "Nothing here yet",

    Txt.NAV_MORE to "More",
    Txt.NAV_GROUP_HOME to "Home",
    Txt.NAV_GROUP_INBOX to "Inbox",
    Txt.NAV_GROUP_BUSINESS to "Business",
    Txt.NAV_GROUP_AUTOMATION to "Automation",
    Txt.NAV_GROUP_SETUP to "Setup",
    Txt.NAV_WEB_ONLY to "On the web dashboard",
    Txt.NAV_WEB_ONLY_DETAIL to "Your plan includes these, and the app does not show them yet.",

    Txt.OVERVIEW_SNAPSHOT to "Operational snapshot",
    Txt.OVERVIEW_NEEDS_YOU to "Needs you",
    Txt.OVERVIEW_NEEDS_YOU_EMPTY to "Nothing is waiting on you.",
    Txt.OVERVIEW_AGENDA to "Agenda",
    Txt.OVERVIEW_MESSAGES_TODAY to "Messages today",
    Txt.OVERVIEW_WAITING to "Waiting",
    Txt.OVERVIEW_CONTACTS to "Contacts",
    Txt.OVERVIEW_CONVERSATIONS to "Conversations",
    Txt.OVERVIEW_COLLECTED_MONTH to "Received this month",
    Txt.OVERVIEW_OUTSTANDING to "To collect",
    Txt.OVERVIEW_OVERDUE to "Overdue",
    Txt.OVERVIEW_PIPELINE_OPEN to "Open quotes",
    Txt.OVERVIEW_BOOKINGS_TODAY to "Bookings today",
    Txt.OVERVIEW_BOOKINGS_PENDING to "To confirm",
    Txt.OVERVIEW_APPROVALS to "Approvals",
    Txt.OVERVIEW_TASKS to "Open tasks",
    Txt.OVERVIEW_GENERATED_AT to "Updated {time}",

    Txt.INBOX_TITLE to "Inbox",
    Txt.INBOX_FILTER_NEEDS_REPLY to "Needs reply",
    Txt.INBOX_FILTER_UNREAD to "Unread",
    Txt.INBOX_FILTER_PAUSED to "AI paused",
    Txt.INBOX_EMPTY to "No conversations yet.",
    Txt.INBOX_MESSAGE_PLACEHOLDER to "Write a message",
    Txt.INBOX_AUTO_REPLY_ON to "The assistant is answering",
    Txt.INBOX_AUTO_REPLY_OFF to "The assistant is paused here",
    Txt.INBOX_WINDOW_CLOSED to "The 24-hour window is closed. Only an approved template can be sent.",
    Txt.INBOX_SEND_FAILED to "Not delivered",
    Txt.INBOX_ATTACHMENT to "Attachment",
    Txt.INBOX_WRITTEN_BY_AGENT to "Sent by {name}",
    Txt.INBOX_WEB_REPLY_UNAVAILABLE to "Replies to website chats are not available in the app yet.",
    "inbox.messagesCount.one" to "{count} message",
    "inbox.messagesCount.other" to "{count} messages",

    Txt.CONTACTS_TITLE to "Contacts",
    Txt.CONTACTS_EMPTY to "No contacts yet.",
    Txt.CONTACTS_BLOCK to "Block",
    Txt.CONTACTS_UNBLOCK to "Unblock",
    Txt.CONTACTS_LAST_SEEN to "Seen {time}",

    Txt.CRM_CLIENTS_TITLE to "Clients",
    Txt.CRM_CLIENTS_EMPTY to "No clients yet.",
    Txt.CRM_CLIENT_NAME to "Name",
    Txt.CRM_CLIENT_PHONE to "Phone",
    Txt.CRM_CLIENT_TAX_ID to "NIF",
    Txt.CRM_CLIENT_TAX_ID_HINT to "Quotes and invoices will not issue without it.",
    Txt.CRM_CLIENT_ADDRESS to "Address",
    Txt.CRM_CLIENT_EMAIL to "Email",
    Txt.CRM_CLIENT_CITY to "City",
    Txt.CRM_CLIENT_POSTAL_CODE to "Postal code",
    Txt.CRM_CLIENT_CREATE to "Add client",
    Txt.CRM_QUOTES_TITLE to "Quotes",
    Txt.CRM_QUOTES_EMPTY to "No quotes yet.",
    Txt.CRM_QUOTE_CONVERT to "Turn into invoice",
    Txt.CRM_QUOTE_VALID_UNTIL to "Valid until",
    Txt.CRM_INVOICES_TITLE to "Invoices",
    Txt.CRM_INVOICES_EMPTY to "No invoices yet.",
    Txt.CRM_INVOICE_DUE_DATE to "Due date",
    Txt.CRM_INVOICE_OVERDUE to "Overdue",
    Txt.CRM_CATALOG_TITLE to "Catalog",
    Txt.CRM_CATALOG_EMPTY to "No catalog items yet.",
    Txt.CRM_CATALOG_ITEM_TITLE to "Title",
    Txt.CRM_CATALOG_ITEM_CODE to "Code",
    Txt.CRM_CATALOG_CATEGORY to "Category",
    Txt.CRM_CATALOG_UNIT to "Unit",
    Txt.CRM_CATALOG_PRICE to "Unit price",
    Txt.CRM_CATALOG_TYPE_SERVICE to "Service",
    Txt.CRM_CATALOG_TYPE_PRODUCT to "Product",
    Txt.CRM_SERVICES_TITLE to "Jobs",
    Txt.CRM_SERVICES_EMPTY to "No jobs yet.",
    Txt.CRM_SERVICES_INVOICE_SELECTED to "Invoice {count} selected",
    Txt.CRM_PAYMENTS_TITLE to "Payments",
    Txt.CRM_PAYMENTS_EMPTY to "No payments yet.",
    Txt.CRM_SUPPLIERS_TITLE to "Suppliers",
    Txt.CRM_SUPPLIERS_EMPTY to "No suppliers yet.",
    Txt.CRM_EMPLOYEES_TITLE to "Employees",
    Txt.CRM_EMPLOYEES_EMPTY to "No employees yet.",
    Txt.CRM_LINE_DESCRIPTION to "Description",
    Txt.CRM_LINE_QUANTITY to "Quantity",
    Txt.CRM_LINE_UNIT_PRICE to "Unit price",
    Txt.CRM_LINE_ADD to "Add line",
    Txt.CRM_NOTES to "Notes",
    Txt.CRM_LINES to "Lines",
    Txt.CRM_PICK_CLIENT to "Choose a client",
    Txt.CRM_DATE_FORMAT_HINT to "YYYY-MM-DD",

    Txt.BOOKINGS_TITLE to "Bookings",
    Txt.BOOKINGS_EMPTY to "Nothing booked.",
    Txt.BOOKINGS_UPCOMING to "Upcoming",
    Txt.BOOKINGS_NEEDS_CONFIRM to "To confirm",
    Txt.BOOKINGS_BILLABLE to "Finished, not invoiced",
    Txt.BOOKINGS_OPENING_HOURS to "Opening hours",
    Txt.BOOKINGS_CLOSED to "Closed",
    Txt.BOOKINGS_SERVICE to "Service",

    Txt.AGENTS_TITLE to "Agents",
    Txt.AGENTS_TAB_INBOX to "To decide",
    Txt.AGENTS_TAB_AGENTS to "Agents",
    Txt.AGENTS_TAB_ACTIVITY to "Activity",
    Txt.AGENTS_APPROVALS to "Waiting for approval",
    Txt.AGENTS_APPROVALS_EMPTY to "No agent is waiting on you.",
    Txt.AGENTS_TASKS to "Tasks",
    Txt.AGENTS_TASKS_EMPTY to "No open tasks.",
    Txt.AGENTS_EMPTY to "No agents yet.",
    Txt.AGENTS_PAUSED_BY_PLATFORM to "Support paused every agent. Only support can resume them.",
    Txt.AGENTS_PAUSED_COMPANY to "Every agent is paused for this company.",
    Txt.AGENTS_CANNOT_DECIDE to "Your role cannot decide this one.",
    Txt.AGENTS_EXPIRES to "Expires in {days} days",
    Txt.AGENTS_EXPIRES_TODAY to "Expires today",
    Txt.AGENTS_REJECT_REASON to "Why are you rejecting it?",
    Txt.AGENTS_RUNS_TODAY to "Runs today",
    Txt.AGENTS_ACTIVE to "Active",
    Txt.AGENTS_FAILED_WEEK to "Failed this week",
    Txt.AGENTS_ACTIVITY_EMPTY to "No runs yet.",
    Txt.AGENTS_DUE to "Due {date}",
    Txt.AGENTS_BUILDER_WEB_ONLY to "Build and edit agents on the web dashboard.",

    Txt.NOTIFICATIONS_TITLE to "Notifications",
    Txt.NOTIFICATIONS_EMPTY to "Nothing to report.",
    Txt.NOTIFICATIONS_GENERIC to "Something needs your attention.",
    Txt.NOTIFICATIONS_UNREAD to "{count} unread",
    "notification.agent_approval_pending" to "{agentName} is waiting for your approval.",
    "notification.agent_task_assigned" to "{agentName} left you a task: {title}",
    "notification.agent_run_failed" to "{agentName} failed to finish a run.",
    "notification.agent_paused" to "{agentName} was paused.",
    "notification.invoice_overdue" to "Invoice {number} is overdue.",
    "notification.quote_accepted" to "Quote {number} was accepted.",
    "notification.booking_pending" to "{contactName} asked for a booking.",
    "notification.integration_disconnected" to "{provider} needs to be reconnected.",
    "notification.conversation_waiting" to "{contactName} is waiting for a reply.",

    Txt.ASSISTANT_TITLE to "Assistant",
    Txt.ASSISTANT_EMPTY to "No conversations with your assistant yet.",
    Txt.ASSISTANT_START_THREAD to "Start a thread to work with your assistant.",
    Txt.ASSISTANT_NEW_THREAD to "New thread",
    Txt.ASSISTANT_PROMPT_PLACEHOLDER to "Ask for something",
    Txt.ASSISTANT_ACTION_PENDING to "Waiting for you to confirm",
    Txt.ASSISTANT_THREADS to "Threads",

    Txt.PERSONA_TITLE to "Persona",
    Txt.PERSONA_INSTRUCTIONS to "Instructions",
    Txt.PERSONA_VERSION to "Version {version}",
    Txt.PERSONA_TOKENS to "{count} tokens",
    Txt.PERSONA_COMPILING to "Rebuilding the prompt",
    Txt.PERSONA_REBUILD to "Rebuild",
    Txt.PERSONA_SOURCES to "Sources",
    Txt.PERSONA_SOURCES_EMPTY to "No sources yet.",
    Txt.PERSONA_ADD_NOTE to "Add a note",
    Txt.PERSONA_NOTE_PLACEHOLDER to "Something the assistant should know",
    Txt.PERSONA_TEST to "Test",
    Txt.PERSONA_TEST_PLACEHOLDER to "Write what a customer would say",
    Txt.PERSONA_SOURCE_PENDING to "Not in the prompt yet",
    Txt.PERSONA_FILE_WEB_ONLY to "Upload documents on the web dashboard.",

    Txt.SETTINGS_TITLE to "Settings",
    Txt.SETTINGS_CHANNELS to "Channels",
    Txt.SETTINGS_CHANNELS_EMPTY to "No channel connected.",
    Txt.SETTINGS_LANGUAGE to "Language",
    Txt.SETTINGS_APPEARANCE to "Appearance",
    Txt.SETTINGS_THEME_LIGHT to "Light",
    Txt.SETTINGS_THEME_DARK to "Dark",
    Txt.SETTINGS_THEME_SYSTEM to "System",
    Txt.SETTINGS_ACCOUNT to "Account",
    Txt.SETTINGS_COMPANIES to "Companies",
    Txt.SETTINGS_COMPANY_SWITCH to "Switch",
    Txt.SETTINGS_WIDGET to "Website widget",
    Txt.SETTINGS_WIDGET_KEY to "Public key",
    Txt.SETTINGS_OPERATOR_SESSION to "You are signed in as support, for this company only.",
    Txt.SETTINGS_WEB_FOR_MORE to "Channels, templates and document design are set up on the web dashboard.",

    Txt.VOICE_START to "Voice",
    Txt.VOICE_STOP to "Stop",
    Txt.VOICE_LISTENING to "Listening",
    Txt.VOICE_PERMISSION_DENIED to "Microphone and speech recognition permission is required.",
    Txt.VOICE_UNAVAILABLE to "Speech recognition is unavailable on this device.",
    Txt.VOICE_FAILED to "Speech could not be recognized. Please try again.",

    "module.overview" to "Home",
    "module.overview.subtitle" to "What needs you today",
    "module.conversations" to "Inbox",
    "module.conversations.subtitle" to "Customer messages",
    "module.contacts" to "Contacts",
    "module.contacts.subtitle" to "Who writes to you",
    "module.instagram" to "Instagram",
    "module.instagram.subtitle" to "Comments and replies",
    "module.clients" to "Clients",
    "module.clients.subtitle" to "Your client directory",
    "module.services" to "Jobs",
    "module.services.subtitle" to "Work done and to bill",
    "module.quotes" to "Quotes",
    "module.quotes.subtitle" to "What you have offered",
    "module.invoices" to "Invoices",
    "module.invoices.subtitle" to "What you are owed",
    "module.suppliers" to "Suppliers",
    "module.suppliers.subtitle" to "Who you buy from",
    "module.employees" to "Employees",
    "module.employees.subtitle" to "Your team",
    "module.payments" to "Payments",
    "module.payments.subtitle" to "What you owe",
    "module.catalog" to "Catalog",
    "module.catalog.subtitle" to "Your services and products",
    "module.bookings" to "Bookings",
    "module.bookings.subtitle" to "Your calendar",
    "module.persona" to "Persona",
    "module.persona.subtitle" to "How the assistant speaks",
    "module.ai-assistant" to "Assistant",
    "module.ai-assistant.subtitle" to "Get work done by asking",
    "module.agents" to "Agents",
    "module.agents.subtitle" to "Approvals and tasks",
    "module.settings" to "Settings",
    "module.settings.subtitle" to "Language, channels, account",

    "module.conversations.short" to "Inbox",
    "module.ai-assistant.short" to "Assistant",

    "status.ACTIVE" to "Active",
    "status.DISABLED" to "Disabled",
    "status.BLOCKED" to "Blocked",
    "status.OPEN" to "Open",
    "status.DONE" to "Done",
    "status.CANCELLED" to "Cancelled",
    "status.PENDING" to "Pending",
    "status.PENDENTE" to "Pending",
    "status.CONFIRMED" to "Confirmed",
    "status.COMPLETED" to "Completed",
    "status.NO_SHOW" to "No show",
    "status.SENT" to "Sent",
    "status.ENVIADO" to "Sent",
    "status.ACCEPTED" to "Accepted",
    "status.ACEITO" to "Accepted",
    "status.REJECTED" to "Rejected",
    "status.RECUSADO" to "Rejected",
    "status.PAID" to "Paid",
    "status.PAGA" to "Paid",
    "status.UNPAID" to "Unpaid",
    "status.OVERDUE" to "Overdue",
    "status.INVOICED" to "Invoiced",
    "status.DRAFT" to "Draft",
    "status.PAUSED" to "Paused",
    "status.ARCHIVED" to "Archived",
    "status.FAILED" to "Failed",
    "status.DELIVERED" to "Delivered",
    "status.READ" to "Read",
    "status.QUEUED" to "Queued",
    "status.RUNNING" to "Running",
    "status.WAITING" to "Waiting",
    "status.SUCCEEDED" to "Succeeded",
    "status.COMPILING" to "Rebuilding",
    "status.READY" to "Ready",

    "attention.waiting_chat" to "Waiting for a reply",
    "attention.overdue_invoice" to "Invoice overdue",
    "attention.due_soon_invoice" to "Invoice due soon",
    "attention.overdue_payment" to "Payment overdue",
    "attention.due_soon_payment" to "Payment due soon",
    "attention.pending_booking" to "Booking to confirm",
    "attention.instagram_comment" to "Comment to answer",
    "attention.quote_expiring" to "Quote expiring",
    "attention.assistant_action" to "Action to confirm",
    "attention.agent_approval" to "Agent waiting for approval",
    "attention.agent_task_due" to "Task due",
    "attention.agent_failed" to "Agent run failed",
    "attention.integration_reconnect" to "Reconnect needed",

    "weekday.1" to "Monday",
    "weekday.2" to "Tuesday",
    "weekday.3" to "Wednesday",
    "weekday.4" to "Thursday",
    "weekday.5" to "Friday",
    "weekday.6" to "Saturday",
    "weekday.7" to "Sunday",
)
