package com.rfm.edubot.mobile.core.localization

/**
 * Every key the app looks up. Screens reference these constants rather than raw strings, so a
 * mistyped key is a compile error instead of blank space on a customer's phone.
 *
 * Names follow the web catalogs (`nav.`, `inbox.`, `crm.`): when a string exists on both, the key
 * should read the same on both.
 */
object Txt {
    // Shared actions and words.
    const val ACTION_SAVE = "action.save"
    const val ACTION_CANCEL = "action.cancel"
    const val ACTION_CONFIRM = "action.confirm"
    const val ACTION_RETRY = "action.retry"
    const val ACTION_REFRESH = "action.refresh"
    const val ACTION_BACK = "action.back"
    const val ACTION_CLOSE = "action.close"
    const val ACTION_NEW = "action.new"
    const val ACTION_SEND = "action.send"
    const val ACTION_SEARCH = "action.search"
    const val ACTION_SIGN_IN = "action.signIn"
    const val ACTION_SIGN_OUT = "action.signOut"
    const val ACTION_APPROVE = "action.approve"
    const val ACTION_REJECT = "action.reject"
    const val ACTION_DONE = "action.done"
    const val ACTION_REOPEN = "action.reopen"
    const val ACTION_PAUSE = "action.pause"
    const val ACTION_RESUME = "action.resume"
    const val ACTION_MARK_PAID = "action.markPaid"
    const val ACTION_MARK_ALL_READ = "action.markAllRead"
    const val ACTION_LOAD_MORE = "action.loadMore"

    const val LABEL_ALL = "label.all"
    const val LABEL_OPEN = "label.open"
    const val LABEL_TODAY = "label.today"
    const val LABEL_OPTIONAL = "label.optional"
    const val LABEL_REQUIRED = "label.required"
    const val LABEL_NONE = "label.none"
    const val LABEL_TOTAL = "label.total"
    const val LABEL_UNTITLED = "label.untitled"

    // Sign-in.
    const val LOGIN_TITLE = "login.title"
    const val LOGIN_DESCRIPTION = "login.description"
    const val LOGIN_EMAIL = "login.email"
    const val LOGIN_PASSWORD = "login.password"
    const val LOGIN_ERROR_MISSING = "login.error.missing"
    const val LOGIN_ERROR_INVALID = "login.error.invalid"
    const val LOGIN_ERROR_EXPIRED = "login.error.expired"
    const val LOGIN_ERROR_INACTIVE = "login.error.inactive"
    const val LOGIN_ERROR_CONNECTION = "login.error.connection"

    // Failures.
    const val ERROR_UNAUTHORIZED = "error.unauthorized"
    const val ERROR_FORBIDDEN = "error.forbidden"
    const val ERROR_NOT_FOUND = "error.notFound"
    const val ERROR_OFFLINE = "error.offline"
    const val ERROR_SERVER = "error.server"
    const val ERROR_REJECTED = "error.rejected"

    // Offline and empty states.
    const val OFFLINE_SNAPSHOT = "offline.snapshot"
    const val OFFLINE_SNAPSHOT_DETAIL = "offline.snapshotDetail"
    const val EMPTY_TITLE = "empty.title"

    // Navigation chrome.
    const val NAV_MORE = "nav.more"
    const val NAV_GROUP_INBOX = "nav.group.inbox"
    const val NAV_GROUP_BUSINESS = "nav.group.business"
    const val NAV_GROUP_AUTOMATION = "nav.group.automation"
    const val NAV_GROUP_SETUP = "nav.group.setup"
    const val NAV_WEB_ONLY = "nav.webOnly"
    const val NAV_WEB_ONLY_DETAIL = "nav.webOnlyDetail"

    // Home.
    const val OVERVIEW_SNAPSHOT = "overview.snapshot"
    const val OVERVIEW_NEEDS_YOU = "overview.needsYou"
    const val OVERVIEW_NEEDS_YOU_EMPTY = "overview.needsYouEmpty"
    const val OVERVIEW_AGENDA = "overview.agenda"
    const val OVERVIEW_MESSAGES_TODAY = "overview.messagesToday"
    const val OVERVIEW_WAITING = "overview.waiting"
    const val OVERVIEW_CONTACTS = "overview.contacts"
    const val OVERVIEW_CONVERSATIONS = "overview.conversations"
    const val OVERVIEW_COLLECTED_MONTH = "overview.collectedMonth"
    const val OVERVIEW_OUTSTANDING = "overview.outstanding"
    const val OVERVIEW_OVERDUE = "overview.overdue"
    const val OVERVIEW_PIPELINE_OPEN = "overview.pipelineOpen"
    const val OVERVIEW_BOOKINGS_TODAY = "overview.bookingsToday"
    const val OVERVIEW_BOOKINGS_PENDING = "overview.bookingsPending"
    const val OVERVIEW_APPROVALS = "overview.approvals"
    const val OVERVIEW_TASKS = "overview.tasks"
    const val OVERVIEW_GENERATED_AT = "overview.generatedAt"

    // Inbox.
    const val INBOX_TITLE = "inbox.title"
    const val INBOX_FILTER_NEEDS_REPLY = "inbox.filter.needsReply"
    const val INBOX_FILTER_UNREAD = "inbox.filter.unread"
    const val INBOX_FILTER_PAUSED = "inbox.filter.paused"
    const val INBOX_EMPTY = "inbox.empty"
    const val INBOX_MESSAGE_PLACEHOLDER = "inbox.messagePlaceholder"
    const val INBOX_AUTO_REPLY_ON = "inbox.autoReplyOn"
    const val INBOX_AUTO_REPLY_OFF = "inbox.autoReplyOff"
    const val INBOX_WINDOW_CLOSED = "inbox.windowClosed"
    const val INBOX_SEND_FAILED = "inbox.sendFailed"
    const val INBOX_ATTACHMENT = "inbox.attachment"
    const val INBOX_WRITTEN_BY_AGENT = "inbox.writtenByAgent"
    const val INBOX_WEB_REPLY_UNAVAILABLE = "inbox.webReplyUnavailable"
    const val INBOX_MESSAGES_COUNT = "inbox.messagesCount"

    // Contacts.
    const val CONTACTS_TITLE = "contacts.title"
    const val CONTACTS_EMPTY = "contacts.empty"
    const val CONTACTS_BLOCK = "contacts.block"
    const val CONTACTS_UNBLOCK = "contacts.unblock"
    const val CONTACTS_LAST_SEEN = "contacts.lastSeen"

    // CRM.
    const val CRM_CLIENTS_TITLE = "crm.clients.title"
    const val CRM_CLIENTS_EMPTY = "crm.clients.empty"
    const val CRM_CLIENT_NAME = "crm.client.name"
    const val CRM_CLIENT_PHONE = "crm.client.phone"
    const val CRM_CLIENT_TAX_ID = "crm.client.taxId"
    const val CRM_CLIENT_TAX_ID_HINT = "crm.client.taxIdHint"
    const val CRM_CLIENT_ADDRESS = "crm.client.address"
    const val CRM_CLIENT_EMAIL = "crm.client.email"
    const val CRM_CLIENT_CITY = "crm.client.city"
    const val CRM_CLIENT_POSTAL_CODE = "crm.client.postalCode"
    const val CRM_CLIENT_CREATE = "crm.client.create"
    const val CRM_QUOTES_TITLE = "crm.quotes.title"
    const val CRM_QUOTES_EMPTY = "crm.quotes.empty"
    const val CRM_QUOTE_CONVERT = "crm.quote.convert"
    const val CRM_QUOTE_VALID_UNTIL = "crm.quote.validUntil"
    const val CRM_INVOICES_TITLE = "crm.invoices.title"
    const val CRM_INVOICES_EMPTY = "crm.invoices.empty"
    const val CRM_INVOICE_DUE_DATE = "crm.invoice.dueDate"
    const val CRM_INVOICE_OVERDUE = "crm.invoice.overdue"
    const val CRM_CATALOG_TITLE = "crm.catalog.title"
    const val CRM_CATALOG_EMPTY = "crm.catalog.empty"
    const val CRM_CATALOG_ITEM_TITLE = "crm.catalog.itemTitle"
    const val CRM_CATALOG_ITEM_CODE = "crm.catalog.itemCode"
    const val CRM_CATALOG_CATEGORY = "crm.catalog.category"
    const val CRM_CATALOG_UNIT = "crm.catalog.unit"
    const val CRM_CATALOG_PRICE = "crm.catalog.price"
    const val CRM_CATALOG_TYPE_SERVICE = "crm.catalog.typeService"
    const val CRM_CATALOG_TYPE_PRODUCT = "crm.catalog.typeProduct"
    const val CRM_SERVICES_TITLE = "crm.services.title"
    const val CRM_SERVICES_EMPTY = "crm.services.empty"
    const val CRM_SERVICES_INVOICE_SELECTED = "crm.services.invoiceSelected"
    const val CRM_PAYMENTS_TITLE = "crm.payments.title"
    const val CRM_PAYMENTS_EMPTY = "crm.payments.empty"
    const val CRM_SUPPLIERS_TITLE = "crm.suppliers.title"
    const val CRM_SUPPLIERS_EMPTY = "crm.suppliers.empty"
    const val CRM_EMPLOYEES_TITLE = "crm.employees.title"
    const val CRM_EMPLOYEES_EMPTY = "crm.employees.empty"
    const val CRM_LINE_DESCRIPTION = "crm.line.description"
    const val CRM_LINE_QUANTITY = "crm.line.quantity"
    const val CRM_LINE_UNIT_PRICE = "crm.line.unitPrice"
    const val CRM_LINE_ADD = "crm.line.add"
    const val CRM_PICK_CLIENT = "crm.pickClient"
    const val CRM_DATE_FORMAT_HINT = "crm.dateFormatHint"

    // Bookings.
    const val BOOKINGS_TITLE = "bookings.title"
    const val BOOKINGS_EMPTY = "bookings.empty"
    const val BOOKINGS_UPCOMING = "bookings.upcoming"
    const val BOOKINGS_NEEDS_CONFIRM = "bookings.needsConfirm"
    const val BOOKINGS_BILLABLE = "bookings.billable"
    const val BOOKINGS_OPENING_HOURS = "bookings.openingHours"
    const val BOOKINGS_CLOSED = "bookings.closed"
    const val BOOKINGS_SERVICE = "bookings.service"

    // Agents.
    const val AGENTS_TITLE = "agents.title"
    const val AGENTS_TAB_INBOX = "agents.tab.inbox"
    const val AGENTS_TAB_AGENTS = "agents.tab.agents"
    const val AGENTS_TAB_ACTIVITY = "agents.tab.activity"
    const val AGENTS_APPROVALS = "agents.approvals"
    const val AGENTS_APPROVALS_EMPTY = "agents.approvalsEmpty"
    const val AGENTS_TASKS = "agents.tasks"
    const val AGENTS_TASKS_EMPTY = "agents.tasksEmpty"
    const val AGENTS_EMPTY = "agents.empty"
    const val AGENTS_PAUSED_BY_PLATFORM = "agents.pausedByPlatform"
    const val AGENTS_PAUSED_COMPANY = "agents.pausedCompany"
    const val AGENTS_CANNOT_DECIDE = "agents.cannotDecide"
    const val AGENTS_EXPIRES = "agents.expires"
    const val AGENTS_EXPIRES_TODAY = "agents.expiresToday"
    const val AGENTS_REJECT_REASON = "agents.rejectReason"
    const val AGENTS_RUNS_TODAY = "agents.runsToday"
    const val AGENTS_ACTIVE = "agents.active"
    const val AGENTS_FAILED_WEEK = "agents.failedWeek"
    const val AGENTS_ACTIVITY_EMPTY = "agents.activityEmpty"
    const val AGENTS_DUE = "agents.due"
    const val AGENTS_BUILDER_WEB_ONLY = "agents.builderWebOnly"

    // Notifications.
    const val NOTIFICATIONS_TITLE = "notifications.title"
    const val NOTIFICATIONS_EMPTY = "notifications.empty"
    const val NOTIFICATIONS_GENERIC = "notifications.generic"
    const val NOTIFICATIONS_UNREAD = "notifications.unread"

    // Assistant.
    const val ASSISTANT_TITLE = "assistant.title"
    const val ASSISTANT_EMPTY = "assistant.empty"
    const val ASSISTANT_START_THREAD = "assistant.startThread"
    const val ASSISTANT_NEW_THREAD = "assistant.newThread"
    const val ASSISTANT_PROMPT_PLACEHOLDER = "assistant.promptPlaceholder"
    const val ASSISTANT_ACTION_PENDING = "assistant.actionPending"
    const val ASSISTANT_THREADS = "assistant.threads"

    // Persona.
    const val PERSONA_TITLE = "persona.title"
    const val PERSONA_INSTRUCTIONS = "persona.instructions"
    const val PERSONA_VERSION = "persona.version"
    const val PERSONA_TOKENS = "persona.tokens"
    const val PERSONA_COMPILING = "persona.compiling"
    const val PERSONA_REBUILD = "persona.rebuild"
    const val PERSONA_SOURCES = "persona.sources"
    const val PERSONA_SOURCES_EMPTY = "persona.sourcesEmpty"
    const val PERSONA_ADD_NOTE = "persona.addNote"
    const val PERSONA_NOTE_PLACEHOLDER = "persona.notePlaceholder"
    const val PERSONA_TEST = "persona.test"
    const val PERSONA_TEST_PLACEHOLDER = "persona.testPlaceholder"
    const val PERSONA_SOURCE_PENDING = "persona.sourcePending"
    const val PERSONA_FILE_WEB_ONLY = "persona.fileWebOnly"

    // Settings.
    const val SETTINGS_TITLE = "settings.title"
    const val SETTINGS_CHANNELS = "settings.channels"
    const val SETTINGS_CHANNELS_EMPTY = "settings.channelsEmpty"
    const val SETTINGS_LANGUAGE = "settings.language"
    const val SETTINGS_APPEARANCE = "settings.appearance"
    const val SETTINGS_THEME_LIGHT = "settings.theme.light"
    const val SETTINGS_THEME_DARK = "settings.theme.dark"
    const val SETTINGS_THEME_SYSTEM = "settings.theme.system"
    const val SETTINGS_ACCOUNT = "settings.account"
    const val SETTINGS_COMPANIES = "settings.companies"
    const val SETTINGS_COMPANY_SWITCH = "settings.companySwitch"
    const val SETTINGS_WIDGET = "settings.widget"
    const val SETTINGS_WIDGET_KEY = "settings.widgetKey"
    const val SETTINGS_OPERATOR_SESSION = "settings.operatorSession"
    const val SETTINGS_WEB_FOR_MORE = "settings.webForMore"

    // Voice input.
    const val VOICE_START = "voice.start"
    const val VOICE_STOP = "voice.stop"
    const val VOICE_LISTENING = "voice.listening"
    const val VOICE_PERMISSION_DENIED = "voice.permissionDenied"
    const val VOICE_UNAVAILABLE = "voice.unavailable"
    const val VOICE_FAILED = "voice.failed"
}
