/* English UI catalog. Registered into window.__I18N_CATALOGS['en'].
   Namespaces: common (shared), app (tenant dashboard), admin (CRM), backoffice (super-admin). */
window.__I18N_CATALOGS = window.__I18N_CATALOGS || {};
window.__I18N_CATALOGS['en'] = {
  common: {
    nav: {
      overview: 'Overview', conversations: 'Conversations', contacts: 'Contacts',
      clients: 'Clients', quotes: 'Quotes', invoices: 'Invoices', catalog: 'Catalog',
      persona: 'Persona', settings: 'Settings', 'ai-assistant': 'AI Assistant', bookings: 'Bookings',
    },
    lang: {
      title: 'Language', desc: 'Language used across this dashboard.', label: 'Language',
      saved: 'Language updated ✓', saveFailed: 'Could not update language',
    },
    menuOpenAria: 'Open menu',
    menuCloseAria: 'Close menu',
  },

  app: {
    settingsDesc: 'Connected channels and bot configuration.',
    channelsTitle: 'Channels',
    channelsDesc: 'Accounts where the assistant replies to your customers.',
    colChannel: 'Channel', colAccount: 'Account', colStatus: 'Status', colActions: 'Actions',
    connected: 'Connected', notConnected: 'Not connected',
    igConnect: 'Connect Instagram', igReconnect: 'Reconnect Instagram',
    waConnect: 'Connect WhatsApp', waReconnect: 'Reconnect WhatsApp',
    channelsHint: 'WhatsApp and Instagram open a Meta window to authorize your business account. Instagram must be Business or Creator.',
    igHint: 'Connecting Instagram opens a Meta window to authorize your professional account. The account must be Business or Creator.',
    moreSettingsTitle: 'More settings coming soon',
    moreSettingsDesc: 'Team members are managed in the backoffice for now.',
    docTemplateTitle: 'Quote & invoice template',
    docTemplateDesc: 'Branding and default text used when generating quote and invoice PDFs.',
    docCompanyName: 'Company name', docTagline: 'Tagline', docTaglinePh: 'e.g. Construction & management',
    docTaxId: 'Tax ID', docTaxIdPh: 'NIF / VAT', docEmail: 'Email', docPhone: 'Phone', docAddress: 'Address',
    docQuoteTitle: 'Quote document title', docInvoiceTitle: 'Invoice document title',
    docQuotePayment: 'Default payment terms (quotes)', docInvoicePayment: 'Default payment terms (invoices)',
    docTerms: 'Terms & conditions', docFooter: 'Footer',
    docLogo: 'Logo', docLogoNone: 'No logo uploaded', docLogoLoading: 'Loading logo…',
    docLogoUpload: 'Upload logo', docLogoRemove: 'Remove logo',
    docLogoHint: 'PNG, JPG or WebP, max 2 MB. Shown on quote and invoice PDFs.',
    docLogoUploaded: 'Logo uploaded', docLogoRemoved: 'Logo removed', docLogoUploadFailed: 'Could not update logo',
    docTemplateSave: 'Save template', docTemplateSaved: 'Document template saved',
    docTemplateSaveFailed: 'Could not save document template',
    sessionExpired: 'Session expired',
    igUnavailable: 'Instagram connection is not available',
    igAllowPopups: 'Allow popups to connect Instagram',
    igConnected: 'Instagram connected ✓',
    igFailed: reason => `Could not connect Instagram${reason ? ` (${reason})` : ''}`,
    waNotConfigured: 'WhatsApp connection is not available',
    waOpenPopup: 'Open the Meta popup to connect WhatsApp',
    waConnected: 'WhatsApp connected ✓',
    waCancelled: 'WhatsApp connection cancelled',
    waMissingCode: 'Meta did not return the authorization code',
    waTimeout: 'Timed out waiting for WhatsApp signup',
    waSdkFailed: 'Could not load the Facebook SDK',
    waFailed: p => `Could not connect WhatsApp${p?.msg ? ` (${p.msg})` : ''}`,
    webTitle: 'Website widget',
    webDesc: 'Add the chat assistant to your website. Paste this snippet just before the closing </body> tag.',
    webGenerate: 'Generate widget code',
    webRegenerate: 'Widget active',
    webCopy: 'Copy snippet',
    webCopied: 'Snippet copied ✓',
    webGenerated: 'Widget code generated ✓',
    webGenerateFailed: 'Could not generate widget code',
    webOriginsLabel: 'Allowed website domains (optional)',
    webOriginsHint: 'One origin per line, e.g. https://www.yoursite.com. Leave empty to allow any site (less secure).',
    webOriginsSave: 'Save domains',
    webOriginsSaved: 'Domains saved ✓',
    webRowName: 'Website',
    quickCreateSoon: 'Quick create for this module is coming soon.',
    clientFormTitle: 'New client',
    clientFormName: 'Name', clientFormPhone: 'Phone', clientFormAddress: 'Address',
    clientPhName: 'Client name', clientPhPhone: '+351…', clientPhAddress: 'Street, city',
    clientSave: 'Create client',
    clientValidate: 'Enter name and phone',
    clientCreated: p => `Client created · ${p.name}`,
    clientCreateFailed: 'Could not create client',
    optional: 'optional',
    catalogFormTitle: 'New item', catalogSave: 'Create item',
    catalogId: 'ID', catalogType: 'Type', catalogService: 'Service', catalogMaterial: 'Material',
    catalogCategory: 'Category', catalogDesc: 'Description', catalogUnit: 'Unit', catalogPrice: 'Price (€)',
    catalogPhId: 'srv-…', catalogPhCategory: 'E.g. Facades', catalogPhDesc: 'What this item covers', catalogPhUnit: 'm2, unit, service…',
    catalogValidate: 'Fill all required fields', catalogCreated: p => `Item created · ${p.id}`, catalogCreateFailed: 'Could not create item',
    quoteFormTitle: 'New quote', quoteSave: 'Create quote',
    quoteValidUntil: 'Valid until', quoteNotes: 'Notes', quoteNotesPh: 'Optional notes shown on the PDF',
    quoteChooseClient: 'Choose a client', quoteAddLine: 'Add at least one line', quoteCreated: 'Quote created', quoteCreateFailed: 'Could not create quote',
    invoiceFormTitle: 'New invoice', invoiceSave: 'Issue invoice',
    invoiceDueDate: 'Due date', invoiceQuoteId: 'Quote ID', invoiceQuoteIdPh: 'Link an existing quote (optional)',
    invoiceChooseClient: 'Choose a client', invoiceEnterDueDate: 'Enter a due date', invoiceAddLine: 'Add at least one line', invoiceCreated: 'Invoice issued', invoiceCreateFailed: 'Could not issue invoice',
    lineClient: 'Client', lineChooseClient: 'Select…', lineItemsLabel: 'Items',
    lineColDesc: 'Description', lineColQty: 'Qty', lineColUnit: 'Unit', lineColPrice: 'Price',
    lineAddEmpty: 'Add line', lineCatalogPick: 'From catalog…', lineAdd: 'Add', lineTotal: 'Total',
    lineDescPh: 'Description', lineUnitPh: 'un', lineRemove: 'Remove line', lineChooseCatalog: 'Pick a catalog item',
    loginEyebrow: 'thebots.lab / tenant',
    loginTitle: 'Sign in to the dashboard',
    loginDesc: 'Access your chatbot data, conversations and CRM.',
    loginEmail: 'Email', loginPassword: 'Password', loginSubmit: 'Sign in', loginInvalid: 'Invalid login',
    newPrefix: 'New',
    dashboardWord: 'Dashboard', searchPlaceholder: 'Search…', logout: 'Log out', themeAria: 'Toggle theme',
    noData: 'No data',
    overviewDesc: 'Chatbot status and recent activity.',
    statMessages24h: 'Messages 24h', statMessages: 'Messages', statContacts: 'Contacts', statConversations: 'Conversations', statQuotes: 'Quotes', statInvoices: 'Invoices',
    contactsDesc: 'End-users who talked to the bot.',
    thName: 'Name', thStatus: 'Status', thLastSeen: 'Last seen', thActions: 'Actions',
    block: 'Block', unblock: 'Unblock',
    conversationsDesc: 'Open a customer conversation and send a live message from a connected account.',
    thState: 'State', thMsgs: 'Msgs', thLast: 'Last',
    threadTitle: 'Conversation', noMessages: 'No messages',
    assetLabel: 'Connected asset', assetHint: 'Select the Page, account, or number used to message customers.',
    unnamedAsset: 'Unnamed account', recipient: 'Recipient', noAssetConversations: 'No conversations for this asset', noMessagingAssets: 'Connect Instagram or WhatsApp to send messages',
    sendingFrom: 'Sending from', sendingTo: 'To', customer: 'Customer', operator: 'Operator',
    messagePlaceholder: 'Write a live message…', sendUnavailable: 'Select the asset that owns this conversation to send a message.',
    messageDelivered: 'Message delivered', messageFailed: 'Message could not be delivered',
    openChat: 'Open chat',
    clientsDesc: 'CRM · Clients.', thPhone: 'Phone', thAddress: 'Address', thNo: 'No.',
    quotesDesc: 'CRM · Commercial proposals.', thNumber: 'Number', thClient: 'Client', thTotal: 'Total',
    invoicesDesc: 'CRM · Issued invoices.', thDueDate: 'Due date',
    thPdf: 'PDF', thPdfActions: 'PDF · Actions', viewPdf: 'View PDF', pdfPending: 'pending',
    errorPdf: p => `PDF error: ${p.msg}`, loadFailed: 'Could not load this section',
    markPaid: 'Mark paid', markedPaid: p => `Invoice ${p.number} marked as paid`, markPaidFailed: 'Could not mark invoice as paid',
    catalogDesc: 'CRM · Standard services and materials.', thType: 'Type', thCategory: 'Category', thDescription: 'Description', thUnit: 'Unit', thPrice: 'Price',
    personaDesc: 'Bot personality — synthesized from notes and files you upload.',
    personaCompiling: 'Synthesizing…', statVersion: 'Version', statTokens: 'Tokens est.', statUpdated: 'Updated',
    testBotTitle: 'Test the bot', clear: 'Clear',
    testBotDesc: 'Chat with the bot using the current persona to test tone and replies. Test messages are not saved and do not create clients, quotes or invoices.',
    chatPlaceholder: 'Type a test message…', send: 'Send',
    chatEmpty: 'Send a message to test the bot persona.', typing: 'typing…', chatError: '⚠️ Error contacting the bot. Please try again.',
    addInfoTitle: 'Add information',
    addInfoDesc: 'Write a note or upload a file (PDF, TXT, MD). It is synthesized into the instructions file below.',
    noteLabel: 'Note', notePlaceholder: 'E.g.: We are a dental clinic in Lisbon. Warm tone, formal address...', addNote: 'Add note',
    fileLabel: 'File', fileHint: 'PDF, TXT or Markdown. The text is extracted and synthesized.',
    sourcesTitle: 'Sources', sourcesDesc: 'Raw material feeding the synthesis.', rebuildAll: 'Recompile all',
    sourceSynced: 'synced', sourcePending: 'pending', remove: 'Remove',
    thSource: 'Source', thCreated: 'Created',
    noSourcesTitle: 'No sources yet', noSourcesDesc: 'Add a note or file above.',
    compiledTitle: 'Compiled instructions file',
    compiledDesc: 'Synthesis result. You can edit it manually; the next synthesis will review it.',
    compiledPlaceholder: 'Still empty — add information above to give the bot personality.',
    saveManual: 'Save manual edit',
    personaSaved: 'Persona saved', noteAdded: 'Note added — synthesizing', fileUploaded: 'File uploaded — synthesizing', rebuildStarted: 'Recompilation started', uploadFailed: 'Upload failed',
    assistantDesc: 'Ask questions about your business data and complete dashboard tasks with your approval.',
    assistantNewThread: 'New conversation', assistantNoThreads: 'No conversations yet',
    assistantEmpty: 'Start by asking about clients, catalog items, quotes, or invoices.', assistantPlaceholder: 'Ask the assistant…',
    assistantError: 'The assistant could not answer. Please try again.', assistantActionError: 'The action could not be updated.',
    assistantProposedAction: 'Proposed action', assistantConfirm: 'Confirm action', assistantCancel: 'Cancel',
    assistantStatusPENDING: 'Awaiting approval', assistantStatusEXECUTING: 'Running', assistantStatusCONFIRMED: 'Completed', assistantStatusFAILED: 'Failed', assistantStatusCANCELLED: 'Cancelled',
    assistantCreateClient: p => `Create client ${p.name}`, assistantCreateQuote: 'Create quote', assistantUpdateQuote: p => `Update quote ${p.id}`,
    assistantCreateInvoice: 'Create invoice', assistantMarkPaid: p => `Mark invoice ${p.id} as paid`, assistantChangeData: 'Change dashboard data',
    assistantClientRef: p => `Client: ${p.id}`, assistantQuoteRef: p => `Quote: ${p.id}`, assistantInvoiceRef: p => `Invoice: ${p.id}`,
    assistantValidUntil: p => `Valid until: ${p.date}`, assistantDueDate: p => `Due date: ${p.date}`, assistantNewStatus: p => `New status: ${p.status}`,
    bookingsDesc: 'Appointments, services and weekly availability.',
    bookingsWeek: 'Week', bookingsList: 'List', bookingsServices: 'Services', bookingsAvailability: 'Availability',
    bookingsPrev: 'Previous week', bookingsNext: 'Next week', bookingsToday: 'This week',
    bookingsNew: 'New booking', bookingsEdit: 'Edit booking', bookingsSave: 'Save booking',
    bookingsContactName: 'Contact name', bookingsContactPhone: 'Phone', bookingsService: 'Service',
    bookingsStart: 'Start', bookingsNotes: 'Notes', bookingsStatus: 'Status', bookingsSource: 'Source',
    bookingsChooseService: '— Choose service —', bookingsCreated: 'Booking created', bookingsUpdated: 'Booking updated',
    bookingsConflict: 'That time overlaps another booking', bookingsValidate: 'Fill name, phone, service and start time',
    bookingsManageServices: 'Manage services', bookingsManageAvailability: 'Weekly hours',
    bookingsServiceName: 'Service name', bookingsDuration: 'Duration (minutes)', bookingsActive: 'Active',
    bookingsServiceSaved: 'Service saved', bookingsAvailabilitySaved: 'Availability saved',
    bookingsAddWindow: 'Add window', bookingsDay: 'Day', bookingsFrom: 'From', bookingsTo: 'To',
    bookingsEmptyWeek: 'No bookings this week', bookingsEmptyList: 'No bookings found',
    bookingsThWhen: 'When', bookingsThContact: 'Contact', bookingsThService: 'Service', bookingsThStatus: 'Status',
    bookingStatusPENDING: 'Pending', bookingStatusCONFIRMED: 'Confirmed', bookingStatusCANCELLED: 'Cancelled', bookingStatusCOMPLETED: 'Completed',
    weekday1: 'Mon', weekday2: 'Tue', weekday3: 'Wed', weekday4: 'Thu', weekday5: 'Fri', weekday6: 'Sat', weekday7: 'Sun',
  },

  admin: {
    nav: { clientes: 'Clients', orcamentos: 'Quotes', faturas: 'Invoices', items: 'Standard items', bookings: 'Bookings' },
    crumbRoot: 'Panel',
    brandSub: 'Tenant · Management',
    searchPlaceholder: 'Search this view…',
    export: 'Export', exportTitle: 'Export CSV', exportSoon: 'Export · coming soon',
    backoffice: '← Backoffice', themeAria: 'Toggle theme', closeAria: 'Close',
    kpiReceivable: 'Receivable', kpiPaid: 'Paid this month',
    saving: 'Saving…', cancel: 'Cancel', save: 'Save', confirm: 'Confirm', delete: 'Delete',
    loading: 'Loading…', loadError: 'Load error',
    login: { eyebrow: p => `thebots.lab / ${p.tenant}`, title: 'Sign in to the CRM', desc: 'Use the operator password to open this management panel.', password: 'Password', submit: 'Sign in', invalid: 'Invalid login', crumb: 'Login' },
    invalidTenantTitle: 'Invalid tenant', invalidTenantDesc: 'Go back to the backoffice and open a valid CRM.',
    titleSuffix: 'Management Panel',
    pdfPending: 'pending',
    errorPdf: p => `PDF error: ${p.msg}`,
    error: p => `Error: ${p.msg}`,
    quoteStatus: { PENDENTE: 'Pending', SENT: 'Sent', ACEITO: 'Accepted' },
    invoiceStatus: { PENDING: 'PENDING', PAID: 'PAID', OVERDUE: 'OVERDUE', CANCELLED: 'CANCELLED' },
    tabs: {
      clientes: { title: 'Clients', desc: 'Company client directory.', newLabel: 'New client' },
      orcamentos: { title: 'Quotes', desc: 'Issued commercial proposals.', newLabel: 'New quote' },
      faturas: { title: 'Invoices', desc: 'Issued invoices and their status.', newLabel: 'New invoice' },
      items: { title: 'Standard items', desc: 'Catalog of services and materials for quotes and invoices.', newLabel: 'New item' },
      bookings: { title: 'Bookings', desc: 'Appointments, services and weekly availability.', newLabel: 'New booking' },
    },
    clients: {
      total: 'Total', new30: 'New · 30d', directory: 'Directory',
      one: 'client', many: 'clients',
      thName: 'Name', thAddress: 'Address', thPhone: 'Phone', thCreated: 'Created', thNo: 'Client no.',
      emptyTitle: 'No clients found', emptyDesc: 'Adjust the search or create a new client.',
      formName: 'Name', formAddress: 'Address', formPhone: 'Phone',
      phName: 'E.g.: Manuel Costa, Ltd.', phAddress: 'E.g.: 12 Rua das Flores, 1200-001 Lisbon', phPhone: '+351 912 345 678',
      eyebrow: 'Clients', formTitle: 'New client', saveLabel: 'Create client',
      validate: 'Enter name and phone', created: p => `Client created · ${p.name}`,
    },
    quotes: {
      total: 'Total', sent: 'Sent', accepted: 'Accepted', proposals: 'Proposals', filterAll: 'All',
      thNumber: 'Number', thClient: 'Client', thStatus: 'Status', thValidUntil: 'Valid until', thTotal: 'Total', thPdf: 'PDF',
      emptyTitle: 'No quotes', emptyDesc: 'Create the first quote with the button above.',
      validUntil: 'Valid until', optional: 'optional', notes: 'Notes', notesPlaceholder: 'Internal notes, conditions, deadlines…',
      eyebrow: 'Quotes', formTitle: 'New quote', saveLabel: 'Create quote',
      chooseClient: 'Choose a client', addLine: 'Add at least one line', created: 'Quote created',
    },
    invoices: {
      paid: 'Paid', pending: 'Pending', overdue: 'Overdue', documents: 'Documents', filterAll: 'All',
      thNumber: 'Number', thClient: 'Client', thStatus: 'Status', thDueDate: 'Due date', thTotal: 'Total', thPdfActions: 'PDF · Actions',
      emptyTitle: 'No invoices', emptyDesc: 'Issue the first invoice with the button above.',
      markPaid: 'Mark paid', markedPaid: p => `Invoice ${p.number} marked as paid`,
      dueDate: 'Due date', quoteId: 'Quote ID', quoteIdPlaceholder: 'Associated quote ID',
      eyebrow: 'Invoices', formTitle: 'New invoice', saveLabel: 'Issue invoice',
      chooseClient: 'Choose a client', enterDueDate: 'Enter the due date', addLine: 'Add at least one line', issued: 'Invoice issued',
    },
    lines: {
      client: 'Client', chooseClient: '— Choose client —',
      services: 'Services', materials: 'Materials', label: 'Lines',
      colDescription: 'Description', colQty: 'Qty', colUnit: 'Unit', colPrice: 'Price €',
      addEmpty: '+ Empty line', catalogPick: 'Catalog · Services / Materials', add: 'Add', total: 'Total',
      descPlaceholder: 'Line description…', unitPlaceholder: 'un', removeLine: 'Remove line', chooseCatalogItem: 'Choose a catalog item',
    },
    items: {
      services: 'Services', materials: 'Materials', catalogTitle: 'Catalog', tag: p => `${p.n} items`,
      thType: 'Type', thCategory: 'Category', thDescription: 'Description', thUnit: 'Unit', thPrice: 'Price', thActions: 'Actions',
      emptyTitle: 'Empty catalog', emptyDesc: 'Add services or materials to reuse in quotes.',
      pillService: 'SERVICE', pillMaterial: 'MATERIAL', editTitle: 'Edit', deleteTitle: 'Delete',
      idLabel: 'ID · slug', typeLabel: 'Type', service: 'Service', material: 'Material',
      categoryLabel: 'Category', descLabel: 'Description', unitLabel: 'Unit', priceLabel: 'Price (EUR)',
      phId: 'e.g.: srv-interior-painting', phCategory: 'E.g.: Painting, Structural, Labour…', phDesc: 'Description shown on quotes', phUnit: 'm², h, un, rl…',
      editingHint: p => `Editing ${p.id} — changes apply to new quotes.`,
      eyebrow: 'Standard items', newTitle: 'New catalog item', editTitleFull: p => `Edit · ${p.id}`,
      saveChanges: 'Save changes', createItem: 'Create item',
      fillRequired: 'Fill all required fields', updated: p => `Item updated · ${p.id}`, created: p => `Item created · ${p.id}`,
      confirmTitle: 'Delete catalog item?', confirmBody: p => `"${p.desc}" will be removed. Already-issued quotes are not affected.`,
      confirmOk: 'Delete item', deleted: p => `Item deleted · ${p.id}`,
    },
  },

  backoffice: {
    login: { eyebrow: 'thebots.lab / platform', title: 'Backoffice', desc: 'Operator access to manage bots, tenants and teams.', password: 'Password', submit: 'Sign in', invalid: 'Invalid login' },
    cancel: 'Cancel', save: 'Save', confirm: 'Confirm', delete: 'Delete', loadError: 'Load error',
    error: p => `Error: ${p.msg}`,
    kpiActive: 'Active', kpiMessages: 'Messages', searchPlaceholder: 'Search tenant…', themeAria: 'Toggle theme',
    logout: 'Log out', crumbRoot: 'Platform', drawerEyebrow: 'Tenant', brandSub: 'Platform · Tenants', closeAria: 'Close',
    heroTitle: 'Tenants', heroDesc: 'Bots/clients configured on this platform.',
    botsTitle: 'Bots',
    thName: 'Name', thSlug: 'Slug', thChannels: 'Channels', thStatus: 'Status', thMsgs: 'Msgs', thLastActivity: 'Last activity', thActions: 'Actions',
    emptyTenants: 'No tenants found',
    openDashboard: 'Open Dashboard', users: 'Users', edit: 'Edit', suspend: 'Suspend', activate: 'Activate', reload: 'Reload',
    pipelineReloaded: 'Pipeline reloaded',
    noToken: 'no token', token: 'token',
    usersTitle: p => `Dashboard users · ${p.slug}`,
    thEmail: 'Email', thRole: 'Role',
    noUsers: 'No users', disable: 'Disable',
    emailLabel: 'Email', tempPassword: 'Temporary password', roleLabel: 'Role',
    createUser: 'Create user', emailPasswordRequired: 'Email and password required', userCreated: 'User created',
    userDisabled: 'User disabled', userActivated: 'User activated',
    tenantNameLabel: 'Name', tenantSlugLabel: 'Slug', languageLabel: 'Language',
    modelOverride: 'Model override', modelPlaceholder: 'blank = default',
    ratePerHour: 'Rate / hour', ratePerDay: 'Rate / day',
    modulesLabel: 'Modules', modulesHint: 'Core modules stay enabled. Select the optional modules this tenant can access.',
    channelsLabel: 'Channels', connectWhatsApp: 'Connect WhatsApp', connectInstagram: 'Connect Instagram', addChannel: '+ Add channel',
    colPlatform: 'Platform', colExternalId: 'External ID', colAccessToken: 'Access token',
    channelsHint: 'Instagram token is required when adding a channel. In edit, leave token blank to keep the existing one.',
    chExternalPlaceholder: 'phone_number_id or IG account id', chTokenUnchanged: 'unchanged', chTokenPlaceholder: 'access token', removeChannel: 'Remove channel',
    editTenant: p => `Edit · ${p.slug}`, newTenant: 'New bot/client', saveChanges: 'Save changes', createTenant: 'Create tenant',
    nameRequired: 'Name required', addOneChannel: 'Add at least one channel', igNeedsToken: 'Instagram needs a Page access token',
    tenantUpdated: 'Tenant updated', botCreated: 'Bot created. Link the channels to the Meta app and point the webhook.',
    suspendTitle: 'Suspend tenant?', activateTitle: 'Activate tenant?', tenantLine: p => `Tenant ${p.slug}`,
    deleteTitle: 'Delete tenant?', deleteBody: p => `${p.slug} will be marked DELETED. Existing data is not erased.`,
    igSessionExpired: 'Session expired', igNotConfigured: 'Instagram OAuth not configured (IG_APP_ID)',
    igAllowPopups: 'Allow popups to connect Instagram', igConnected: 'Instagram connected ✓', igFailed: p => `Instagram failed: ${p.reason || 'error'}`,
    waNotConfigured: 'WhatsApp Embedded Signup not configured', waOpenPopup: 'Open the Meta popup to connect WhatsApp', waConnected: 'WhatsApp connected',
    waCancelled: 'WhatsApp connection cancelled', waMissingCode: 'Meta did not return the authorization code',
    waTimeout: 'Timed out waiting for Embedded Signup', waSdkFailed: 'Could not load the Facebook SDK', waFailed: p => `WhatsApp failed: ${p.msg}`,
    platformSettings: {
      nav: 'Platform settings',
      title: 'Platform settings',
      desc: 'Runtime overrides stored in MongoDB. Secrets are masked; reveal on demand. Mongo URI and listen port stay in .env only.',
      save: 'Save overrides',
      reload: 'Reload from Mongo',
      saved: 'Settings saved',
      reloaded: 'Settings reloaded',
      reveal: 'Reveal',
      hide: 'Hide',
      clear: 'Clear override',
      secretBadge: 'secret',
      sourceEnv: 'from .env',
      sourceOverride: 'Mongo override',
      updatedAt: p => `Updated ${p.at}`,
      neverUpdated: 'No overrides saved yet',
      passwordHint: 'Enter a new plaintext password (hashed on save) or paste a bcrypt hash.',
      empty: 'No settings available',
      categories: {
        whatsapp: 'WhatsApp',
        instagram: 'Instagram',
        openrouter: 'OpenRouter',
        ratelimit: 'Rate limits',
        pdf: 'PDF storage',
        admin: 'Admin auth',
      },
    },
  },
};
