/* Portuguese (pt-PT) UI catalog. Registered into window.__I18N_CATALOGS['pt-PT']. */
window.__I18N_CATALOGS = window.__I18N_CATALOGS || {};
window.__I18N_CATALOGS['pt-PT'] = {
  common: {
    nav: {
      overview: 'Visão geral', conversations: 'Conversas', contacts: 'Contactos',
      clients: 'Clientes', quotes: 'Orçamentos', invoices: 'Faturas', catalog: 'Catálogo',
      persona: 'Persona', settings: 'Definições',
    },
    lang: {
      title: 'Idioma', desc: 'Idioma usado neste painel.', label: 'Idioma',
      saved: 'Idioma atualizado ✓', saveFailed: 'Não foi possível atualizar o idioma',
    },
  },

  app: {
    settingsDesc: 'Canais ligados e configuração do bot.',
    channelsTitle: 'Canais',
    channelsDesc: 'Contas onde o assistente responde aos seus clientes.',
    colChannel: 'Canal', colAccount: 'Conta', colStatus: 'Estado', colActions: 'Ações',
    connected: 'Ligado', notConnected: 'Não ligado',
    igConnect: 'Ligar Instagram', igReconnect: 'Religar Instagram',
    igHint: 'Ligar o Instagram abre uma janela Meta para autorizar a sua conta profissional. A conta tem de ser Business ou Creator.',
    moreSettingsTitle: 'Mais definições em breve',
    moreSettingsDesc: 'Os membros da equipa são geridos no backoffice por agora. Perfil de empresa / marca nos PDF ainda pendente.',
    sessionExpired: 'Sessão expirada',
    igUnavailable: 'A ligação ao Instagram não está disponível',
    igAllowPopups: 'Permita popups para ligar o Instagram',
    igConnected: 'Instagram ligado ✓',
    igFailed: reason => `Não foi possível ligar o Instagram${reason ? ` (${reason})` : ''}`,
    webTitle: 'Widget do site',
    webDesc: 'Adicione o assistente de chat ao seu site. Cole este snippet imediatamente antes da etiqueta </body>.',
    webGenerate: 'Gerar código do widget',
    webRegenerate: 'Widget ativo',
    webCopy: 'Copiar snippet',
    webCopied: 'Snippet copiado ✓',
    webGenerated: 'Código do widget gerado ✓',
    webGenerateFailed: 'Não foi possível gerar o código do widget',
    webOriginsLabel: 'Domínios de site permitidos (opcional)',
    webOriginsHint: 'Uma origem por linha, ex.: https://www.oseusite.com. Deixe vazio para permitir qualquer site (menos seguro).',
    webOriginsSave: 'Guardar domínios',
    webOriginsSaved: 'Domínios guardados ✓',
    webRowName: 'Site',
    quickCreateSoon: 'A criação rápida deste módulo está para breve.',
    loginEyebrow: 'thebots.lab / tenant',
    loginTitle: 'Entrar no painel',
    loginDesc: 'Aceda aos dados do chatbot, conversas e CRM.',
    loginEmail: 'Email', loginPassword: 'Password', loginSubmit: 'Entrar', loginInvalid: 'Login inválido',
    newPrefix: 'Novo',
    dashboardWord: 'Painel', searchPlaceholder: 'Procurar…', logout: 'Sair', themeAria: 'Mudar tema',
    noData: 'Sem dados',
    overviewDesc: 'Estado do chatbot e atividade recente.',
    statMessages24h: 'Mensagens 24h', statMessages: 'Mensagens', statContacts: 'Contactos', statConversations: 'Conversas', statQuotes: 'Orçamentos', statInvoices: 'Faturas',
    contactsDesc: 'Utilizadores finais que falaram com o bot.',
    thName: 'Nome', thStatus: 'Estado', thLastSeen: 'Visto', thActions: 'Ações',
    block: 'Bloquear', unblock: 'Desbloquear',
    conversationsDesc: 'Histórico de conversas (apenas leitura).',
    thState: 'Estado', thMsgs: 'Msgs', thLast: 'Última',
    threadTitle: 'Conversa', noMessages: 'Sem mensagens',
    clientsDesc: 'CRM · Clientes.', thPhone: 'Telefone', thAddress: 'Morada', thNo: 'Nº',
    quotesDesc: 'CRM · Propostas comerciais.', thNumber: 'Número', thClient: 'Cliente', thTotal: 'Total',
    invoicesDesc: 'CRM · Faturas emitidas.', thDueDate: 'Vencimento',
    catalogDesc: 'CRM · Serviços e materiais padrão.', thType: 'Tipo', thCategory: 'Categoria', thDescription: 'Descrição', thUnit: 'Unid.', thPrice: 'Preço',
    personaDesc: 'Personalidade do bot — sintetizada a partir das notas e ficheiros que carrega.',
    personaCompiling: 'A sintetizar…', statVersion: 'Versão', statTokens: 'Tokens est.', statUpdated: 'Atualizado',
    testBotTitle: 'Testar o bot', clear: 'Limpar',
    testBotDesc: 'Converse com o bot usando a persona atual para testar o tom e as respostas. As mensagens de teste não são guardadas e não criam clientes, orçamentos ou faturas.',
    chatPlaceholder: 'Escreva uma mensagem de teste…', send: 'Enviar',
    chatEmpty: 'Envie uma mensagem para testar a persona do bot.', typing: 'a escrever…', chatError: '⚠️ Erro ao contactar o bot. Tente novamente.',
    addInfoTitle: 'Adicionar informação',
    addInfoDesc: 'Escreva uma nota ou carregue um ficheiro (PDF, TXT, MD). É sintetizado no ficheiro de instruções abaixo.',
    noteLabel: 'Nota', notePlaceholder: 'Ex.: Somos uma clínica dentária em Lisboa. Tom acolhedor, tratamento formal...', addNote: 'Adicionar nota',
    fileLabel: 'Ficheiro', fileHint: 'PDF, TXT ou Markdown. O texto é extraído e sintetizado.',
    sourcesTitle: 'Fontes', sourcesDesc: 'Material em bruto que alimenta a síntese.', rebuildAll: 'Recompilar tudo',
    sourceSynced: 'sincronizado', sourcePending: 'pendente', remove: 'Remover',
    thSource: 'Fonte', thCreated: 'Criado',
    noSourcesTitle: 'Ainda sem fontes', noSourcesDesc: 'Adicione uma nota ou ficheiro acima.',
    compiledTitle: 'Ficheiro de instruções compilado',
    compiledDesc: 'Resultado da síntese. Pode editá-lo manualmente; a próxima síntese vai revê-lo.',
    compiledPlaceholder: 'Ainda vazio — adicione informação acima para dar personalidade ao bot.',
    saveManual: 'Guardar edição manual',
    personaSaved: 'Persona guardada', noteAdded: 'Nota adicionada — a sintetizar', fileUploaded: 'Ficheiro carregado — a sintetizar', rebuildStarted: 'Recompilação iniciada', uploadFailed: 'Falha no carregamento',
  },

  admin: {
    nav: { clientes: 'Clientes', orcamentos: 'Orçamentos', faturas: 'Faturas', items: 'Items Padrão' },
    crumbRoot: 'Painel',
    brandSub: 'Tenant · Gestão',
    searchPlaceholder: 'Procurar nesta vista…',
    export: 'Exportar', exportTitle: 'Exportar CSV', exportSoon: 'Exportar · em breve',
    backoffice: '← Backoffice', themeAria: 'Mudar tema', closeAria: 'Fechar',
    kpiReceivable: 'A receber', kpiPaid: 'Pago este mês',
    saving: 'A guardar…', cancel: 'Cancelar', save: 'Guardar', confirm: 'Confirmar', delete: 'Eliminar',
    loading: 'A carregar…', loadError: 'Erro ao carregar',
    login: { eyebrow: p => `thebots.lab / ${p.tenant}`, title: 'Entrar no CRM', desc: 'Use a password de operador para abrir este painel de gestão.', password: 'Password', submit: 'Entrar', invalid: 'Login inválido', crumb: 'Login' },
    invalidTenantTitle: 'Tenant inválido', invalidTenantDesc: 'Volte ao backoffice e abra um CRM válido.',
    titleSuffix: 'Painel de Gestão',
    pdfPending: 'pendente',
    errorPdf: p => `Erro PDF: ${p.msg}`,
    error: p => `Erro: ${p.msg}`,
    quoteStatus: { PENDENTE: 'Pendente', ACEITO: 'Aceito' },
    invoiceStatus: { PENDING: 'PENDENTE', PAID: 'PAGA', OVERDUE: 'VENCIDA', CANCELLED: 'CANCELADA' },
    tabs: {
      clientes: { title: 'Clientes', desc: 'Diretório de clientes da empresa.', newLabel: 'Novo cliente' },
      orcamentos: { title: 'Orçamentos', desc: 'Propostas comerciais emitidas.', newLabel: 'Novo orçamento' },
      faturas: { title: 'Faturas', desc: 'Faturas emitidas e respetivo estado.', newLabel: 'Nova fatura' },
      items: { title: 'Items Padrão', desc: 'Catálogo de serviços e materiais para orçamentos e faturas.', newLabel: 'Novo item' },
    },
    clients: {
      total: 'Total', new30: 'Novos · 30d', directory: 'Diretório',
      one: 'cliente', many: 'clientes',
      thName: 'Nome', thAddress: 'Morada', thPhone: 'Telefone', thCreated: 'Criado em', thNo: 'Nº Cliente',
      emptyTitle: 'Nenhum cliente encontrado', emptyDesc: 'Ajuste a pesquisa ou crie um novo cliente.',
      formName: 'Nome', formAddress: 'Morada', formPhone: 'Telefone',
      phName: 'Ex: Manuel Costa, Lda.', phAddress: 'Ex: Rua das Flores 12, 1200-001 Lisboa', phPhone: '+351 912 345 678',
      eyebrow: 'Clientes', formTitle: 'Novo cliente', saveLabel: 'Criar cliente',
      validate: 'Preencha nome e telefone', created: p => `Cliente criado · ${p.name}`,
    },
    quotes: {
      total: 'Total', sent: 'Enviados', accepted: 'Aceites', proposals: 'Propostas', filterAll: 'Todos',
      thNumber: 'Número', thClient: 'Cliente', thStatus: 'Status', thValidUntil: 'Válido até', thTotal: 'Total', thPdf: 'PDF',
      emptyTitle: 'Sem orçamentos', emptyDesc: 'Crie o primeiro orçamento com o botão acima.',
      validUntil: 'Válido até', optional: 'opcional', notes: 'Notas', notesPlaceholder: 'Notas internas, condições, prazos…',
      eyebrow: 'Orçamentos', formTitle: 'Novo orçamento', saveLabel: 'Criar orçamento',
      chooseClient: 'Escolha um cliente', addLine: 'Adicione pelo menos uma linha', created: 'Orçamento criado',
    },
    invoices: {
      paid: 'Pago', pending: 'Pendente', overdue: 'Vencido', documents: 'Documentos', filterAll: 'Todos',
      thNumber: 'Número', thClient: 'Cliente', thStatus: 'Status', thDueDate: 'Vencimento', thTotal: 'Total', thPdfActions: 'PDF · Acções',
      emptyTitle: 'Sem faturas', emptyDesc: 'Emita a primeira fatura com o botão acima.',
      markPaid: 'Marcar pago', markedPaid: p => `Fatura ${p.number} marcada como paga`,
      dueDate: 'Vencimento', quoteId: 'ID Orçamento', quoteIdPlaceholder: 'ID do orçamento associado',
      eyebrow: 'Faturas', formTitle: 'Nova fatura', saveLabel: 'Emitir fatura',
      chooseClient: 'Escolha um cliente', enterDueDate: 'Indique a data de vencimento', addLine: 'Adicione pelo menos uma linha', issued: 'Fatura emitida',
    },
    lines: {
      client: 'Cliente', chooseClient: '— Escolher cliente —',
      services: 'Serviços', materials: 'Materiais', label: 'Linhas',
      colDescription: 'Descrição', colQty: 'Qtd', colUnit: 'Unid.', colPrice: 'Preço €',
      addEmpty: '+ Linha vazia', catalogPick: 'Catálogo · Serviços / Materiais', add: 'Adicionar', total: 'Total',
      descPlaceholder: 'Descrição da linha…', unitPlaceholder: 'un', removeLine: 'Remover linha', chooseCatalogItem: 'Escolha um item do catálogo',
    },
    items: {
      services: 'Serviços', materials: 'Materiais', catalogTitle: 'Catálogo', tag: p => `${p.n} itens`,
      thType: 'Tipo', thCategory: 'Categoria', thDescription: 'Descrição', thUnit: 'Unid.', thPrice: 'Preço', thActions: 'Acções',
      emptyTitle: 'Catálogo vazio', emptyDesc: 'Adicione serviços ou materiais para reutilizar em orçamentos.',
      pillService: 'SERVIÇO', pillMaterial: 'MATERIAL', editTitle: 'Editar', deleteTitle: 'Eliminar',
      idLabel: 'ID · slug', typeLabel: 'Tipo', service: 'Serviço', material: 'Material',
      categoryLabel: 'Categoria', descLabel: 'Descrição', unitLabel: 'Unidade', priceLabel: 'Preço (EUR)',
      phId: 'ex: srv-pintura-interior', phCategory: 'Ex: Pintura, Estruturais, Mão-de-obra…', phDesc: 'Descrição visível em orçamentos', phUnit: 'm², h, un, rl…',
      editingHint: p => `A editar ${p.id} — alterações aplicam-se a novos orçamentos.`,
      eyebrow: 'Items Padrão', newTitle: 'Novo item de catálogo', editTitleFull: p => `Editar · ${p.id}`,
      saveChanges: 'Guardar alterações', createItem: 'Criar item',
      fillRequired: 'Preencha todos os campos obrigatórios', updated: p => `Item actualizado · ${p.id}`, created: p => `Item criado · ${p.id}`,
      confirmTitle: 'Eliminar item do catálogo?', confirmBody: p => `"${p.desc}" será removido. Orçamentos já emitidos não serão afectados.`,
      confirmOk: 'Eliminar item', deleted: p => `Item eliminado · ${p.id}`,
    },
  },

  backoffice: {
    login: { eyebrow: 'thebots.lab / platform', title: 'Backoffice', desc: 'Acesso de operador para gerir bots, tenants e equipas.', password: 'Password', submit: 'Entrar', invalid: 'Login inválido' },
    cancel: 'Cancelar', save: 'Guardar', confirm: 'Confirmar', delete: 'Eliminar', loadError: 'Erro ao carregar',
    error: p => `Erro: ${p.msg}`,
    kpiActive: 'Activos', kpiMessages: 'Mensagens', searchPlaceholder: 'Procurar tenant…', themeAria: 'Mudar tema',
    logout: 'Sair', crumbRoot: 'Platform', drawerEyebrow: 'Tenant', brandSub: 'Platform · Tenants', closeAria: 'Fechar',
    heroTitle: 'Tenants', heroDesc: 'Bots/clientes configurados nesta plataforma.',
    botsTitle: 'Bots',
    thName: 'Nome', thSlug: 'Slug', thChannels: 'Channels', thAgent: 'Agent', thStatus: 'Status', thMsgs: 'Msgs', thLastActivity: 'Última actividade', thActions: 'Acções',
    emptyTenants: 'Nenhum tenant encontrado',
    openDashboard: 'Open Dashboard', users: 'Users', edit: 'Edit', suspend: 'Suspend', activate: 'Activate', reload: 'Reload',
    pipelineReloaded: 'Pipeline recarregada',
    noToken: 'no token', token: 'token',
    usersTitle: p => `Dashboard users · ${p.slug}`,
    thEmail: 'Email', thRole: 'Role',
    noUsers: 'Sem utilizadores', disable: 'Disable',
    emailLabel: 'Email', tempPassword: 'Password temporária', roleLabel: 'Role',
    createUser: 'Criar utilizador', emailPasswordRequired: 'Email e password obrigatórios', userCreated: 'Utilizador criado',
    userDisabled: 'Utilizador desactivado', userActivated: 'Utilizador activado',
    tenantNameLabel: 'Nome', tenantSlugLabel: 'Slug', agentTypeLabel: 'Agent type', languageLabel: 'Idioma',
    modelOverride: 'Model override', modelPlaceholder: 'blank = default',
    ratePerHour: 'Rate / hour', ratePerDay: 'Rate / day',
    modulesLabel: 'Modules', modulesHint: 'Always-on modules stay checked. CRM modules require agent type CRM_V1.',
    channelsLabel: 'Channels', connectWhatsApp: 'Connect WhatsApp', connectInstagram: 'Connect Instagram', addChannel: '+ Add channel',
    colPlatform: 'Platform', colExternalId: 'External ID', colAccessToken: 'Access token',
    channelsHint: 'Instagram token is required when adding a channel. In edit, leave token blank to keep the existing one.',
    chExternalPlaceholder: 'phone_number_id or IG account id', chTokenUnchanged: 'unchanged', chTokenPlaceholder: 'access token', removeChannel: 'Remove channel',
    editTenant: p => `Editar · ${p.slug}`, newTenant: 'Novo bot/cliente', saveChanges: 'Guardar alterações', createTenant: 'Criar tenant',
    nameRequired: 'Nome obrigatório', addOneChannel: 'Adicione pelo menos um channel', igNeedsToken: 'Instagram precisa de Page access token',
    tenantUpdated: 'Tenant actualizado', botCreated: 'Bot criado. Liga os canais à app Meta e aponta o webhook.',
    suspendTitle: 'Suspender tenant?', activateTitle: 'Activar tenant?', tenantLine: p => `Tenant ${p.slug}`,
    deleteTitle: 'Eliminar tenant?', deleteBody: p => `${p.slug} ficará marcado como DELETED. Dados existentes não serão apagados.`,
    igSessionExpired: 'Sessão expirada', igNotConfigured: 'Instagram OAuth não configurado (IG_APP_ID)',
    igAllowPopups: 'Permite popups para ligar o Instagram', igConnected: 'Instagram ligado ✓', igFailed: p => `Instagram falhou: ${p.reason || 'erro'}`,
    waNotConfigured: 'WhatsApp Embedded Signup não configurado', waOpenPopup: 'Abre o popup Meta para ligar o WhatsApp', waConnected: 'WhatsApp ligado',
    waCancelled: 'Ligação WhatsApp cancelada', waMissingCode: 'Meta não devolveu o código de autorização',
    waTimeout: 'Tempo esgotado à espera do Embedded Signup', waSdkFailed: 'Não foi possível carregar o Facebook SDK', waFailed: p => `WhatsApp falhou: ${p.msg}`,
  },
};
