/* English UI catalog. Registered into window.__I18N_CATALOGS['en'].
   Namespaces: common (shared), app (tenant dashboard), admin (CRM), backoffice (super-admin). */
window.__I18N_CATALOGS = window.__I18N_CATALOGS || {};
window.__I18N_CATALOGS['en'] = {
  common: {
    nav: {
      overview: 'Overview', conversations: 'Conversations', contacts: 'Contacts',
      clients: 'Clients', quotes: 'Quotes', invoices: 'Invoices', catalog: 'Catalog',
      persona: 'Persona', settings: 'Settings',
    },
    lang: {
      title: 'Language', desc: 'Language used across this dashboard.', label: 'Language',
      saved: 'Language updated ✓', saveFailed: 'Could not update language',
    },
  },

  app: {
    settingsDesc: 'Connected channels and bot configuration.',
    channelsTitle: 'Channels',
    channelsDesc: 'Accounts where the assistant replies to your customers.',
    colChannel: 'Channel', colAccount: 'Account', colStatus: 'Status', colActions: 'Actions',
    connected: 'Connected', notConnected: 'Not connected',
    igConnect: 'Connect Instagram', igReconnect: 'Reconnect Instagram',
    igHint: 'Connecting Instagram opens a Meta window to authorize your professional account. The account must be Business or Creator.',
    moreSettingsTitle: 'More settings coming soon',
    moreSettingsDesc: 'Team members are managed in the backoffice for now. Business profile / PDF branding still pending.',
    sessionExpired: 'Session expired',
    igUnavailable: 'Instagram connection is not available',
    igAllowPopups: 'Allow popups to connect Instagram',
    igConnected: 'Instagram connected ✓',
    igFailed: reason => `Could not connect Instagram${reason ? ` (${reason})` : ''}`,
    webTitle: 'Website widget',
    webDesc: 'Add the chat assistant to your website. Paste this snippet just before the closing </body> tag.',
    webGenerate: 'Generate widget code',
    webRegenerate: 'Widget active',
    webCopy: 'Copy snippet',
    webCopied: 'Snippet copied ✓',
    webGenerated: 'Widget code generated ✓',
    webGenerateFailed: 'Could not generate widget code',
    webOriginsLabel: 'Allowed website domains (optional)',
    webOriginsHint: 'One origin per line, e.g. https://www.yoursite.com. Leave empty to allow any site (less secure).',
    webOriginsSave: 'Save domains',
    webOriginsSaved: 'Domains saved ✓',
    webRowName: 'Website',
    quickCreateSoon: 'Quick create for this module is coming soon.',
    loginEyebrow: 'thebots.lab / tenant',
    loginTitle: 'Sign in to the dashboard',
    loginDesc: 'Access your chatbot data, conversations and CRM.',
    loginEmail: 'Email', loginPassword: 'Password', loginSubmit: 'Sign in', loginInvalid: 'Invalid login',
    newPrefix: 'New',
    dashboardWord: 'Dashboard', searchPlaceholder: 'Search…', logout: 'Log out', themeAria: 'Toggle theme',
    noData: 'No data',
    overviewDesc: 'Chatbot status and recent activity.',
    statMessages24h: 'Messages 24h', statMessages: 'Messages', statContacts: 'Contacts', statConversations: 'Conversations', statQuotes: 'Quotes', statInvoices: 'Invoices',
    contactsDesc: 'End-users who talked to the bot.',
    thName: 'Name', thStatus: 'Status', thLastSeen: 'Last seen', thActions: 'Actions',
    block: 'Block', unblock: 'Unblock',
    conversationsDesc: 'Read-only conversation history.',
    thState: 'State', thMsgs: 'Msgs', thLast: 'Last',
    threadTitle: 'Conversation', noMessages: 'No messages',
    clientsDesc: 'CRM · Clients.', thPhone: 'Phone', thAddress: 'Address', thNo: 'No.',
    quotesDesc: 'CRM · Commercial proposals.', thNumber: 'Number', thClient: 'Client', thTotal: 'Total',
    invoicesDesc: 'CRM · Issued invoices.', thDueDate: 'Due date',
    catalogDesc: 'CRM · Standard services and materials.', thType: 'Type', thCategory: 'Category', thDescription: 'Description', thUnit: 'Unit', thPrice: 'Price',
    personaDesc: 'Bot personality — synthesized from notes and files you upload.',
    personaCompiling: 'Synthesizing…', statVersion: 'Version', statTokens: 'Tokens est.', statUpdated: 'Updated',
    testBotTitle: 'Test the bot', clear: 'Clear',
    testBotDesc: 'Chat with the bot using the current persona to test tone and replies. Test messages are not saved and do not create clients, quotes or invoices.',
    chatPlaceholder: 'Type a test message…', send: 'Send',
    chatEmpty: 'Send a message to test the bot persona.', typing: 'typing…', chatError: '⚠️ Error contacting the bot. Please try again.',
    addInfoTitle: 'Add information',
    addInfoDesc: 'Write a note or upload a file (PDF, TXT, MD). It is synthesized into the instructions file below.',
    noteLabel: 'Note', notePlaceholder: 'E.g.: We are a dental clinic in Lisbon. Warm tone, formal address...', addNote: 'Add note',
    fileLabel: 'File', fileHint: 'PDF, TXT or Markdown. The text is extracted and synthesized.',
    sourcesTitle: 'Sources', sourcesDesc: 'Raw material feeding the synthesis.', rebuildAll: 'Recompile all',
    sourceSynced: 'synced', sourcePending: 'pending', remove: 'Remove',
    thSource: 'Source', thCreated: 'Created',
    noSourcesTitle: 'No sources yet', noSourcesDesc: 'Add a note or file above.',
    compiledTitle: 'Compiled instructions file',
    compiledDesc: 'Synthesis result. You can edit it manually; the next synthesis will review it.',
    compiledPlaceholder: 'Still empty — add information above to give the bot personality.',
    saveManual: 'Save manual edit',
    personaSaved: 'Persona saved', noteAdded: 'Note added — synthesizing', fileUploaded: 'File uploaded — synthesizing', rebuildStarted: 'Recompilation started', uploadFailed: 'Upload failed',
  },

  admin: {
    nav: { clientes: 'Clients', orcamentos: 'Quotes', faturas: 'Invoices', items: 'Standard items' },
    crumbRoot: 'Panel',
    brandSub: 'Tenant · Management',
    searchPlaceholder: 'Search this view…',
    export: 'Export', exportTitle: 'Export CSV', exportSoon: 'Export · coming soon',
    backoffice: '← Backoffice', themeAria: 'Toggle theme', closeAria: 'Close',
    kpiReceivable: 'Receivable', kpiPaid: 'Paid this month',
    saving: 'Saving…', cancel: 'Cancel', save: 'Save', confirm: 'Confirm', delete: 'Delete',
    loading: 'Loading…', loadError: 'Load error',
    login: { eyebrow: p => `thebots.lab / ${p.tenant}`, title: 'Sign in to the CRM', desc: 'Use the operator password to open this management panel.', password: 'Password', submit: 'Sign in', invalid: 'Invalid login', crumb: 'Login' },
    invalidTenantTitle: 'Invalid tenant', invalidTenantDesc: 'Go back to the backoffice and open a valid CRM.',
    titleSuffix: 'Management Panel',
    pdfPending: 'pending',
    errorPdf: p => `PDF error: ${p.msg}`,
    error: p => `Error: ${p.msg}`,
    quoteStatus: { PENDENTE: 'Pending', ACEITO: 'Accepted' },
    invoiceStatus: { PENDING: 'PENDING', PAID: 'PAID', OVERDUE: 'OVERDUE', CANCELLED: 'CANCELLED' },
    tabs: {
      clientes: { title: 'Clients', desc: 'Company client directory.', newLabel: 'New client' },
      orcamentos: { title: 'Quotes', desc: 'Issued commercial proposals.', newLabel: 'New quote' },
      faturas: { title: 'Invoices', desc: 'Issued invoices and their status.', newLabel: 'New invoice' },
      items: { title: 'Standard items', desc: 'Catalog of services and materials for quotes and invoices.', newLabel: 'New item' },
    },
    clients: {
      total: 'Total', new30: 'New · 30d', directory: 'Directory',
      one: 'client', many: 'clients',
      thName: 'Name', thAddress: 'Address', thPhone: 'Phone', thCreated: 'Created', thNo: 'Client no.',
      emptyTitle: 'No clients found', emptyDesc: 'Adjust the search or create a new client.',
      formName: 'Name', formAddress: 'Address', formPhone: 'Phone',
      phName: 'E.g.: Manuel Costa, Ltd.', phAddress: 'E.g.: 12 Rua das Flores, 1200-001 Lisbon', phPhone: '+351 912 345 678',
      eyebrow: 'Clients', formTitle: 'New client', saveLabel: 'Create client',
      validate: 'Enter name and phone', created: p => `Client created · ${p.name}`,
    },
    quotes: {
      total: 'Total', sent: 'Sent', accepted: 'Accepted', proposals: 'Proposals', filterAll: 'All',
      thNumber: 'Number', thClient: 'Client', thStatus: 'Status', thValidUntil: 'Valid until', thTotal: 'Total', thPdf: 'PDF',
      emptyTitle: 'No quotes', emptyDesc: 'Create the first quote with the button above.',
      validUntil: 'Valid until', optional: 'optional', notes: 'Notes', notesPlaceholder: 'Internal notes, conditions, deadlines…',
      eyebrow: 'Quotes', formTitle: 'New quote', saveLabel: 'Create quote',
      chooseClient: 'Choose a client', addLine: 'Add at least one line', created: 'Quote created',
    },
    invoices: {
      paid: 'Paid', pending: 'Pending', overdue: 'Overdue', documents: 'Documents', filterAll: 'All',
      thNumber: 'Number', thClient: 'Client', thStatus: 'Status', thDueDate: 'Due date', thTotal: 'Total', thPdfActions: 'PDF · Actions',
      emptyTitle: 'No invoices', emptyDesc: 'Issue the first invoice with the button above.',
      markPaid: 'Mark paid', markedPaid: p => `Invoice ${p.number} marked as paid`,
      dueDate: 'Due date', quoteId: 'Quote ID', quoteIdPlaceholder: 'Associated quote ID',
      eyebrow: 'Invoices', formTitle: 'New invoice', saveLabel: 'Issue invoice',
      chooseClient: 'Choose a client', enterDueDate: 'Enter the due date', addLine: 'Add at least one line', issued: 'Invoice issued',
    },
    lines: {
      client: 'Client', chooseClient: '— Choose client —',
      services: 'Services', materials: 'Materials', label: 'Lines',
      colDescription: 'Description', colQty: 'Qty', colUnit: 'Unit', colPrice: 'Price €',
      addEmpty: '+ Empty line', catalogPick: 'Catalog · Services / Materials', add: 'Add', total: 'Total',
      descPlaceholder: 'Line description…', unitPlaceholder: 'un', removeLine: 'Remove line', chooseCatalogItem: 'Choose a catalog item',
    },
    items: {
      services: 'Services', materials: 'Materials', catalogTitle: 'Catalog', tag: p => `${p.n} items`,
      thType: 'Type', thCategory: 'Category', thDescription: 'Description', thUnit: 'Unit', thPrice: 'Price', thActions: 'Actions',
      emptyTitle: 'Empty catalog', emptyDesc: 'Add services or materials to reuse in quotes.',
      pillService: 'SERVICE', pillMaterial: 'MATERIAL', editTitle: 'Edit', deleteTitle: 'Delete',
      idLabel: 'ID · slug', typeLabel: 'Type', service: 'Service', material: 'Material',
      categoryLabel: 'Category', descLabel: 'Description', unitLabel: 'Unit', priceLabel: 'Price (EUR)',
      phId: 'e.g.: srv-interior-painting', phCategory: 'E.g.: Painting, Structural, Labour…', phDesc: 'Description shown on quotes', phUnit: 'm², h, un, rl…',
      editingHint: p => `Editing ${p.id} — changes apply to new quotes.`,
      eyebrow: 'Standard items', newTitle: 'New catalog item', editTitleFull: p => `Edit · ${p.id}`,
      saveChanges: 'Save changes', createItem: 'Create item',
      fillRequired: 'Fill all required fields', updated: p => `Item updated · ${p.id}`, created: p => `Item created · ${p.id}`,
      confirmTitle: 'Delete catalog item?', confirmBody: p => `"${p.desc}" will be removed. Already-issued quotes are not affected.`,
      confirmOk: 'Delete item', deleted: p => `Item deleted · ${p.id}`,
    },
  },

  backoffice: {
    login: { eyebrow: 'thebots.lab / platform', title: 'Backoffice', desc: 'Operator access to manage bots, tenants and teams.', password: 'Password', submit: 'Sign in', invalid: 'Invalid login' },
    cancel: 'Cancel', save: 'Save', confirm: 'Confirm', delete: 'Delete', loadError: 'Load error',
    error: p => `Error: ${p.msg}`,
    kpiActive: 'Active', kpiMessages: 'Messages', searchPlaceholder: 'Search tenant…', themeAria: 'Toggle theme',
    logout: 'Log out', crumbRoot: 'Platform', drawerEyebrow: 'Tenant', brandSub: 'Platform · Tenants', closeAria: 'Close',
    heroTitle: 'Tenants', heroDesc: 'Bots/clients configured on this platform.',
    botsTitle: 'Bots',
    thName: 'Name', thSlug: 'Slug', thChannels: 'Channels', thAgent: 'Agent', thStatus: 'Status', thMsgs: 'Msgs', thLastActivity: 'Last activity', thActions: 'Actions',
    emptyTenants: 'No tenants found',
    openDashboard: 'Open Dashboard', users: 'Users', edit: 'Edit', suspend: 'Suspend', activate: 'Activate', reload: 'Reload',
    pipelineReloaded: 'Pipeline reloaded',
    noToken: 'no token', token: 'token',
    usersTitle: p => `Dashboard users · ${p.slug}`,
    thEmail: 'Email', thRole: 'Role',
    noUsers: 'No users', disable: 'Disable',
    emailLabel: 'Email', tempPassword: 'Temporary password', roleLabel: 'Role',
    createUser: 'Create user', emailPasswordRequired: 'Email and password required', userCreated: 'User created',
    userDisabled: 'User disabled', userActivated: 'User activated',
    tenantNameLabel: 'Name', tenantSlugLabel: 'Slug', agentTypeLabel: 'Agent type', languageLabel: 'Language',
    modelOverride: 'Model override', modelPlaceholder: 'blank = default',
    ratePerHour: 'Rate / hour', ratePerDay: 'Rate / day',
    modulesLabel: 'Modules', modulesHint: 'Always-on modules stay checked. CRM modules require agent type CRM_V1.',
    channelsLabel: 'Channels', connectWhatsApp: 'Connect WhatsApp', connectInstagram: 'Connect Instagram', addChannel: '+ Add channel',
    colPlatform: 'Platform', colExternalId: 'External ID', colAccessToken: 'Access token',
    channelsHint: 'Instagram token is required when adding a channel. In edit, leave token blank to keep the existing one.',
    chExternalPlaceholder: 'phone_number_id or IG account id', chTokenUnchanged: 'unchanged', chTokenPlaceholder: 'access token', removeChannel: 'Remove channel',
    editTenant: p => `Edit · ${p.slug}`, newTenant: 'New bot/client', saveChanges: 'Save changes', createTenant: 'Create tenant',
    nameRequired: 'Name required', addOneChannel: 'Add at least one channel', igNeedsToken: 'Instagram needs a Page access token',
    tenantUpdated: 'Tenant updated', botCreated: 'Bot created. Link the channels to the Meta app and point the webhook.',
    suspendTitle: 'Suspend tenant?', activateTitle: 'Activate tenant?', tenantLine: p => `Tenant ${p.slug}`,
    deleteTitle: 'Delete tenant?', deleteBody: p => `${p.slug} will be marked DELETED. Existing data is not erased.`,
    igSessionExpired: 'Session expired', igNotConfigured: 'Instagram OAuth not configured (IG_APP_ID)',
    igAllowPopups: 'Allow popups to connect Instagram', igConnected: 'Instagram connected ✓', igFailed: p => `Instagram failed: ${p.reason || 'error'}`,
    waNotConfigured: 'WhatsApp Embedded Signup not configured', waOpenPopup: 'Open the Meta popup to connect WhatsApp', waConnected: 'WhatsApp connected',
    waCancelled: 'WhatsApp connection cancelled', waMissingCode: 'Meta did not return the authorization code',
    waTimeout: 'Timed out waiting for Embedded Signup', waSdkFailed: 'Could not load the Facebook SDK', waFailed: p => `WhatsApp failed: ${p.msg}`,
  },
};
