/* Portuguese (pt-PT) UI catalog. Registered into window.__I18N_CATALOGS['pt-PT']. */
window.__I18N_CATALOGS = window.__I18N_CATALOGS || {};
window.__I18N_CATALOGS['pt-PT'] = {
  common: {
    nav: {
      overview: 'Início', conversations: 'Conversas', contacts: 'Contactos',
      clients: 'Clientes', quotes: 'Orçamentos', invoices: 'Faturas', catalog: 'Catálogo',
      persona: 'Persona', settings: 'Definições', 'ai-assistant': 'Assistente IA', bookings: 'Marcações', instagram: 'Instagram',
      groupInbox: 'Inbox', groupBusiness: 'Negócio', groupBot: 'Bot', groupSetup: 'Configuração',
    },
    lang: {
      title: 'Idioma', desc: 'Idioma usado neste painel.', label: 'Idioma',
      saved: 'Idioma atualizado ✓', saveFailed: 'Não foi possível atualizar o idioma',
    },
    menuOpenAria: 'Abrir menu',
    menuCloseAria: 'Fechar menu',
    themeToLight: 'Mudar para tema claro',
    themeToDark: 'Mudar para tema escuro',
  },

  app: {
    settingsDesc: 'Canais ligados e configuração do bot.',
    channelsTitle: 'Canais',
    channelsDesc: 'Contas onde o assistente responde aos seus clientes.',
    colChannel: 'Canal', colAccount: 'Conta', colStatus: 'Estado', colActions: 'Ações',
    connected: 'Ligado', notConnected: 'Não ligado',
    igConnect: 'Ligar Instagram', igReconnect: 'Religar Instagram',
    waConnect: 'Ligar WhatsApp', waReconnect: 'Religar WhatsApp',
    channelsHint: 'WhatsApp e Instagram abrem uma janela Meta para autorizar a sua conta empresarial. O Instagram tem de ser Business ou Creator.',
    igHint: 'Ligar o Instagram abre uma janela Meta para autorizar a sua conta profissional. A conta tem de ser Business ou Creator.',
    moreSettingsTitle: 'Mais definições em breve',
    moreSettingsDesc: 'Os membros da equipa são geridos no backoffice por agora.',
    docTemplateTitle: 'Modelo de orçamento e fatura',
    docTemplateDesc: 'Desenhe a página usada nos PDFs de orçamento e fatura. Arraste e redimensione as caixas e grave.',
    docCompanyName: 'Nome da empresa', docTagline: 'Slogan', docTaglinePh: 'ex.: Construção e gestão',
    docTaxId: 'NIF', docTaxIdPh: 'NIF / IVA', docEmail: 'Email', docPhone: 'Telefone', docAddress: 'Morada',
    docQuoteTitle: 'Título do orçamento', docInvoiceTitle: 'Título da fatura',
    docQuotePayment: 'Condições de pagamento (orçamentos)', docInvoicePayment: 'Condições de pagamento (faturas)',
    docTerms: 'Termos e condições', docFooter: 'Rodapé',
    docLogo: 'Logótipo', docLogoNone: 'Sem logótipo', docLogoLoading: 'A carregar logótipo…',
    docLogoUpload: 'Carregar logótipo', docLogoRemove: 'Remover logótipo',
    docLogoHint: 'PNG, JPG ou WebP, máx. 2 MB. Aparece nos PDFs de orçamento e fatura.',
    docLogoUploaded: 'Logótipo carregado', docLogoRemoved: 'Logótipo removido', docLogoUploadFailed: 'Não foi possível atualizar o logótipo',
    docTemplateSave: 'Guardar modelo', docTemplateSaved: 'Modelo de documento guardado',
    docTemplateSaveFailed: 'Não foi possível guardar o modelo',
    docTplDragHint: 'Arraste uma caixa para a mover. Redimensione pelas pegas. Clique numa caixa para editar o conteúdo.',
    docTplPreviewQuote: 'Orçamento', docTplPreviewInvoice: 'Fatura',
    docTplResetLayout: 'Repor disposição', docTplLayoutReset: 'Disposição reposta para a página predefinida',
    docTplLayers: 'Blocos', docTplInspector: 'Bloco selecionado',
    docTplEmptySelect: 'Clique numa caixa da página para a editar.',
    docTplAccent: 'Cor de destaque', docTplDecor: 'Ondas decorativas',
    docTplShow: 'Mostrar', docTplHide: 'Ocultar',
    docTplPos: 'Posição', docTplSize: 'Tamanho',
    docTplSampleHint: 'A pré-visualização usa dados de exemplo. Orçamentos e faturas reais preenchem isto a partir do CRM.',
    docTplPageLabel: 'A4 · 210 × 297 mm',
    docTplDirty: 'Alterações por gravar',
    docTplColService: 'Serviço', docTplColDesc: 'Descrição', docTplColValue: 'Valor',
    docTplClientLabel: 'Cliente', docTplPaymentLabel: 'Forma de pagamento', docTplTermsLabel: 'Termos e condições',
    docTplDateLabel: 'Data', docTplTotalLabel: 'Total',
    docTplSampleClient: 'Cliente exemplo', docTplSamplePhone: '+351 210 000 000',
    docTplSampleItem1: 'Pintura interior', docTplSampleItem1Desc: 'Preparação e duas demãos',
    docTplSampleItem2: 'Reboco exterior', docTplSampleItem2Desc: 'Reparação e acabamento de fachada',
    docTplSampleQuoteNo: 'ORC-1042', docTplSampleInvoiceNo: 'FAT-1042',
    docTplBlockLogo: 'Logótipo', docTplBlockContact: 'Contacto', docTplBlockCompany: 'Empresa',
    docTplBlockTitle: 'Título do documento', docTplBlockClient: 'Cliente', docTplBlockItems: 'Linhas',
    docTplBlockTotals: 'Total', docTplBlockPayment: 'Condições de pagamento', docTplBlockTerms: 'Termos',
    docTplBlockFooter: 'Rodapé',
    docTplHideAria: 'Alternar visibilidade',
    docTplColorAria: 'Cor de destaque',
    sessionExpired: 'Sessão expirada',
    igUnavailable: 'A ligação ao Instagram não está disponível',
    igAllowPopups: 'Permita popups para ligar o Instagram',
    igConnected: 'Instagram ligado ✓',
    igFailed: reason => `Não foi possível ligar o Instagram${reason ? ` (${reason})` : ''}`,
    waNotConfigured: 'A ligação ao WhatsApp não está disponível',
    waOpenPopup: 'Abre o popup Meta para ligar o WhatsApp',
    waConnected: 'WhatsApp ligado ✓',
    waCancelled: 'Ligação ao WhatsApp cancelada',
    waMissingCode: 'A Meta não devolveu o código de autorização',
    waTimeout: 'Tempo esgotado à espera do registo WhatsApp',
    waSdkFailed: 'Não foi possível carregar o Facebook SDK',
    waFailed: p => `Não foi possível ligar o WhatsApp${p?.msg ? ` (${p.msg})` : ''}`,
    webTitle: 'Widget do site',
    webDesc: 'Adicione o assistente de chat ao seu site. Cole este snippet imediatamente antes da etiqueta </body>.',
    webGenerate: 'Gerar código do widget',
    webRegenerate: 'Widget ativo',
    webCopy: 'Copiar snippet',
    webCopied: 'Snippet copiado ✓',
    webGenerated: 'Código do widget gerado ✓',
    webGenerateFailed: 'Não foi possível gerar o código do widget',
    webOriginsLabel: 'Domínios de site permitidos (opcional)',
    webOriginsHint: 'Uma origem por linha, ex.: https://www.oseusite.com. Deixe vazio para permitir qualquer site (menos seguro).',
    webOriginsSave: 'Guardar domínios',
    webOriginsSaved: 'Domínios guardados ✓',
    webRowName: 'Site',
    quickCreateSoon: 'A criação rápida deste módulo está para breve.',
    clientFormTitle: 'Novo cliente',
    clientFormName: 'Nome', clientFormPhone: 'Telefone', clientFormAddress: 'Morada',
    clientPhName: 'Nome do cliente', clientPhPhone: '+351…', clientPhAddress: 'Rua, cidade',
    clientSave: 'Criar cliente',
    clientValidate: 'Introduza nome e telefone',
    clientCreated: p => `Cliente criado · ${p.name}`,
    clientCreateFailed: 'Não foi possível criar o cliente',
    optional: 'opcional',
    catalogFormTitle: 'Novo item', catalogSave: 'Criar item',
    catalogId: 'ID', catalogType: 'Tipo', catalogService: 'Serviço', catalogMaterial: 'Material',
    catalogCategory: 'Categoria', catalogDesc: 'Descrição', catalogUnit: 'Unidade', catalogPrice: 'Preço (€)',
    catalogPhId: 'srv-…', catalogPhCategory: 'Ex.: Fachadas', catalogPhDesc: 'O que este item cobre', catalogPhUnit: 'm2, unidade, serviço…',
    catalogValidate: 'Preencha todos os campos obrigatórios', catalogCreated: p => `Item criado · ${p.id}`, catalogCreateFailed: 'Não foi possível criar o item',
    quoteFormTitle: 'Novo orçamento', quoteSave: 'Criar orçamento',
    quoteValidUntil: 'Válido até', quoteNotes: 'Notas', quoteNotesPh: 'Notas opcionais mostradas no PDF',
    quoteChooseClient: 'Escolha um cliente', quoteAddLine: 'Adicione pelo menos uma linha', quoteCreated: 'Orçamento criado', quoteCreateFailed: 'Não foi possível criar o orçamento',
    invoiceFormTitle: 'Nova fatura', invoiceSave: 'Emitir fatura',
    invoiceDueDate: 'Vencimento', invoiceQuoteId: 'ID do orçamento', invoiceQuoteIdPh: 'Associar um orçamento existente (opcional)',
    invoiceChooseClient: 'Escolha um cliente', invoiceEnterDueDate: 'Indique a data de vencimento', invoiceAddLine: 'Adicione pelo menos uma linha', invoiceCreated: 'Fatura emitida', invoiceCreateFailed: 'Não foi possível emitir a fatura',
    lineClient: 'Cliente', lineChooseClient: 'Selecionar…', lineItemsLabel: 'Linhas',
    lineColDesc: 'Descrição', lineColQty: 'Qtd', lineColUnit: 'Unid.', lineColPrice: 'Preço',
    lineAddEmpty: 'Adicionar linha', lineCatalogPick: 'Do catálogo…', lineAdd: 'Adicionar', lineTotal: 'Total',
    lineDescPh: 'Descrição', lineUnitPh: 'un', lineRemove: 'Remover linha', lineChooseCatalog: 'Escolha um item do catálogo',
    loginEyebrow: 'thebots.lab / tenant',
    loginTitle: 'Entrar no painel',
    loginDesc: 'Aceda aos dados do chatbot, conversas e CRM.',
    loginEmail: 'Email', loginPassword: 'Password', loginSubmit: 'Entrar', loginInvalid: 'Login inválido',
    newPrefix: 'Novo',
    dashboardWord: 'Painel', searchPlaceholder: 'Procurar…', logout: 'Sair', themeAria: 'Mudar tema',
    closeAria: 'Fechar', cancel: 'Cancelar', confirm: 'Confirmar',
    noData: 'Sem dados',
    contactStatusACTIVE: 'Activo', contactStatusBLOCKED: 'Bloqueado', contactStatusRATE_LIMITED: 'Com limite',
    conversationStateACTIVE: 'Aberta', conversationStateARCHIVED: 'Arquivada',
    markPaidConfirmTitle: 'Marcar esta fatura como paga?',
    markPaidConfirmBody: p => `A fatura ${p.number} será marcada como paga.`,
    overviewDesc: 'O que precisa de si hoje, e o que falta configurar.',
    needsYou: 'Precisa de si', needsYouEmpty: 'Está em dia',     needsYouEmptyDesc: 'Sem conversas à espera, faturas vencidas, marcações pendentes ou comentários no Instagram.',
    setupTitle: 'Concluir configuração', setupDone: 'A configuração parece completa.',
    todayTitle: 'Hoje',
    waitingChat: 'À espera de resposta', overdueInvoice: 'Fatura vencida', pendingBooking: 'Marcação pendente', instagramWaitingComment: 'Comentário no Instagram',
    teachBot: 'Ensinar o bot', setupWidget: 'Adicionar o widget do site',
    openInbox: 'Abrir inbox', viewInvoices: 'Ver faturas', viewBookings: 'Ver marcações',
    waiting: 'À espera', noThread: 'Selecione uma conversa', noThreadDesc: 'Escolha um cliente à esquerda para ler e responder.',
    quoteMarkSent: 'Marcar enviado', quoteAccept: 'Aceitar', quoteConvert: 'Converter em fatura',
    quoteConverted: 'Fatura emitida a partir deste orçamento', quoteStatusUpdated: 'Orçamento atualizado',
    quoteConvertDue: 'Vencimento da fatura', quoteConvertFailed: 'Não foi possível converter este orçamento',
    clientUpdated: 'Cliente atualizado', clientUpdateFailed: 'Não foi possível atualizar o cliente', clientEdit: 'Editar cliente',
    settingsChannels: 'Canais', settingsWidget: 'Website', settingsLanguage: 'Idioma', settingsDocuments: 'Documentos',
    widgetPreview: 'Pré-visualização', widgetPreviewHi: 'Olá — como podemos ajudar?', widgetPreviewLive: 'Atualização em direto',
    widgetContentTitle: 'Conversa', widgetAppearanceTitle: 'Aparência',
    widgetTitleLabel: 'Nome do assistente', widgetSubtitleLabel: 'Mensagem de estado', widgetWelcomeLabel: 'Mensagem de boas-vindas',
    widgetPlaceholderLabel: 'Texto do campo', widgetLauncherLabel: 'Texto do botão', widgetAccentLabel: 'Cor da marca',
    widgetPositionLabel: 'Posição', widgetPositionRight: 'Inferior direita', widgetPositionLeft: 'Inferior esquerda',
    widgetThemeLabel: 'Tema', widgetThemeLight: 'Claro', widgetThemeDark: 'Escuro', widgetThemeAuto: 'Definição do dispositivo',
    widgetInstallTitle: 'Instalar no seu site', widgetInstallHint: 'O snippet é atualizado à medida que personaliza. Copie-o e cole-o antes da etiqueta </body>.',
    widgetEmptyTitle: 'Crie o chat do seu site', widgetEmptyDesc: 'Gere uma chave segura, adapte o assistente à sua marca e veja aqui o resultado.',
    widgetDefaultTitle: 'Chat', widgetDefaultSubtitle: 'Normalmente responde de imediato', widgetDefaultWelcome: 'Olá! Como podemos ajudar?',
    widgetDefaultPlaceholder: 'Escreva uma mensagem…', widgetDefaultLauncher: 'Fale connosco',
    personaAdvanced: 'Avançado', personaAdvancedHint: 'Instruções compiladas que o bot usa. Edite só se souber o que está a alterar.',
    statMessages24h: 'Mensagens 24h', statMessages: 'Mensagens', statContacts: 'Contactos', statConversations: 'Conversas', statQuotes: 'Orçamentos', statInvoices: 'Faturas',
    contactsDesc: 'Utilizadores finais que falaram com o bot.',
    thName: 'Nome', thStatus: 'Estado', thLastSeen: 'Visto', thActions: 'Ações',
    block: 'Bloquear', unblock: 'Desbloquear',
    conversationsDesc: 'Abra uma conversa e envie uma mensagem em direto a partir de uma conta ligada.',
    thState: 'Estado', thMsgs: 'Msgs', thLast: 'Última',
    threadTitle: 'Conversa', noMessages: 'Sem mensagens',
    assetLabel: 'Ativo ligado', assetHint: 'Selecione a Página, conta ou número usado para enviar mensagens aos clientes.',
    unnamedAsset: 'Conta sem nome', recipient: 'Destinatário', noAssetConversations: 'Sem conversas para este ativo', noMessagingAssets: 'Ligue o Instagram ou WhatsApp para enviar mensagens',
    sendingFrom: 'A enviar de', sendingTo: 'Para', customer: 'Cliente', operator: 'Operador',
    messagePlaceholder: 'Escreva uma mensagem em direto…', sendUnavailable: 'Selecione o ativo desta conversa para enviar uma mensagem.',
    messageDelivered: 'Mensagem entregue', messageFailed: 'Não foi possível entregar a mensagem',
    openChat: 'Abrir conversa',
    clientsDesc: 'CRM · Clientes.', thPhone: 'Telefone', thAddress: 'Morada', thNo: 'Nº',
    quotesDesc: 'CRM · Propostas comerciais.', thNumber: 'Número', thClient: 'Cliente', thTotal: 'Total',
    invoicesDesc: 'CRM · Faturas emitidas.', thDueDate: 'Vencimento',
    thPdf: 'PDF', thPdfActions: 'PDF · Acções', viewPdf: 'Ver PDF', pdfPending: 'pendente',
    errorPdf: p => `Erro PDF: ${p.msg}`, loadFailed: 'Não foi possível carregar esta secção',
    markPaid: 'Marcar pago', markedPaid: p => `Fatura ${p.number} marcada como paga`, markPaidFailed: 'Não foi possível marcar a fatura como paga',
    catalogDesc: 'CRM · Serviços e materiais padrão.', thType: 'Tipo', thCategory: 'Categoria', thDescription: 'Descrição', thUnit: 'Unid.', thPrice: 'Preço',
    personaDesc: 'Personalidade do bot — sintetizada a partir das notas e ficheiros que carrega.',
    personaCompiling: 'A sintetizar…', statVersion: 'Versão', statTokens: 'Tokens est.', statUpdated: 'Atualizado',
    testBotTitle: 'Testar o bot', clear: 'Limpar',
    testBotDesc: 'Converse com o bot usando a persona atual para testar o tom e as respostas. As mensagens de teste não são guardadas e não criam clientes, orçamentos ou faturas.',
    chatPlaceholder: 'Escreva uma mensagem de teste…', send: 'Enviar',
    chatEmpty: 'Envie uma mensagem para testar a persona do bot.', typing: 'a escrever…', chatError: '⚠️ Erro ao contactar o bot. Tente novamente.',
    addInfoTitle: 'Adicionar informação',
    addInfoDesc: 'Escreva uma nota ou carregue um ficheiro (PDF, TXT, MD). É sintetizado no ficheiro de instruções abaixo.',
    noteLabel: 'Nota', notePlaceholder: 'Ex.: Somos uma clínica dentária em Lisboa. Tom acolhedor, tratamento formal...', addNote: 'Adicionar nota',
    fileLabel: 'Ficheiro', fileHint: 'PDF, TXT ou Markdown. O texto é extraído e sintetizado.',
    sourcesTitle: 'Fontes', sourcesDesc: 'Material em bruto que alimenta a síntese.', rebuildAll: 'Recompilar tudo',
    sourceSynced: 'sincronizado', sourcePending: 'pendente', remove: 'Remover',
    thSource: 'Fonte', thCreated: 'Criado',
    noSourcesTitle: 'Ainda sem fontes', noSourcesDesc: 'Adicione uma nota ou ficheiro acima.',
    compiledTitle: 'Ficheiro de instruções compilado',
    compiledDesc: 'Resultado da síntese. Pode editá-lo manualmente; a próxima síntese vai revê-lo.',
    compiledPlaceholder: 'Ainda vazio — adicione informação acima para dar personalidade ao bot.',
    saveManual: 'Guardar edição manual',
    personaSaved: 'Persona guardada', noteAdded: 'Nota adicionada — a sintetizar', fileUploaded: 'Ficheiro carregado — a sintetizar', rebuildStarted: 'Recompilação iniciada', uploadFailed: 'Falha no carregamento',
    assistantDesc: 'Faça perguntas sobre os dados do negócio e execute tarefas do dashboard com a sua aprovação.',
    assistantNewThread: 'Nova conversa', assistantNoThreads: 'Ainda não existem conversas',
    assistantEmpty: 'Comece por perguntar sobre clientes, catálogo, orçamentos ou faturas.', assistantPlaceholder: 'Pergunte ao assistente…',
    assistantError: 'O assistente não conseguiu responder. Tente novamente.', assistantActionError: 'Não foi possível atualizar a ação.',
    assistantProposedAction: 'Ação proposta', assistantConfirm: 'Confirmar ação', assistantCancel: 'Cancelar',
    assistantStatusPENDING: 'A aguardar aprovação', assistantStatusEXECUTING: 'Em execução', assistantStatusCONFIRMED: 'Concluída', assistantStatusFAILED: 'Falhou', assistantStatusCANCELLED: 'Cancelada',
    assistantCreateClient: p => `Criar cliente ${p.name}`, assistantCreateQuote: 'Criar orçamento', assistantUpdateQuote: p => `Atualizar orçamento ${p.id}`,
    assistantCreateInvoice: 'Criar fatura', assistantMarkPaid: p => `Marcar fatura ${p.id} como paga`, assistantChangeData: 'Alterar dados do dashboard',
    assistantClientRef: p => `Cliente: ${p.id}`, assistantQuoteRef: p => `Orçamento: ${p.id}`, assistantInvoiceRef: p => `Fatura: ${p.id}`,
    assistantValidUntil: p => `Válido até: ${p.date}`, assistantDueDate: p => `Vencimento: ${p.date}`, assistantNewStatus: p => `Novo estado: ${p.status}`,
    bookingsDesc: 'Marcações, serviços e disponibilidade semanal.',
    bookingsWeek: 'Semana', bookingsList: 'Lista', bookingsServices: 'Serviços', bookingsAvailability: 'Disponibilidade',
    bookingsPrev: 'Semana anterior', bookingsNext: 'Semana seguinte', bookingsToday: 'Esta semana',
    bookingsNew: 'Nova marcação', bookingsEdit: 'Editar marcação', bookingsSave: 'Guardar marcação',
    bookingsContactName: 'Nome do contacto', bookingsContactPhone: 'Telefone', bookingsService: 'Serviço',
    bookingsStart: 'Início', bookingsNotes: 'Notas', bookingsStatus: 'Estado', bookingsSource: 'Origem',
    bookingsChooseService: '— Escolher serviço —', bookingsCreated: 'Marcação criada', bookingsUpdated: 'Marcação atualizada',
    bookingsConflict: 'Esse horário sobrepõe outra marcação', bookingsValidate: 'Preencha nome, telefone, serviço e início',
    bookingsManageServices: 'Gerir serviços', bookingsManageAvailability: 'Horário semanal',
    bookingsServiceName: 'Nome do serviço', bookingsDuration: 'Duração (minutos)', bookingsActive: 'Ativo',
    bookingsServiceSaved: 'Serviço guardado', bookingsAvailabilitySaved: 'Disponibilidade guardada',
    bookingsAddWindow: 'Adicionar intervalo', bookingsDay: 'Dia', bookingsFrom: 'De', bookingsTo: 'Até',
    bookingsEmptyWeek: 'Sem marcações nesta semana', bookingsEmptyList: 'Nenhuma marcação encontrada',
    bookingsThWhen: 'Quando', bookingsThContact: 'Contacto', bookingsThService: 'Serviço', bookingsThStatus: 'Estado',
    bookingStatusPENDING: 'Pendente', bookingStatusCONFIRMED: 'Confirmada', bookingStatusCANCELLED: 'Cancelada', bookingStatusCOMPLETED: 'Concluída',
    weekday1: 'Seg', weekday2: 'Ter', weekday3: 'Qua', weekday4: 'Qui', weekday5: 'Sex', weekday6: 'Sáb', weekday7: 'Dom',
    instagramDesc: 'Veja os comentários nas publicações do Instagram e responda daqui.',
    instagramNeedsReply: 'Precisa de resposta', instagramPosts: 'Publicações',
    instagramEmptyComments: 'Nenhum comentário à espera',
    instagramEmptyCommentsDesc: 'Os novos comentários nas suas publicações aparecem aqui.',
    instagramEmptyPosts: 'Ainda sem publicações',
    instagramEmptyPostsDesc: 'Ligue o Instagram, publique, e volte a abrir esta página.',
    instagramNotConnected: 'Instagram não está ligado',
    instagramNotConnectedDesc: 'Ligue a conta profissional em Definições para ver publicações e comentários.',
    instagramReconnectBanner: 'Religue o Instagram para ver os comentários nas publicações.',
    instagramThPost: 'Publicação', instagramThComment: 'Comentário', instagramThFrom: 'De', instagramThWhen: 'Quando',
    instagramReply: 'Responder', instagramReplyPlaceholder: 'Escreva uma resposta pública…',
    instagramReplied: 'Resposta enviada', instagramReplyFailed: 'Não foi possível enviar a resposta',
    instagramOpenPost: 'Abrir no Instagram', instagramUnreplied: 'Sem resposta',
    instagramNoCaption: 'Sem legenda', instagramGoSettings: 'Abrir Definições',
    instagramSyncFailed: 'Não foi possível atualizar o Instagram',
  },

  admin: {
    nav: { clientes: 'Clientes', orcamentos: 'Orçamentos', faturas: 'Faturas', items: 'Items Padrão', bookings: 'Marcações' },
    crumbRoot: 'Painel',
    brandSub: 'Tenant · Gestão',
    searchPlaceholder: 'Procurar nesta vista…',
    export: 'Exportar', exportTitle: 'Exportar CSV', exportSoon: 'Exportar · em breve',
    backoffice: '← Backoffice', themeAria: 'Mudar tema', closeAria: 'Fechar',
    kpiReceivable: 'A receber', kpiPaid: 'Pago este mês',
    saving: 'A guardar…', cancel: 'Cancelar', save: 'Guardar', confirm: 'Confirmar', delete: 'Eliminar',
    loading: 'A carregar…', loadError: 'Erro ao carregar',
    login: { eyebrow: p => `thebots.lab / ${p.tenant}`, title: 'Entrar no CRM', desc: 'Use a password de operador para abrir este painel de gestão.', password: 'Password', submit: 'Entrar', invalid: 'Login inválido', crumb: 'Login' },
    invalidTenantTitle: 'Tenant inválido', invalidTenantDesc: 'Volte ao backoffice e abra um CRM válido.',
    titleSuffix: 'Painel de Gestão',
    pdfPending: 'pendente',
    errorPdf: p => `Erro PDF: ${p.msg}`,
    error: p => `Erro: ${p.msg}`,
    quoteStatus: { PENDENTE: 'Pendente', SENT: 'Enviado', ACEITO: 'Aceito' },
    invoiceStatus: { PENDING: 'Pendente', PAID: 'Paga', OVERDUE: 'Vencida', CANCELLED: 'Cancelada' },
    tabs: {
      clientes: { title: 'Clientes', desc: 'Diretório de clientes da empresa.', newLabel: 'Novo cliente' },
      orcamentos: { title: 'Orçamentos', desc: 'Propostas comerciais emitidas.', newLabel: 'Novo orçamento' },
      faturas: { title: 'Faturas', desc: 'Faturas emitidas e respetivo estado.', newLabel: 'Nova fatura' },
      items: { title: 'Items Padrão', desc: 'Catálogo de serviços e materiais para orçamentos e faturas.', newLabel: 'Novo item' },
      bookings: { title: 'Marcações', desc: 'Marcações, serviços e disponibilidade semanal.', newLabel: 'Nova marcação' },
    },
    clients: {
      total: 'Total', new30: 'Novos · 30d', directory: 'Diretório',
      one: 'cliente', many: 'clientes',
      thName: 'Nome', thAddress: 'Morada', thPhone: 'Telefone', thCreated: 'Criado em', thNo: 'Nº Cliente',
      emptyTitle: 'Nenhum cliente encontrado', emptyDesc: 'Ajuste a pesquisa ou crie um novo cliente.',
      formName: 'Nome', formAddress: 'Morada', formPhone: 'Telefone',
      phName: 'Ex: Manuel Costa, Lda.', phAddress: 'Ex: Rua das Flores 12, 1200-001 Lisboa', phPhone: '+351 912 345 678',
      eyebrow: 'Clientes', formTitle: 'Novo cliente', saveLabel: 'Criar cliente',
      validate: 'Preencha nome e telefone', created: p => `Cliente criado · ${p.name}`,
    },
    quotes: {
      total: 'Total', sent: 'Enviados', accepted: 'Aceites', proposals: 'Propostas', filterAll: 'Todos',
      thNumber: 'Número', thClient: 'Cliente', thStatus: 'Status', thValidUntil: 'Válido até', thTotal: 'Total', thPdf: 'PDF',
      emptyTitle: 'Sem orçamentos', emptyDesc: 'Crie o primeiro orçamento com o botão acima.',
      validUntil: 'Válido até', optional: 'opcional', notes: 'Notas', notesPlaceholder: 'Notas internas, condições, prazos…',
      eyebrow: 'Orçamentos', formTitle: 'Novo orçamento', saveLabel: 'Criar orçamento',
      chooseClient: 'Escolha um cliente', addLine: 'Adicione pelo menos uma linha', created: 'Orçamento criado',
    },
    invoices: {
      paid: 'Pago', pending: 'Pendente', overdue: 'Vencido', documents: 'Documentos', filterAll: 'Todos',
      thNumber: 'Número', thClient: 'Cliente', thStatus: 'Status', thDueDate: 'Vencimento', thTotal: 'Total', thPdfActions: 'PDF · Acções',
      emptyTitle: 'Sem faturas', emptyDesc: 'Emita a primeira fatura com o botão acima.',
      markPaid: 'Marcar pago', markedPaid: p => `Fatura ${p.number} marcada como paga`,
      dueDate: 'Vencimento', quoteId: 'ID Orçamento', quoteIdPlaceholder: 'ID do orçamento associado',
      eyebrow: 'Faturas', formTitle: 'Nova fatura', saveLabel: 'Emitir fatura',
      chooseClient: 'Escolha um cliente', enterDueDate: 'Indique a data de vencimento', addLine: 'Adicione pelo menos uma linha', issued: 'Fatura emitida',
    },
    lines: {
      client: 'Cliente', chooseClient: '— Escolher cliente —',
      services: 'Serviços', materials: 'Materiais', label: 'Linhas',
      colDescription: 'Descrição', colQty: 'Qtd', colUnit: 'Unid.', colPrice: 'Preço €',
      addEmpty: '+ Linha vazia', catalogPick: 'Catálogo · Serviços / Materiais', add: 'Adicionar', total: 'Total',
      descPlaceholder: 'Descrição da linha…', unitPlaceholder: 'un', removeLine: 'Remover linha', chooseCatalogItem: 'Escolha um item do catálogo',
    },
    items: {
      services: 'Serviços', materials: 'Materiais', catalogTitle: 'Catálogo', tag: p => `${p.n} itens`,
      thType: 'Tipo', thCategory: 'Categoria', thDescription: 'Descrição', thUnit: 'Unid.', thPrice: 'Preço', thActions: 'Acções',
      emptyTitle: 'Catálogo vazio', emptyDesc: 'Adicione serviços ou materiais para reutilizar em orçamentos.',
      pillService: 'SERVIÇO', pillMaterial: 'MATERIAL', editTitle: 'Editar', deleteTitle: 'Eliminar',
      idLabel: 'ID · slug', typeLabel: 'Tipo', service: 'Serviço', material: 'Material',
      categoryLabel: 'Categoria', descLabel: 'Descrição', unitLabel: 'Unidade', priceLabel: 'Preço (EUR)',
      phId: 'ex: srv-pintura-interior', phCategory: 'Ex: Pintura, Estruturais, Mão-de-obra…', phDesc: 'Descrição visível em orçamentos', phUnit: 'm², h, un, rl…',
      editingHint: p => `A editar ${p.id} — alterações aplicam-se a novos orçamentos.`,
      eyebrow: 'Items Padrão', newTitle: 'Novo item de catálogo', editTitleFull: p => `Editar · ${p.id}`,
      saveChanges: 'Guardar alterações', createItem: 'Criar item',
      fillRequired: 'Preencha todos os campos obrigatórios', updated: p => `Item actualizado · ${p.id}`, created: p => `Item criado · ${p.id}`,
      confirmTitle: 'Eliminar item do catálogo?', confirmBody: p => `"${p.desc}" será removido. Orçamentos já emitidos não serão afectados.`,
      confirmOk: 'Eliminar item', deleted: p => `Item eliminado · ${p.id}`,
    },
  },

  backoffice: {
    login: { eyebrow: 'thebots.lab / platform', title: 'Backoffice', desc: 'Acesso de operador para gerir bots, tenants e equipas.', password: 'Password', submit: 'Entrar', invalid: 'Login inválido' },
    cancel: 'Cancelar', save: 'Guardar', confirm: 'Confirmar', delete: 'Eliminar', loadError: 'Erro ao carregar',
    error: p => `Erro: ${p.msg}`,
    kpiActive: 'Activos', kpiMessages: 'Mensagens', searchPlaceholder: 'Procurar tenant…', themeAria: 'Mudar tema',
    logout: 'Sair', crumbRoot: 'Platform', drawerEyebrow: 'Tenant', brandSub: 'Platform · Tenants', closeAria: 'Fechar',
    heroTitle: 'Tenants', heroDesc: 'Bots/clientes configurados nesta plataforma.',
    botsTitle: 'Bots',
    thName: 'Nome', thSlug: 'Slug', thChannels: 'Channels', thStatus: 'Status', thMsgs: 'Msgs', thLastActivity: 'Última actividade', thActions: 'Acções',
    emptyTenants: 'Nenhum tenant encontrado',
    openDashboard: 'Open Dashboard', users: 'Users', edit: 'Edit', suspend: 'Suspend', activate: 'Activate', reload: 'Reload',
    pipelineReloaded: 'Pipeline recarregada',
    noToken: 'no token', token: 'token',
    usersTitle: p => `Dashboard users · ${p.slug}`,
    thEmail: 'Email', thRole: 'Role',
    noUsers: 'Sem utilizadores', disable: 'Disable',
    emailLabel: 'Email', tempPassword: 'Password temporária', roleLabel: 'Role',
    createUser: 'Criar utilizador', emailPasswordRequired: 'Email e password obrigatórios', userCreated: 'Utilizador criado',
    userDisabled: 'Utilizador desactivado', userActivated: 'Utilizador activado',
    tenantNameLabel: 'Nome', tenantSlugLabel: 'Slug', languageLabel: 'Idioma',
    modelOverride: 'Model override', modelPlaceholder: 'blank = default',
    ratePerHour: 'Rate / hour', ratePerDay: 'Rate / day',
    modulesLabel: 'Módulos', modulesHint: 'Os módulos principais permanecem activos. Seleccione os módulos opcionais a que este tenant pode aceder.',
    channelsLabel: 'Channels', connectWhatsApp: 'Connect WhatsApp', connectInstagram: 'Connect Instagram', addChannel: '+ Add channel',
    colPlatform: 'Platform', colExternalId: 'External ID', colAccessToken: 'Access token',
    channelsHint: 'Instagram token is required when adding a channel. In edit, leave token blank to keep the existing one.',
    chExternalPlaceholder: 'phone_number_id or IG account id', chTokenUnchanged: 'unchanged', chTokenPlaceholder: 'access token', removeChannel: 'Remove channel',
    editTenant: p => `Editar · ${p.slug}`, newTenant: 'Novo bot/cliente', saveChanges: 'Guardar alterações', createTenant: 'Criar tenant',
    nameRequired: 'Nome obrigatório', addOneChannel: 'Adicione pelo menos um channel', igNeedsToken: 'Instagram precisa de Page access token',
    tenantUpdated: 'Tenant actualizado', botCreated: 'Bot criado. Liga os canais à app Meta e aponta o webhook.',
    suspendTitle: 'Suspender tenant?', activateTitle: 'Activar tenant?', tenantLine: p => `Tenant ${p.slug}`,
    deleteTitle: 'Eliminar tenant?', deleteBody: p => `${p.slug} ficará marcado como DELETED. Dados existentes não serão apagados.`,
    igSessionExpired: 'Sessão expirada', igNotConfigured: 'Instagram OAuth não configurado (IG_APP_ID)',
    igAllowPopups: 'Permite popups para ligar o Instagram', igConnected: 'Instagram ligado ✓', igFailed: p => `Instagram falhou: ${p.reason || 'erro'}`,
    waNotConfigured: 'WhatsApp Embedded Signup não configurado', waOpenPopup: 'Abre o popup Meta para ligar o WhatsApp', waConnected: 'WhatsApp ligado',
    waCancelled: 'Ligação WhatsApp cancelada', waMissingCode: 'Meta não devolveu o código de autorização',
    waTimeout: 'Tempo esgotado à espera do Embedded Signup', waSdkFailed: 'Não foi possível carregar o Facebook SDK', waFailed: p => `WhatsApp falhou: ${p.msg}`,
    platformSettings: {
      nav: 'Definições da plataforma',
      title: 'Definições da plataforma',
      desc: 'Overrides em tempo de execução guardados no MongoDB. Segredos ficam mascarados; revelação a pedido. URI Mongo e porta ficam só no .env.',
      save: 'Guardar overrides',
      reload: 'Recarregar do Mongo',
      saved: 'Definições guardadas',
      reloaded: 'Definições recarregadas',
      reveal: 'Revelar',
      hide: 'Ocultar',
      clear: 'Limpar override',
      secretBadge: 'segredo',
      sourceEnv: 'do .env',
      sourceOverride: 'override Mongo',
      updatedAt: p => `Actualizado ${p.at}`,
      neverUpdated: 'Ainda sem overrides guardados',
      passwordHint: 'Introduz uma password em texto (é hasheada ao guardar) ou cola um hash bcrypt.',
      empty: 'Sem definições disponíveis',
      categories: {
        whatsapp: 'WhatsApp',
        instagram: 'Instagram',
        openrouter: 'OpenRouter',
        ratelimit: 'Rate limits',
        pdf: 'Armazenamento PDF',
        admin: 'Auth admin',
      },
    },
  },
};
