/* English UI catalog. Registered into window.__I18N_CATALOGS['en'].
   Namespaces: common (shared), app (tenant dashboard), admin (CRM), backoffice (super-admin). */
window.__I18N_CATALOGS = window.__I18N_CATALOGS || {};
window.__I18N_CATALOGS['en'] = {
  common: {
    nav: {
      overview: 'Home', conversations: 'Conversations', contacts: 'Contacts',
      clients: 'Clients', services: 'Services', quotes: 'Quotes', invoices: 'Invoices', financeiro: 'Finances', suppliers: 'Suppliers', employees: 'Employees', payments: 'Payments', catalog: 'Catalog',
      persona: 'Persona', settings: 'Settings', 'ai-assistant': 'AI Assistant', bookings: 'Bookings', instagram: 'Instagram',
      groupInbox: 'Inbox', groupBusiness: 'Business', groupBot: 'Bot', groupSetup: 'Setup',
    },
    lang: {
      title: 'Language', desc: 'Language used across this dashboard.', label: 'Language',
      saved: 'Language updated ✓', saveFailed: 'Could not update language',
    },
    menuOpenAria: 'Open menu',
    menuCloseAria: 'Close menu',
    themeToLight: 'Switch to light theme',
    themeToDark: 'Switch to dark theme',
    layoutToMinimal: 'Switch to minimal layout',
    layoutToClassic: 'Switch to classic layout',
  },

  app: {
    settingsDesc: 'Connected channels and bot configuration.',
    channelsTitle: 'Channels',
    channelsDesc: 'Accounts where the assistant replies to your customers.',
    colChannel: 'Channel', colAccount: 'Account', colStatus: 'Status', colActions: 'Actions',
    connected: 'Connected', notConnected: 'Not connected',
    igConnect: 'Connect Instagram', igReconnect: 'Reconnect Instagram', igDisconnect: 'Disconnect',
    waConnect: 'Connect WhatsApp', waReconnect: 'Reconnect WhatsApp',
    channelsHint: 'WhatsApp and Instagram open a Meta window to authorize your business account. Instagram must be Business or Creator.',
    igHint: 'Connecting Instagram opens a Meta window to authorize your professional account. The account must be Business or Creator.',
    moreSettingsTitle: 'More settings coming soon',
    moreSettingsDesc: 'Team members are managed in the backoffice for now.',
    docTemplateTitle: 'Quote & invoice template',
    docTemplateDesc: 'Design the page used for quote and invoice PDFs. Drag and resize the boxes, then save.',
    docCompanyName: 'Company name', docTagline: 'Tagline', docTaglinePh: 'e.g. Construction & management',
    docTaxId: 'Tax ID', docTaxIdPh: 'NIF / VAT', docEmail: 'Email', docPhone: 'Phone', docAddress: 'Address',
    docQuoteTitle: 'Quote document title', docInvoiceTitle: 'Invoice document title',
    docQuotePayment: 'Default payment terms (quotes)', docInvoicePayment: 'Default payment terms (invoices)',
    docTerms: 'Terms & conditions', docFooter: 'Footer',
    docLogo: 'Logo', docLogoNone: 'No logo uploaded', docLogoLoading: 'Loading logo…',
    docLogoUpload: 'Upload logo', docLogoRemove: 'Remove logo',
    docLogoHint: 'PNG, JPG or WebP, max 2 MB. Shown on quote and invoice PDFs.',
    docLogoUploaded: 'Logo uploaded', docLogoRemoved: 'Logo removed', docLogoUploadFailed: 'Could not update logo',
    docTemplateSave: 'Save template', docTemplateSaved: 'Document template saved',
    docTemplateSaveFailed: 'Could not save document template',
    docTplDragHint: 'Drag a box to move it. Resize from the handles. Click a box to edit its content.',
    docTplOverlap: 'These boxes overlap, so their text will print on top of each other. Move them apart.',
    docTplPreviewQuote: 'Quote', docTplPreviewInvoice: 'Invoice',
    docTplResetLayout: 'Reset layout', docTplLayoutReset: 'Layout reset to the default page',
    docTplLayers: 'Blocks', docTplInspector: 'Selected block',
    docTplEmptySelect: 'Click a box on the page to edit it.',
    docTplAccent: 'Accent color', docTplDecor: 'Decorative waves',
    docTplShow: 'Show', docTplHide: 'Hide',
    docTplPos: 'Position', docTplSize: 'Size',
    docTplSampleHint: 'Preview uses sample data. Real quotes and invoices fill this from the CRM.',
    docTplPageLabel: 'A4 · 210 × 297 mm',
    docTplDirty: 'Unsaved changes',
    docTplColService: 'Service', docTplColDesc: 'Description', docTplColValue: 'Amount',
    docTplColQty: 'Qty', docTplColPrice: 'Price',
    docTplClientLabel: 'Client', docTplPaymentLabel: 'Payment method', docTplTermsLabel: 'Terms and conditions',
    docTplDateLabel: 'Date', docTplTotalLabel: 'Total',
    docTplSampleClient: 'Sample client', docTplSamplePhone: '+351 210 000 000', docTplSampleClientRef: 'CLT-001  ·  NIF 123456789',
    docTplSampleItem1: 'Interior painting', docTplSampleItem1Desc: 'Preparation and two coats',
    docTplSampleItem2: 'Exterior render', docTplSampleItem2Desc: 'Facade repair and finish',
    docTplSampleQuoteNo: 'Q-1042', docTplSampleInvoiceNo: 'INV-1042',
    docTplBlockLogo: 'Logo', docTplBlockContact: 'Contact', docTplBlockCompany: 'Company',
    docTplBlockTitle: 'Document title', docTplBlockClient: 'Client', docTplBlockItems: 'Line items',
    docTplBlockTotals: 'Total', docTplBlockPayment: 'Payment terms', docTplBlockTerms: 'Terms',
    docTplBlockFooter: 'Footer',
    docTplHideAria: 'Toggle visibility',
    docTplColorAria: 'Accent color',
    docTplTemplates: 'Templates',
    docTplTemplatesTitle: 'Document templates',
    docTplTemplatesDesc: 'Start from a design, or reuse one you saved. Applying a template keeps your company details.',
    docTplTemplatesGallery: 'Starter designs', docTplTemplatesYours: 'Your templates',
    docTplTemplatesEmpty: 'No saved templates yet. Save your current design below.',
    docTplPresetBuiltIn: 'Built-in',
    docTplPresetApply: 'Apply', docTplPresetApplied: 'Template applied',
    docTplPresetApplyFailed: 'Could not apply template',
    docTplPresetDelete: 'Delete', docTplPresetDeleted: 'Template deleted',
    docTplPresetDeleteFailed: 'Could not delete template',
    docTplPresetDeleteConfirmTitle: 'Delete this template?',
    docTplPresetDeleteConfirmBody: 'This cannot be undone.',
    docTplPresetSaveLabel: 'Save current design as a template',
    docTplPresetNamePh: 'e.g. Summer campaign',
    docTplPresetSaveBtn: 'Save template',
    docTplPresetSaved: 'Template saved', docTplPresetSaveFailed: 'Could not save template',
    docTplPresetNameRequired: 'Give the template a name',
    docTplPresetClassic: 'Classic', docTplPresetModern: 'Modern', docTplPresetMinimal: 'Minimal',
    docTplPresetClear: 'Clear', docTplPresetStatement: 'Statement', docTplPresetMargin: 'Margin',
    docTplPresetClassicDesc: 'Original pill page with letter-spaced labels.',
    docTplPresetModernDesc: 'Same pill page, logo on the left, blue accent.',
    docTplPresetMinimalDesc: 'Same pill page, compact header, no waves.',
    docTplPresetClearDesc: 'Readable invoice: company letterhead, qty and price columns, no pills.',
    docTplPresetStatementDesc: 'Document card on the right, client in a box, same clear table.',
    docTplPresetMarginDesc: 'Accent band on the left edge, same clear table.',
    sessionExpired: 'Session expired',
    igUnavailable: 'Instagram connection is not available',
    igAllowPopups: 'Allow popups to connect Instagram',
    igConnected: 'Instagram connected ✓',
    igFailed: reason => `Could not connect Instagram${reason ? ` (${reason})` : ''}`,
    igDisconnectConfirmTitle: 'Disconnect Instagram?',
    igDisconnectConfirmBody: p => `${p.account} will stop receiving automatic replies. You can reconnect any time.`,
    igDisconnectAction: 'Disconnect', igDisconnected: 'Instagram disconnected', igDisconnectFailed: 'Could not disconnect Instagram',
    waNotConfigured: 'WhatsApp connection is not available',
    waOpenPopup: 'Open the Meta popup to connect WhatsApp',
    waConnected: 'WhatsApp connected ✓',
    waCancelled: 'WhatsApp connection cancelled',
    waMissingCode: 'Meta did not return the authorization code',
    waTimeout: 'Timed out waiting for WhatsApp signup',
    waSdkFailed: 'Could not load the Facebook SDK',
    waFailed: p => `Could not connect WhatsApp${p?.msg ? ` (${p.msg})` : ''}`,
    webTitle: 'Website widget',
    webDesc: 'Add the chat assistant to your website. Paste this snippet just before the closing </body> tag.',
    webGenerate: 'Generate widget code',
    webRegenerate: 'Widget active',
    webCopy: 'Copy snippet',
    webCopied: 'Snippet copied ✓',
    webGenerated: 'Widget code generated ✓',
    webGenerateFailed: 'Could not generate widget code',
    webOriginsLabel: 'Allowed website domains (optional)',
    webOriginsHint: 'One origin per line, e.g. https://www.yoursite.com. Leave empty to allow any site (less secure).',
    webOriginsSave: 'Save domains',
    webOriginsSaved: 'Domains saved ✓',
    webRowName: 'Website',
    quickCreateSoon: 'Quick create for this module is coming soon.',
    clientFormTitle: 'New client',
    clientFormName: 'Name', clientFormPhone: 'Phone', clientFormAddress: 'Address',
    clientPhName: 'Client name', clientPhPhone: '+351…', clientPhAddress: 'Street, city',
    clientSave: 'Create client',
    clientValidate: 'Enter name and phone',
    clientCreated: p => `Client created · ${p.name}`,
    clientCreateFailed: 'Could not create client',
    optional: 'optional',
    catalogFormTitle: 'New item', catalogSave: 'Create item',
    catalogId: 'ID', catalogType: 'Type', catalogService: 'Service', catalogMaterial: 'Material',
    catalogCategory: 'Category', catalogDesc: 'Description', catalogUnit: 'Unit', catalogPrice: 'Price (€)',
    catalogPhId: 'srv-…', catalogPhCategory: 'E.g. Facades', catalogPhDesc: 'What this item covers', catalogPhUnit: 'm2, unit, service…',
    catalogValidate: 'Fill all required fields', catalogCreated: p => `Item created · ${p.id}`, catalogCreateFailed: 'Could not create item',
    quoteFormTitle: 'New quote', quoteSave: 'Create quote',
    quoteValidUntil: 'Valid until', quoteNotes: 'Notes', quoteNotesPh: 'Optional notes shown on the PDF',
    quoteChooseClient: 'Choose a client', quoteAddLine: 'Add at least one line', quoteCreated: 'Quote created', quoteCreateFailed: 'Could not create quote',
    invoiceFormTitle: 'New invoice', invoiceSave: 'Issue invoice',
    invoiceDueDate: 'Due date', invoiceQuoteId: 'Quote ID', invoiceQuoteIdPh: 'Link an existing quote (optional)',
    invoiceChooseClient: 'Choose a client', invoiceEnterDueDate: 'Enter a due date', invoiceAddLine: 'Add at least one line', invoiceCreated: 'Invoice issued', invoiceCreateFailed: 'Could not issue invoice',
    lineClient: 'Client', lineChooseClient: 'Select…', lineItemsLabel: 'Items',
    lineColDesc: 'Description', lineColQty: 'Qty', lineColUnit: 'Unit', lineColPrice: 'Price',
    lineAddEmpty: 'Add line', lineCatalogPick: 'From catalog…', lineAdd: 'Add', lineTotal: 'Total',
    lineDescPh: 'Description', lineUnitPh: 'un', lineRemove: 'Remove line', lineChooseCatalog: 'Pick a catalog item',
    loginEyebrow: 'thebots.lab / tenant',
    loginTitle: 'Sign in to the dashboard',
    loginDesc: 'Access your chatbot data, conversations and CRM.',
    loginEmail: 'Email', loginPassword: 'Password', loginSubmit: 'Sign in', loginInvalid: 'Invalid login',
    loginGoogle: 'Continue with Google', loginOr: 'or sign in with your email and password',
    loginGoogleCancelled: 'Sign-in cancelled', loginGoogleFailed: 'Could not sign in with Google',
    loginGooglePopupBlocked: 'Allow pop-ups for this site to sign in with Google',
    loginGoogleNoAccount: "This Google account isn't linked to a user yet. Sign in with your email and password, then link it under your account.",
    loginGoogleOtherAccount: 'Your user is linked to a different Google account. Sign in with that one.',
    loginInactive: 'This account is inactive',
    accountAria: 'Your account', accountTitle: 'Account', accountLoadFailed: 'Could not load your account',
    accountRoleTENANT_ADMIN: 'Administrator', accountRoleTENANT_MEMBER: 'Member',
    accountMethods: 'How you sign in', accountGoogle: 'Google', accountPassword: 'Password',
    accountLinked: 'Linked', accountNotLinked: 'Not linked', accountOn: 'On', accountOff: 'Off',
    accountGoogleOffDetail: 'One click, no password to remember',
    accountGoogleUnavailable: "Google sign-in isn't available right now",
    accountPasswordOnDetail: 'Your email and password',
    accountPasswordOffDetail: 'Off: you sign in with Google only',
    accountHintLink: 'Link your Google account to sign in with one click. You can then switch your password off so only Google gets you in.',
    accountHintBoth: 'You can sign in with Google or with your password. Switch the password off to sign in with Google only.',
    accountHintGoogleOnly: 'Only your Google account gets you in. To sign in with a password again, set one.',
    accountGoogleTitle: 'Google account', accountGoogleEmail: 'Linked account',
    accountGoogleLinkIntro: 'Confirm your current password, then choose your Google account.',
    accountCurrentPassword: 'Current password',
    accountGoogleLinked: 'Google account linked',
    accountGoogleUnlinkIntro: 'After unlinking, you sign in with your email and password only.',
    accountGoogleUnlinkAction: 'Unlink Google account', accountGoogleUnlinked: 'Google account unlinked',
    accountGoogleOnlyKeep: "It's your only way in. To unlink it, set a password first.",
    accountSetPasswordAction: 'Set a password',
    accountNewPassword: 'New password', accountNewPasswordHint: 'At least 8 characters', accountRepeatPassword: 'Repeat the new password',
    accountSavePassword: 'Save password', accountPasswordChanged: 'Password changed',
    accountGoogleOnlyTitle: 'Sign in with Google only',
    accountGoogleOnlyIntro: p => `Switch your password off so only your Google account (${p.email}) gets you in. You confirm with Google first, and you can set a password again at any time.`,
    accountGoogleOnlyNeedsLink: 'Link a Google account first to sign in with Google only.',
    accountGoogleOnlyAction: 'Confirm with Google and switch off', accountLinkGoogleAction: 'Link Google account',
    accountPasswordOff: 'Password switched off. You sign in with Google only.',
    accountSetIntro: p => `You sign in with Google only (${p.email}). Set a password to also sign in with your email.`,
    accountSetAction: 'Confirm with Google and save', accountPasswordSet: 'Password set',
    accountFailed: 'Could not save the change',
    accountErr_wrong_password: 'Your current password is wrong',
    accountErr_mismatch: "The new passwords don't match",
    accountErr_password_too_short: 'The new password needs at least 8 characters',
    accountErr_password_too_long: 'The new password is too long',
    accountErr_google_in_use: 'That Google account is already linked to another user',
    accountErr_other_google_account: 'Choose the Google account linked to your user',
    accountErr_already_linked: 'A Google account is already linked',
    accountErr_password_required: 'Set a password first',
    accountErr_google_required: 'Link a Google account first',
    newPrefix: 'New',
    dashboardWord: 'Dashboard', searchPlaceholder: 'Search…', logout: 'Log out', themeAria: 'Toggle theme',
    closeAria: 'Close', cancel: 'Cancel', confirm: 'Confirm',
    noData: 'No data',
    contactStatusACTIVE: 'Active', contactStatusBLOCKED: 'Blocked', contactStatusRATE_LIMITED: 'Rate limited',
    conversationStateACTIVE: 'Open', conversationStateARCHIVED: 'Archived',
    markPaidConfirmTitle: 'Mark this invoice as paid?',
    markPaidConfirmBody: p => `Invoice ${p.number} will be marked paid.`,
    overviewDesc: 'The pulse of the business — money, people, and what needs you today.',
    needsYou: 'Needs you', needsYouEmpty: 'You are caught up', needsYouEmptyDesc: 'No waiting chats, overdue invoices, pending bookings or Instagram comments.',
    setupTitle: 'Finish setup', setupDone: 'Setup looks complete.',
    todayTitle: 'Today',
    waitingChat: 'Waiting for a reply', overdueInvoice: 'Overdue invoice', pendingBooking: 'Pending booking', instagramWaitingComment: 'Instagram comment',
    dueSoonInvoice: 'Invoice due soon', overduePayment: 'Overdue payment', dueSoonPayment: 'Payment due soon', quoteExpiring: 'Quote expiring', assistantAction: p => `${p.n} assistant ${p.n === 1 ? 'action' : 'actions'} waiting for approval`,
    overdueInvoiceN: p => `${p.n} overdue ${p.n === 1 ? 'invoice' : 'invoices'}`, overduePaymentN: p => `${p.n} overdue ${p.n === 1 ? 'payment' : 'payments'}`,
    teachBot: 'Teach the bot', setupWidget: 'Add the website widget',
    openModule: 'Open',
    healthOk: 'On track', healthWatch: 'Needs attention', healthUrgent: 'Urgent',
    pulseOk: 'Nothing waiting — the shop is quiet.',
    pulseNeeds: p => `${p.n} ${p.n === 1 ? 'item needs' : 'items need'} you`,
    pulseOutstanding: p => `${p.amount} to collect`,
    pulseBookingsToday: p => `${p.n} ${p.n === 1 ? 'booking' : 'bookings'} today`,
    hl_collected_month: 'Received this month', hl_outstanding: 'To collect', hl_overdue: 'Overdue',
    hl_pipeline_open: 'Open quotes', hl_win_rate: 'Win rate', hl_waiting: 'Waiting for a reply',
    hl_messages_today: 'Messages today', hl_bookings_today: 'Bookings today', hl_clients: 'Clients',
    hl_contacts: 'Contacts', hl_instagram_unreplied: 'Unreplied comments',
    vsLastMonth: 'vs last month', vsLastWeek: 'vs last week',
    deltaUp: p => `↑ ${p.pct}% ${p.vs}`, deltaDown: p => `↓ ${p.pct}% ${p.vs}`, deltaFlat: p => `= ${p.vs}`,
    snapFinance: 'Finances', snapPipeline: 'Pipeline', snapCustomers: 'Clients', snapInbox: 'Inbox',
    snapCalendar: 'This week', snapSocial: 'Instagram', snapCatalog: 'Catalog', snapServices: 'Services', snapSuppliers: 'Suppliers', snapEmployees: 'Employees', snapAssistant: 'Assistant',
    cashPaidCount: 'Payments this month',
    financeGained: 'Received this month', financeSpent: 'Spent this month', financeReceivable: 'To collect', financePayable: 'To pay',
    pipelineDrafts: 'Drafts', pipelineSent: 'Sent', pipelineAccepted: 'Accepted', pipelineExpiring: 'Expiring this week',
    pipelineAcceptedMonth: 'Accepted this month',
    customersNewMonth: 'New this month', customersNewLastMonth: 'New last month',
    inboxWeek: 'Messages this week', inboxPaused: 'Auto-reply paused', inboxNewContacts: 'New contacts · 7d',
    calendarPending: 'To confirm', calendarNext: 'Next up', calendarNone: 'Nothing booked',
    catalogItems: 'Items', servicesOpen: 'Open to invoice', servicesInvoicedMonth: 'Invoiced this month',
    suppliersNewMonth: 'New this month', suppliersNewLastMonth: 'New last month',
    employeesNewMonth: 'New this month', employeesNewLastMonth: 'New last month',
    assistantPending: 'Actions to approve',
    overviewEmptyTitle: 'This workspace is ready',
    overviewEmptyDesc: 'Turn on modules in the backoffice to see money, inbox and calendar here.',
    customizeHome: 'Choose cards',
    settingsHome: 'Home',
    homeLayoutTitle: 'Home cards',
    homeLayoutDesc: 'Pick which snapshots appear on Home. Only modules enabled for this workspace are listed.',
    homeLayoutSections: 'At a glance',
    homeLayoutSnapshots: 'Dashboards',
    homeLayoutShown: 'Shown',
    homeLayoutHidden: 'Hidden',
    homeLayoutSaved: 'Home layout saved',
    homeLayoutSaveFailed: 'Could not save Home layout',
    homeCard_highlights: 'Highlights',
    homeCard_highlightsDesc: 'The numbers at the top of Home',
    homeCard_pulse: 'Health pulse',
    homeCard_pulseDesc: 'One-line status of what needs you today',
    homeCard_attentionDesc: 'Overdue invoices, overdue payments, waiting chats, pending bookings',
    homeCard_setupDesc: 'Connect channels and teach the bot',
    homeCard_calendar: 'Calendar',
    homeCard_financeDesc: 'How much came in vs. went out',
    homeCard_pipelineDesc: 'Open quotes and win rate',
    homeCard_customersDesc: 'Client count and new this month',
    homeCard_inboxDesc: 'Waiting chats and messages today',
    homeCard_calendarDesc: 'Bookings today and to confirm',
    homeCard_socialDesc: 'Unreplied Instagram comments',
    homeCard_catalogDesc: 'Items in your catalog',
    homeCard_servicesDesc: 'Unbilled work attached to clients',
    homeCard_suppliers: 'Suppliers',
    homeCard_suppliersDesc: 'Vendor directory',
    homeCard_employees: 'Employees',
    homeCard_employeesDesc: 'People on the team',
    homeCard_payments: 'Payments',
    homeCard_assistantDesc: 'Actions waiting for approval',
    greetingMorning: 'Good morning', greetingAfternoon: 'Good afternoon', greetingEvening: 'Good evening',
    dashKpisAria: 'Key numbers', openModuleAria: 'Open {name}',
    kpiNet: 'Net this month', kpiOverdue: '{amount} overdue', kpiDueSoon: p => `${p.n} due this week`,
    kpiInOut: '{in} in · {out} out', kpiQuotes: p => `${p.n} ${p.n === 1 ? 'quote' : 'quotes'} · ${p.pct}% win rate`,
    kpiMessagesToday: p => `${p.n} ${p.n === 1 ? 'message' : 'messages'} today`, kpiThisWeek: '{n} this week',
    kpiNewThisMonth: '+{n} this month', kpiNewThisWeek: '+{n} this week',
    dashCashFlow: 'Cash flow', dashLast6Months: 'Last 6 months', dashMoneyIn: 'Money in', dashMoneyOut: 'Money out',
    dashAvgIn: 'Avg. in / month', dashAvgOut: 'Avg. out / month', dashIssuedMonth: 'Invoiced this month',
    dashCashEmpty: 'No payments recorded in the last 6 months',
    dashAgendaEmpty: 'Nothing booked today', dashNow: 'Now',
    dashReceivables: 'Receivables', dashPayables: 'Payables', dashOutstanding: 'Outstanding',
    agingCurrent: 'Not due yet', agingWeek: '1–7 days late', agingMonth: '8–30 days late', agingOld: '30+ days late',
    dashTopOverdue: 'Largest overdue', dashDueSoon: 'Due this week',
    dashOpenQuotesN: p => `${p.n} open ${p.n === 1 ? 'quote' : 'quotes'}`,
    dashWeekChange: 'Change vs last week', dashLast14Days: 'Last 14 days',
    dashTopClients: 'Top clients', dashLast12Months: 'Last 12 months',
    dashInvoicesN: p => `${p.n} ${p.n === 1 ? 'invoice' : 'invoices'}`, dashPaidPct: '{pct}% paid',
    dashTopClientsEmpty: 'No invoices in the last 12 months',
    dashRecent: 'Recent activity', dashRecentEmpty: 'Nothing new yet',
    recent_invoice_paid: 'Invoice {number} paid', recent_invoice_issued: 'Invoice {number} issued',
    recent_payment_paid: 'Payment {number} made', recent_quote_accepted: 'Quote {number} accepted',
    recent_quote_created: 'Quote {number} created', recent_client_created: 'New client', recent_booking_created: 'New booking',
    settingsAppearance: 'Appearance', appearanceLayoutTitle: 'Layout',
    appearanceLayoutHint: 'Saved on this browser. Switch any time from the top bar.',
    layoutClassic: 'Classic', layoutClassicDesc: 'Colorful cards and a roomy Home with big numbers.',
    layoutMinimal: 'Minimal', layoutMinimalDesc: 'Clean, dense CRM view: trends, today’s agenda and receivables at a glance.',
    appearanceThemeTitle: 'Theme', themeLight: 'Light', themeLightDesc: 'Bright surfaces for daytime work.',
    themeDark: 'Dark', themeDarkDesc: 'Low-glare surfaces for dim rooms.',
    appearanceActive: 'Active', appearanceSaved: 'Appearance updated',
    openInbox: 'Open inbox', viewInvoices: 'View invoices', viewBookings: 'View bookings',
    waiting: 'Waiting', noThread: 'Select a conversation', noThreadDesc: 'Pick a customer on the left to read and reply.',
    quoteMarkSent: 'Mark sent', quoteAccept: 'Accept', quoteConvert: 'Convert to invoice',
    quoteConverted: 'Invoice issued from this quote', quoteStatusUpdated: 'Quote updated',
    quoteConvertDue: 'Invoice due date', quoteConvertFailed: 'Could not convert this quote',
    clientUpdated: 'Client updated', clientUpdateFailed: 'Could not update client', clientEdit: 'Edit client',
    clientEyebrow: 'Client', clientEditAction: 'Edit', clientSaveChanges: 'Save changes', clientBackAria: p => `Back to ${p.name}`,
    clientSince: p => `Client since ${p.date}`, clientLastActivity: p => `last activity ${p.when}`,
    clientVisits: p => `${p.n} ${p.n === 1 ? 'visit' : 'visits'}`, clientTaxIdShort: p => `NIF ${p.id}`,
    clientCall: 'Call', clientWhatsApp: 'WhatsApp', clientOpenChat: 'Open chat',
    clientKpiOutstanding: 'Outstanding', clientKpiOverdue: p => `${p.amount} overdue`,
    clientKpiUnpaid: p => `${p.n} unpaid ${p.n === 1 ? 'invoice' : 'invoices'}`, clientKpiNothingDue: 'Nothing due',
    clientKpiNextBooking: 'Next booking', clientKpiNoBooking: 'None scheduled',
    clientKpiUnbilled: 'To invoice', clientKpiServices: p => `${p.n} ${p.n === 1 ? 'service' : 'services'}`,
    clientKpiBilled: 'Billed', clientKpiPaid: p => `${p.amount} paid`,
    clientKpiQuotes: 'In proposal', clientKpiOpenQuotes: p => `${p.n} open ${p.n === 1 ? 'quote' : 'quotes'}`,
    clientAttention: 'Needs attention',
    clientAttnOverdue: p => `${p.number} is overdue`, clientAttnOverdueDetail: p => `was due ${p.when}`,
    clientAttnUnclosed: 'Booking to close', clientAttnPendingBooking: 'Booking to confirm',
    clientAttnUnbilled: p => `${p.n} ${p.n === 1 ? 'service' : 'services'} to invoice`,
    clientAttnQuote: p => `${p.number} awaiting a reply`, clientAttnQuoteDraft: p => `${p.number} not sent yet`,
    clientAttnQuoteExpired: p => `expired ${p.when}`, clientAttnDueSoon: p => `${p.number} due soon`, clientDueWhen: p => `due ${p.when}`,
    clientValidUntil: p => `valid until ${p.date}`, clientCreatedOn: p => `created ${p.date}`, clientIssuedOn: p => `issued ${p.date}`,
    clientTabActivity: 'Activity', clientUpcoming: 'Upcoming', clientPast: 'Past', clientHistory: 'History', clientThDate: 'Date',
    clientKindBooking: 'Booking', clientKindService: 'Service',
    clientEvtQuote: p => `Quote ${p.number}`, clientEvtInvoice: p => `Invoice ${p.number}`,
    clientEvtPaid: p => `Payment received · ${p.number}`, clientEvtChat: 'WhatsApp conversation',
    clientActivityEmpty: 'No activity yet', clientActivityEmptyDesc: 'Bookings, services, quotes and invoices for this client show up here.',
    clientNoBookings: 'No bookings yet', clientNoServices: 'No services yet', clientNoQuotes: 'No quotes yet', clientNoInvoices: 'No invoices yet',
    clientInvoiceOpenWork: p => `Invoice open work · ${p.amount}`, clientInvoiceOpenWorkTitle: 'Invoice open work',
    clientIssueInvoice: p => `Issue invoice · ${p.amount}`,
    clientFormEmail: 'Email', clientFormTaxId: 'Tax ID (NIF)', clientFormNotes: 'Notes',
    clientPhEmail: 'name@example.com', clientPhTaxId: '123456789', clientPhNotes: 'Preferences, access details, anything the team should know',
    clientNotesHint: 'Only your team sees these notes.', clientInvalidEmail: 'Enter a valid email address',
    clientDuplicate: p => `${p.name} (${p.number}) already uses this phone.`, clientOpenExisting: 'Open',
    recordSupplier: 'Supplier', recordEmployee: 'Employee',
    supplierSince: p => `Supplier since ${p.date}`, employeeSince: p => `On the team since ${p.date}`,
    payeePayments: p => `${p.n} ${p.n === 1 ? 'payment' : 'payments'}`, payeeLastPaid: p => `last paid ${p.when}`,
    payeeKpiToPay: 'To pay', payeeKpiUnpaid: p => `${p.n} unpaid`, payeeKpiNothingDue: 'Nothing to pay',
    payeeKpiNextDue: 'Next due', payeeKpiNoneDue: 'Nothing scheduled', payeeKpiPaid: 'Paid',
    payeeAttnOverdue: p => `${p.number} is overdue`, payeeNoPayments: 'No payments yet',
    detailOpenRecordAria: p => `Open ${p.name}`, detailOpenDoc: p => `Open ${p.number}`,
    detailCreated: 'Created', detailIssued: 'Issued', detailInvoice: 'Invoice',
    quoteExpiresWhen: p => `expires ${p.when}`, quoteAlreadyInvoiced: 'This quote already has an invoice',
    clientPhoneTaken: 'Another client already has this phone number.',
    supplierPhoneTaken: 'Another supplier already has this phone number.',
    employeePhoneTaken: 'Someone on the team already has this phone number.',
    settingsChannels: 'Channels', settingsWidget: 'Website', settingsLanguage: 'Language', settingsDocuments: 'Documents',
    widgetPreview: 'Preview', widgetPreviewHi: 'Hi — how can we help?', widgetPreviewLive: 'Updates live',
    widgetContentTitle: 'Conversation', widgetAppearanceTitle: 'Appearance',
    widgetTitleLabel: 'Assistant name', widgetSubtitleLabel: 'Status message', widgetWelcomeLabel: 'Welcome message',
    widgetPlaceholderLabel: 'Input placeholder', widgetLauncherLabel: 'Launcher label', widgetAccentLabel: 'Brand color',
    widgetPositionLabel: 'Position', widgetPositionRight: 'Bottom right', widgetPositionLeft: 'Bottom left',
    widgetThemeLabel: 'Theme', widgetThemeLight: 'Light', widgetThemeDark: 'Dark', widgetThemeAuto: 'Device setting',
    widgetInstallTitle: 'Install on your website', widgetInstallHint: 'The snippet updates as you customize. Copy it and paste it before the closing </body> tag.',
    widgetEmptyTitle: 'Create your website chat', widgetEmptyDesc: 'Generate a secure widget key, then tailor the assistant to your brand and preview it here.',
    widgetDefaultTitle: 'Chat', widgetDefaultSubtitle: 'Typically replies instantly', widgetDefaultWelcome: 'Hi! How can we help?',
    widgetDefaultPlaceholder: 'Type a message…', widgetDefaultLauncher: 'Chat with us',
    personaAdvanced: 'Advanced', personaAdvancedHint: 'Compiled instructions the bot uses. Edit only if you know what you are changing.',
    statMessages24h: 'Messages 24h', statMessages: 'Messages', statContacts: 'Contacts', statConversations: 'Conversations', statQuotes: 'Quotes', statInvoices: 'Invoices',
    contactsDesc: 'End-users who talked to the bot.',
    thName: 'Name', thStatus: 'Status', thLastSeen: 'Last seen', thActions: 'Actions',
    block: 'Block', unblock: 'Unblock',
    conversationsDesc: 'Open a customer conversation and send a live message from a connected account.',
    thState: 'State', thMsgs: 'Msgs', thLast: 'Last',
    threadTitle: 'Conversation', noMessages: 'No messages',
    assetLabel: 'Connected asset', assetHint: 'Select the Page, account, or number used to message customers.',
    unnamedAsset: 'Unnamed account', recipient: 'Recipient', noAssetConversations: 'No conversations for this asset', noMessagingAssets: 'Connect Instagram or WhatsApp to send messages',
    sendingFrom: 'Sending from', sendingTo: 'To', customer: 'Customer', operator: 'Operator',
    messagePlaceholder: 'Write a live message…', sendUnavailable: 'Select the asset that owns this conversation to send a message.',
    webWidgetAsset: 'Website widget', webConversationReadOnly: 'Website conversations are answered live by the bot and are read-only here.',
    messageDelivered: 'Message delivered', messageFailed: 'Message could not be delivered',
    autoReplyOn: 'Auto-reply on', autoReplyPaused: 'Auto-reply paused',
    autoReplyPauseAction: 'Pause auto-reply', autoReplyResumeAction: 'Resume auto-reply',
    autoReplyToggleFailed: 'Could not change auto-reply',
    openChat: 'Open chat',
    clientsDesc: 'CRM · Clients.', thPhone: 'Phone', thAddress: 'Address', thNo: 'No.',
    quotesDesc: 'CRM · Commercial proposals.', thNumber: 'Number', thClient: 'Client', thTotal: 'Total',
    invoicesDesc: 'CRM · Issued invoices.', thDueDate: 'Due date',
    thPdf: 'PDF', thPdfActions: 'PDF · Actions', viewPdf: 'View PDF', pdfPending: 'pending',
    errorPdf: p => `PDF error: ${p.msg}`, loadFailed: 'Could not load this section',
    markPaid: 'Mark paid', markedPaid: p => `Invoice ${p.number} marked as paid`, markPaidFailed: 'Could not mark invoice as paid',
    invoiceFromQuote: p => `From quote ${p.number}`, paidOnLabel: 'Paid on',
    catalogDesc: 'CRM · Standard services and materials.', thType: 'Type', thCategory: 'Category', thDescription: 'Description', thUnit: 'Unit', thPrice: 'Price',
    personaDesc: 'Bot personality — synthesized from notes and files you upload.',
    personaCompiling: 'Synthesizing…', statVersion: 'Version', statTokens: 'Tokens est.', statUpdated: 'Updated',
    testBotTitle: 'Test the bot', clear: 'Clear',
    testBotDesc: 'Chat with the bot using the current persona to test tone and replies. Test messages are not saved and do not create clients, quotes or invoices.',
    chatPlaceholder: 'Type a test message…', send: 'Send',
    chatEmpty: 'Send a message to test the bot persona.', typing: 'typing…', chatError: '⚠️ Error contacting the bot. Please try again.',
    addInfoTitle: 'Add information',
    addInfoDesc: 'Write a note or upload a file (PDF, TXT, MD). It is synthesized into the instructions file below.',
    noteLabel: 'Note', notePlaceholder: 'E.g.: We are a dental clinic in Lisbon. Warm tone, formal address...', addNote: 'Add note',
    fileLabel: 'File', fileHint: 'PDF, TXT or Markdown. The text is extracted and synthesized.',
    sourcesTitle: 'Sources', sourcesDesc: 'Raw material feeding the synthesis.', rebuildAll: 'Recompile all',
    sourceSynced: 'synced', sourcePending: 'pending', remove: 'Remove',
    thSource: 'Source', thCreated: 'Created',
    noSourcesTitle: 'No sources yet', noSourcesDesc: 'Add a note or file above.',
    compiledTitle: 'Compiled instructions file',
    compiledDesc: 'Synthesis result. You can edit it manually; the next synthesis will review it.',
    compiledPlaceholder: 'Still empty — add information above to give the bot personality.',
    saveManual: 'Save manual edit',
    personaSaved: 'Persona saved', noteAdded: 'Note added — synthesizing', fileUploaded: 'File uploaded — synthesizing', rebuildStarted: 'Recompilation started', uploadFailed: 'Upload failed',
    assistantDesc: 'Ask questions about your business data and complete dashboard tasks with your approval.',
    assistantNewThread: 'New conversation', assistantNoThreads: 'No conversations yet',
    assistantEmpty: 'Start by asking about clients, catalog items, quotes, or invoices.', assistantPlaceholder: 'Ask the assistant…',
    assistantError: 'The assistant could not answer. Please try again.', assistantActionError: 'The action could not be updated.',
    assistantProposedAction: 'Proposed action', assistantConfirm: 'Confirm action', assistantCancel: 'Cancel',
    assistantStatusPENDING: 'Awaiting approval', assistantStatusEXECUTING: 'Running', assistantStatusCONFIRMED: 'Completed', assistantStatusFAILED: 'Failed', assistantStatusCANCELLED: 'Cancelled',
    assistantCreateClient: p => `Create client ${p.name}`, assistantCreateQuote: 'Create quote', assistantUpdateQuote: p => `Update quote ${p.id}`,
    assistantCreateInvoice: 'Create invoice', assistantMarkPaid: p => `Mark invoice ${p.id} as paid`, assistantChangeData: 'Change dashboard data',
    assistantClientRef: p => `Client: ${p.id}`, assistantQuoteRef: p => `Quote: ${p.id}`, assistantInvoiceRef: p => `Invoice: ${p.id}`,
    assistantValidUntil: p => `Valid until: ${p.date}`, assistantDueDate: p => `Due date: ${p.date}`, assistantNewStatus: p => `New status: ${p.status}`,
    assistantDownloadPdf: p => p.number ? `Download ${p.number} PDF` : 'Download PDF',
    bookingsDesc: 'Appointments for your catalog services, linked to clients and billed when done.',
    bookingsWeek: 'Week', bookingsAgenda: 'Agenda', bookingsAgendaTitle: p => `Next ${p.days} days`,
    bookingsPrev: 'Previous week', bookingsNext: 'Next week', bookingsToday: 'This week',
    bookingsStatToday: 'Today', bookingsStatWeek: 'Week', bookingsStatPending: 'To confirm', bookingsStatValue: 'Week value',
    bookingsNew: 'New booking', bookingsEdit: 'Edit booking', bookingsSave: 'Save booking', bookingsNewForClient: 'New booking',
    bookingsContactName: 'Contact name', bookingsContactPhone: 'Phone', bookingsService: 'Service',
    bookingsStart: 'Start', bookingsNotes: 'Notes', bookingsStatus: 'Status', bookingsSource: 'Source', bookingsOptional: 'optional',
    bookingsDate: 'Date', bookingsTime: 'Time', bookingsDurationShort: 'Duration (min)', bookingsPrice: 'Price €',
    bookingsFreeTimes: 'Free times', bookingsNoFreeTimes: 'No free times on this day', bookingsPickServiceFirst: 'Pick a service and a date to see free times',
    bookingsOutsideHours: 'Outside opening hours — you can still save it.',
    bookingsChooseService: '— Choose service —', bookingsCreated: 'Booking created', bookingsUpdated: 'Booking updated',
    bookingsConflict: 'That time overlaps another booking', bookingsValidate: 'Fill service, date, time, name and phone',
    bookingsSaveFailed: 'Could not save the booking', bookingsStatusChanged: p => `Booking: ${p.status}`,
    bookingsLinkedClient: p => `Linked to client ${p.name}.`, bookingsUnlink: 'Unlink',
    bookingsClientHint: 'Type to find a client. A new contact is saved as a client.',
    bookingsClientNoShows: p => `${p.n} ${p.n === 1 ? 'no-show' : 'no-shows'}`,
    bookingsToConfirm: 'To confirm', bookingsToConfirmAll: 'See all',
    bookingsConfirm: 'Confirm', bookingsDecline: 'Decline', bookingsComplete: 'Mark done', bookingsNoShow: 'No-show',
    bookingsCancel: 'Cancel booking', bookingsReopen: 'Reopen', bookingsEditAction: 'Edit', bookingsBack: 'Back', bookingsOpenService: 'Open service',
    bookingsInvoice: 'Invoice', bookingsInvoiced: 'Invoiced', bookingsBilled: 'Added to Services, ready to invoice.',
    bookingsCancelConfirmTitle: 'Cancel this booking?', bookingsCancelConfirmBody: p => `${p.name} · ${p.when}. The time becomes free for other bookings.`,
    bookingsCancelOk: 'Cancel booking',
    bookingsSetupTitle: 'Set up bookings',
    bookingsSetupServices: 'Choose bookable services', bookingsSetupServicesDesc: 'Turn on booking for catalog services and set how long each takes.',
    bookingsSetupHours: 'Set opening hours', bookingsSetupHoursDesc: 'Customers can only book inside these hours.',
    bookingsManageServices: 'Services', bookingsManageAvailability: 'Opening hours',
    bookingsServicesHint: 'These are your catalog services. Tick the ones customers can book and set how long each takes.',
    bookingsBookable: 'Bookable', bookingsGoCatalog: 'Edit names and prices in Catalog',
    bookingsNoServices: 'No services in the catalog', bookingsNoServicesDesc: 'Add one below — it goes into the catalog too.',
    bookingsServiceName: 'Service name', bookingsServiceSaved: 'Service saved', bookingsAddService: 'Add service',
    bookingsHoursHint: 'Opening hours for bookings. Add a second window on the same day for a lunch break.',
    bookingsHoursInvalid: 'Each window must end after it starts', bookingsRemoveWindow: 'Remove window',
    bookingsAvailabilitySaved: 'Opening hours saved', bookingsSaveHours: 'Save hours',
    bookingsAddWindow: 'Add window', bookingsDay: 'Day', bookingsFrom: 'From', bookingsTo: 'To',
    bookingsEmptyList: 'No bookings found',
    bookingsEmptyAgenda: 'Nothing booked yet', bookingsEmptyAgendaDesc: 'New bookings from the dashboard, WhatsApp and the assistant show up here.',
    bookingsThWhen: 'When', bookingsThContact: 'Contact', bookingsThService: 'Service', bookingsThStatus: 'Status', bookingsStatusAll: 'All',
    bookingStatusPENDING: 'Pending', bookingStatusCONFIRMED: 'Confirmed', bookingStatusCANCELLED: 'Cancelled', bookingStatusCOMPLETED: 'Completed', bookingStatusNO_SHOW: 'No-show',
    bookingsSourceDASHBOARD: 'Dashboard', bookingsSourceADMIN: 'Backoffice', bookingsSourceWHATSAPP: 'WhatsApp',
    bookingsSourceINSTAGRAM: 'Instagram', bookingsSourceWEB: 'Website chat', bookingsSourceASSISTANT: 'AI Assistant',
    bookingsErr_conflict: 'That time overlaps another booking', bookingsErr_outside_hours: 'That time is outside opening hours',
    bookingsErr_in_past: 'That time has already passed', bookingsErr_service_not_bookable: 'That service is not bookable',
    bookingsErr_service_not_found: 'That service no longer exists', bookingsErr_contact_required: 'Enter the contact name and phone',
    bookingsErr_invalid_time: 'Check the date, time and duration', bookingsErr_client_not_found: 'That client no longer exists',
    bookingsErr_booking_not_found: 'That booking no longer exists',
    assistantCreateBooking: 'Create booking', assistantRescheduleBooking: 'Move booking', assistantCancelBooking: 'Cancel booking',
    assistantConfirmBooking: 'Confirm booking', assistantBookingRef: p => `Booking: ${p.id}`,
    weekday1: 'Mon', weekday2: 'Tue', weekday3: 'Wed', weekday4: 'Thu', weekday5: 'Fri', weekday6: 'Sat', weekday7: 'Sun',
    instagramDesc: 'Review comments on your Instagram posts and reply from here.',
    instagramNeedsReply: 'Needs a reply', instagramPosts: 'Posts',
    instagramEmptyComments: 'No comments waiting',
    instagramEmptyCommentsDesc: 'New comments on your posts will show up here.',
    instagramEmptyPosts: 'No posts yet',
    instagramEmptyPostsDesc: 'Connect Instagram, publish a post, then open this page again.',
    instagramNotConnected: 'Instagram is not connected',
    instagramNotConnectedDesc: 'Connect your professional account in Settings to review posts and comments.',
    instagramReconnectBanner: 'Reconnect Instagram to review comments on your posts.',
    instagramThPost: 'Post', instagramThComment: 'Comment', instagramThFrom: 'From', instagramThWhen: 'When',
    instagramReply: 'Reply', instagramReplyPlaceholder: 'Write a public reply…',
    instagramReplied: 'Reply sent', instagramReplyFailed: 'Could not send the reply',
    instagramOpenPost: 'Open on Instagram', instagramUnreplied: 'Unreplied',
    instagramNoCaption: 'No caption', instagramGoSettings: 'Open Settings',
    instagramSyncFailed: 'Could not refresh Instagram',
  },

  admin: {
    nav: { clientes: 'Clients', servicos: 'Services', orcamentos: 'Quotes', faturas: 'Invoices', fornecedores: 'Suppliers', colaboradores: 'Employees', pagamentos: 'Payments', items: 'Standard items', bookings: 'Bookings' },
    crumbRoot: 'Panel',
    brandSub: 'Tenant · Management',
    searchPlaceholder: 'Search this view…',
    export: 'Export', exportTitle: 'Export CSV', exportSoon: 'Export · coming soon',
    backoffice: '← Backoffice', themeAria: 'Toggle theme', closeAria: 'Close',
    kpiReceivable: 'Receivable', kpiPaid: 'Paid this month',
    saving: 'Saving…', cancel: 'Cancel', save: 'Save', confirm: 'Confirm', delete: 'Delete',
    loading: 'Loading…', loadError: 'Load error',
    login: { eyebrow: p => `thebots.lab / ${p.tenant}`, title: 'Sign in to the CRM', desc: 'Use the operator password to open this management panel.', password: 'Password', submit: 'Sign in', invalid: 'Invalid login', crumb: 'Login' },
    invalidTenantTitle: 'Invalid tenant', invalidTenantDesc: 'Go back to the backoffice and open a valid CRM.',
    titleSuffix: 'Management Panel',
    pdfPending: 'pending',
    errorPdf: p => `PDF error: ${p.msg}`,
    error: p => `Error: ${p.msg}`,
    quoteStatus: { PENDENTE: 'Pending', SENT: 'Sent', ACEITO: 'Accepted' },
    invoiceStatus: { PENDING: 'Pending', PAID: 'Paid', OVERDUE: 'Overdue', CANCELLED: 'Cancelled' },
    paymentStatus: { PENDING: 'Pending', PAID: 'Paid', OVERDUE: 'Overdue', CANCELLED: 'Cancelled' },
    tabs: {
      clientes: { title: 'Clients', desc: 'Company client directory.', newLabel: 'New client' },
      orcamentos: { title: 'Quotes', desc: 'Issued commercial proposals.', newLabel: 'New quote' },
      faturas: { title: 'Invoices', desc: 'Issued invoices and their status.', newLabel: 'New invoice' },
      items: { title: 'Standard items', desc: 'Catalog of services and materials for quotes and invoices.', newLabel: 'New item' },
      servicos: { title: 'Services', desc: 'Work attached to a client. Group open rows into one invoice.', newLabel: 'New service' },
      fornecedores: { title: 'Suppliers', desc: 'People and companies you pay.', newLabel: 'New supplier' },
      colaboradores: { title: 'Employees', desc: 'People on your team. Record a payment against them from here.', newLabel: 'New employee' },
      pagamentos: { title: 'Payments', desc: 'Bills attached to a supplier or an employee. Mark paid when the money goes out.', newLabel: 'New payment' },
      financeiro: { title: 'Finances', desc: 'Money received and spent, by week or by month.' },
      bookings: { title: 'Bookings', desc: 'Appointments for your catalog services, linked to clients and billed when done.', newLabel: 'New booking' },
    },
    clients: {
      total: 'Total', new30: 'New · 30d', directory: 'Directory',
      one: 'client', many: 'clients',
      thName: 'Name', thAddress: 'Address', thPhone: 'Phone', thCreated: 'Created', thNo: 'Client no.',
      emptyTitle: 'No clients found', emptyDesc: 'Adjust the search or create a new client.',
      formName: 'Name', formAddress: 'Address', formPhone: 'Phone',
      phName: 'E.g.: Manuel Costa, Ltd.', phAddress: 'E.g.: 12 Rua das Flores, 1200-001 Lisbon', phPhone: '+351 912 345 678',
      eyebrow: 'Clients', formTitle: 'New client', saveLabel: 'Create client',
      validate: 'Enter name and phone', created: p => `Client created · ${p.name}`,
    },
    quotes: {
      total: 'Total', sent: 'Open', accepted: 'Accepted', proposals: 'Proposals', filterAll: 'All',
      thNumber: 'Number', thClient: 'Client', thStatus: 'Status', thValidUntil: 'Valid until', thTotal: 'Total', thPdf: 'PDF',
      emptyTitle: 'No quotes', emptyDesc: 'Create the first quote with the button above.',
      validUntil: 'Valid until', optional: 'optional', notes: 'Notes', notesPlaceholder: 'Internal notes, conditions, deadlines…',
      eyebrow: 'Quotes', formTitle: 'New quote', saveLabel: 'Create quote',
      chooseClient: 'Choose a client', addLine: 'Add at least one line', created: 'Quote created',
    },
    services: {
      open: 'Open', invoiced: 'Invoiced', cancelled: 'Cancelled', work: 'Client work', filterAll: 'All',
      viewList: 'List', byWeek: 'By week', byMonth: 'By month', summaryWeek: 'Week wrap-up', summaryMonth: 'Month wrap-up',
      periodPrev: 'Previous', periodNext: 'Next', periodCurrent: 'Current',
      vsPrev: p => `vs previous · ${p.delta}`,
      thPeriod: 'Period', thCount: 'Jobs',
      summaryEmpty: 'Nothing in this wrap-up', summaryEmptyDesc: 'Work appears here once it has a date.',
      thWhen: 'When', thClient: 'Client', thService: 'Service', thQty: 'Qty', thTotal: 'Total', thStatus: 'Status',
      emptyTitle: 'No services yet', emptyDesc: 'Attach work to a client, then invoice several rows together.',
      emptyFiltered: 'No matching services', emptyFilteredDesc: 'Try another client or clear the filters.',
      filterClientAll: 'All clients',
      formTitle: 'New service', editTitle: 'Edit service', save: 'Save service',
      name: 'Service', namePh: 'E.g.: Facade painting',
      fromCatalog: 'From catalog', fromBooking: 'from booking', fromCatalogNone: '— Custom service —',
      qty: 'Quantity', unit: 'Unit', price: 'Unit price €', when: 'Performed on', notes: 'Notes',
      validate: 'Choose a client and name the service',
      created: 'Service added', updated: 'Service updated', saveFailed: 'Could not save service',
      cancel: 'Cancel service', cancelConfirmTitle: 'Cancel this service?',
      cancelConfirmBody: p => `"${p.name}" stays in the list as cancelled and cannot be invoiced.`,
      cancelOk: 'Cancel service', cancelled: 'Service cancelled', cancelFailed: 'Could not cancel this service',
      delete: 'Delete service', deleteConfirmTitle: 'Delete this service?',
      deleteConfirmBody: p => `"${p.name}" will be removed. This cannot be undone.`,
      deleteOk: 'Delete service', deleted: 'Service deleted', deleteFailed: 'Could not delete this service',
      invoicedLocked: 'This service was invoiced and cannot be changed, cancelled, or deleted.',
      invoiceSelected: 'Invoice selected', invoiceDue: 'Invoice due date',
      invoiceNeedSameClient: 'Select open services from the same client',
      invoiceNeedRows: 'Select at least one open service',
      issuedFrom: p => `Invoice ${p.number} issued from services`,
      invoiceFailed: 'Could not invoice these services',
      addForClient: 'Add service',
      invoiceNow: 'Invoice', reopen: 'Reopen', reopened: 'Service reopened', reopenFailed: 'Could not reopen the service', openBooking: 'Open booking',
    },
    suppliers: {
      total: 'Total', new30: 'New · 30d', directory: 'Directory', filterAll: 'All suppliers',
      thName: 'Name', thAddress: 'Address', thPhone: 'Phone', thCreated: 'Created', thNo: 'Supplier no.',
      emptyTitle: 'No suppliers yet', emptyDesc: 'Add a supplier, then record payments against them.',
      formTitle: 'New supplier', editTitle: 'Edit supplier', save: 'Save supplier',
      formName: 'Name', formPhone: 'Phone', formAddress: 'Address',
      phName: 'E.g.: Tintas Norte, Lda.', phPhone: '+351 210 000 000', phAddress: 'E.g.: Zona Industrial, Porto',
      validate: 'Enter name and phone',
      created: 'Supplier added', updated: 'Supplier updated', saveFailed: 'Could not save supplier',
      addPayment: 'Add payment',
    },
    employees: {
      total: 'Total', new30: 'New · 30d', directory: 'Directory',
      thName: 'Name', thRole: 'Role', thPhone: 'Phone', thCreated: 'Created', thNo: 'Employee no.',
      emptyTitle: 'No employees yet', emptyDesc: 'Add the people on your team, then record payments against them.',
      addPayment: 'Add payment',
      formTitle: 'New employee', editTitle: 'Edit employee', save: 'Save employee',
      formName: 'Name', formPhone: 'Phone', formRole: 'Role',
      phName: 'E.g.: Ana Costa', phPhone: '+351 912 345 678', phRole: 'E.g.: Painter',
      validate: 'Enter name and phone',
      created: 'Employee added', updated: 'Employee updated', saveFailed: 'Could not save employee',
    },
    payments: {
      paid: 'Paid', pending: 'To pay', overdue: 'Overdue', ledger: 'Outgoing', filterAll: 'All',
      filterSupplierAll: 'All suppliers', filterPayeeAll: 'Everyone',
      thNumber: 'Number', thSupplier: 'Supplier', thEmployee: 'Employee', thPayee: 'Paid to', thStatus: 'Status', thDueDate: 'Due date', thTotal: 'Total',
      emptyTitle: 'No payments yet', emptyDesc: 'Record a bill against a supplier or an employee, then mark it paid.',
      emptyFiltered: 'No matching payments', emptyFilteredDesc: 'Try another person or clear the filters.',
      formTitle: 'New payment', save: 'Save payment',
      payee: 'Pay', paySupplier: 'Supplier', payEmployee: 'Employee',
      chooseSupplier: 'Choose a supplier', chooseSupplierEmpty: '— Choose supplier —',
      chooseEmployee: 'Choose an employee', chooseEmployeeEmpty: '— Choose employee —',
      needSupplier: 'Add a supplier first', needEmployee: 'Add an employee first', needPayee: 'Add a supplier or an employee first',
      enterDueDate: 'Enter the due date', addLine: 'Add at least one line',
      amount: 'Amount €', enterAmount: 'Enter the amount',
      generalEntry: 'Description', generalEntryValue: 'Payment',
      notes: 'Notes', notesPh: 'Internal note…',
      created: 'Payment recorded', saveFailed: 'Could not save payment',
      markPaid: 'Mark paid', markedPaid: p => `Payment ${p.number} marked as paid`,
      markPaidFailed: 'Could not mark this payment as paid',
      markPaidConfirmTitle: 'Mark this payment as paid?',
      markPaidConfirmBody: p => `This records that ${p.number} was paid.`,
    },
    invoices: {
      paid: 'Paid', pending: 'Pending', overdue: 'Overdue', documents: 'Documents', filterAll: 'All',
      viewList: 'List', byWeek: 'By week', byMonth: 'By month', summaryWeek: 'Week wrap-up', summaryMonth: 'Month wrap-up',
      periodPrev: 'Previous', periodNext: 'Next', periodCurrent: 'Current',
      vsPrev: p => `vs previous · ${p.delta}`,
      thPeriod: 'Period', thCount: 'Invoices',
      summaryEmpty: 'Nothing in this wrap-up', summaryEmptyDesc: 'Invoices appear here once they are issued.',
      thNumber: 'Number', thClient: 'Client', thStatus: 'Status', thDueDate: 'Due date', thTotal: 'Total', thPdfActions: 'PDF · Actions',
      emptyTitle: 'No invoices', emptyDesc: 'Issue the first invoice with the button above.',
      markPaid: 'Mark paid', markedPaid: p => `Invoice ${p.number} marked as paid`,
      dueDate: 'Due date', quoteId: 'Quote ID', quoteIdPlaceholder: 'Associated quote ID',
      eyebrow: 'Invoices', formTitle: 'New invoice', saveLabel: 'Issue invoice',
      chooseClient: 'Choose a client', enterDueDate: 'Enter the due date', addLine: 'Add at least one line', issued: 'Invoice issued',
    },
    financeiro: {
      viewList: 'List', byWeek: 'By week', byMonth: 'By month', summaryWeek: 'Week wrap-up', summaryMonth: 'Month wrap-up',
      periodPrev: 'Previous', periodNext: 'Next', periodCurrent: 'Current',
      vsPrev: p => `vs previous · ${p.delta}`,
      thPeriod: 'Period', thWhen: 'Date', thWho: 'Client / Supplier', thRef: 'Reference', thTotal: 'Amount',
      filterAll: 'All', received: 'Received', spent: 'Spent', net: 'Net', ledger: 'Transactions',
      summaryEmpty: 'Nothing in this wrap-up', summaryEmptyDesc: 'Transactions appear here once an invoice or payment is marked paid.',
      emptyTitle: 'No transactions yet', emptyDesc: 'Transactions appear here once an invoice or payment is marked paid.',
    },
    lines: {
      client: 'Client', chooseClient: '— Choose client —',
      services: 'Services', materials: 'Materials', label: 'Lines',
      colDescription: 'Description', colQty: 'Qty', colUnit: 'Unit', colPrice: 'Price €',
      addEmpty: '+ Empty line', catalogPick: 'Catalog · Services / Materials', add: 'Add', total: 'Total',
      descPlaceholder: 'Line description…', unitPlaceholder: 'un', removeLine: 'Remove line', chooseCatalogItem: 'Choose a catalog item',
    },
    items: {
      bookableLabel: 'Customers can book this service', bookableHint: 'Shows it in Bookings, the WhatsApp bot and the assistant.',
      durationLabel: 'Duration (min)', bookablePill: p => `Bookable · ${p.min} min`,
      services: 'Services', materials: 'Materials', catalogTitle: 'Catalog', tag: p => `${p.n} items`,
      thType: 'Type', thCategory: 'Category', thDescription: 'Description', thUnit: 'Unit', thPrice: 'Price', thActions: 'Actions',
      emptyTitle: 'Empty catalog', emptyDesc: 'Add services or materials to reuse in quotes.',
      pillService: 'SERVICE', pillMaterial: 'MATERIAL', editTitle: 'Edit', deleteTitle: 'Delete',
      idLabel: 'ID · slug', typeLabel: 'Type', service: 'Service', material: 'Material',
      categoryLabel: 'Category', descLabel: 'Description', unitLabel: 'Unit', priceLabel: 'Price (EUR)',
      phId: 'e.g.: srv-interior-painting', phCategory: 'E.g.: Painting, Structural, Labour…', phDesc: 'Description shown on quotes', phUnit: 'm², h, un, rl…',
      editingHint: p => `Editing ${p.id} — changes apply to new quotes.`,
      eyebrow: 'Standard items', newTitle: 'New catalog item', editTitleFull: p => `Edit · ${p.id}`,
      saveChanges: 'Save changes', createItem: 'Create item',
      fillRequired: 'Fill all required fields', updated: p => `Item updated · ${p.id}`, created: p => `Item created · ${p.id}`,
      confirmTitle: 'Delete catalog item?', confirmBody: p => `"${p.desc}" will be removed. Already-issued quotes are not affected.`,
      confirmOk: 'Delete item', deleted: p => `Item deleted · ${p.id}`,
    },
  },

  backoffice: {
    login: { eyebrow: 'thebots.lab / platform', title: 'Backoffice', desc: 'Operator access to manage bots, tenants and teams.', password: 'Password', submit: 'Sign in', invalid: 'Invalid login', google: 'Continue with Google', or: 'or use the admin password', notAllowed: 'This Google account is not allowed to open the backoffice', googleFailed: 'Google sign-in failed', cancelled: 'Sign-in cancelled', unavailable: 'No sign-in method is configured.' },
    cancel: 'Cancel', save: 'Save', confirm: 'Confirm', delete: 'Delete', loadError: 'Load error',
    error: p => `Error: ${p.msg}`,
    kpiActive: 'Active', kpiMessages: 'Messages', searchPlaceholder: 'Search tenant…', themeAria: 'Toggle theme',
    logout: 'Log out', crumbRoot: 'Platform', drawerEyebrow: 'Tenant', brandSub: 'Platform · Tenants', closeAria: 'Close',
    heroTitle: 'Tenants', heroDesc: 'Bots/clients configured on this platform.',
    botsTitle: 'Bots',
    thName: 'Name', thSlug: 'Slug', thChannels: 'Channels', thStatus: 'Status', thMsgs: 'Msgs', thLastActivity: 'Last activity', thActions: 'Actions',
    emptyTenants: 'No tenants found',
    openDashboard: 'Open Dashboard', users: 'Users', edit: 'Edit', suspend: 'Suspend', activate: 'Activate', reload: 'Reload',
    pipelineReloaded: 'Pipeline reloaded',
    noToken: 'no token', token: 'token',
    usersTitle: p => `Dashboard users · ${p.slug}`,
    thEmail: 'Email', thRole: 'Role',
    noUsers: 'No users', disable: 'Disable',
    emailLabel: 'Email', tempPassword: 'Temporary password', roleLabel: 'Role',
    createUser: 'Create user', emailPasswordRequired: 'Email and password required', userCreated: 'User created',
    userDisabled: 'User disabled', userActivated: 'User activated',
    tenantNameLabel: 'Name', tenantSlugLabel: 'Slug', languageLabel: 'Language',
    modelOverride: 'Model override', modelPlaceholder: 'blank = default',
    ratePerHour: 'Rate / hour', ratePerDay: 'Rate / day',
    modulesLabel: 'Modules', modulesHint: 'Only the overview stays enabled. Every other module — messaging included — is optional.',
    selectAllModules: 'All', selectNoModules: 'None',
    channelsLabel: 'Channels', connectWhatsApp: 'Connect WhatsApp', connectInstagram: 'Connect Instagram', addChannel: '+ Add channel',
    colPlatform: 'Platform', colExternalId: 'External ID', colAccessToken: 'Access token',
    channelsHint: 'Channels are optional — a tenant can be created without one and connected later. Instagram token is required when adding a channel. In edit, leave token blank to keep the existing one.',
    noChannels: 'No channels. This tenant works without one.',
    chExternalPlaceholder: 'phone_number_id or IG account id', chTokenUnchanged: 'unchanged', chTokenPlaceholder: 'access token', removeChannel: 'Remove channel',
    editTenant: p => `Edit · ${p.slug}`, newTenant: 'New bot/client', saveChanges: 'Save changes', createTenant: 'Create tenant',
    nameRequired: 'Name required', igNeedsToken: 'Instagram needs a Page access token',
    tenantUpdated: 'Tenant updated', botCreated: 'Bot created. Link the channels to the Meta app and point the webhook.',
    suspendTitle: 'Suspend tenant?', activateTitle: 'Activate tenant?', tenantLine: p => `Tenant ${p.slug}`,
    deleteTitle: 'Delete tenant?', deleteBody: p => `${p.slug} will be marked DELETED. Existing data is not erased.`,
    igSessionExpired: 'Session expired', igNotConfigured: 'Instagram OAuth not configured (IG_APP_ID)',
    igAllowPopups: 'Allow popups to connect Instagram', igConnected: 'Instagram connected ✓', igFailed: p => `Instagram failed: ${p.reason || 'error'}`,
    waNotConfigured: 'WhatsApp Embedded Signup not configured', waOpenPopup: 'Open the Meta popup to connect WhatsApp', waConnected: 'WhatsApp connected',
    waCancelled: 'WhatsApp connection cancelled', waMissingCode: 'Meta did not return the authorization code',
    waTimeout: 'Timed out waiting for Embedded Signup', waSdkFailed: 'Could not load the Facebook SDK', waFailed: p => `WhatsApp failed: ${p.msg}`,
    platformSettings: {
      nav: 'Platform settings',
      title: 'Platform settings',
      desc: 'Runtime overrides stored in MongoDB. Secrets are masked; reveal on demand. Mongo URI and listen port stay in .env only.',
      save: 'Save overrides',
      reload: 'Reload from Mongo',
      saved: 'Settings saved',
      reloaded: 'Settings reloaded',
      reveal: 'Reveal',
      hide: 'Hide',
      clear: 'Clear override',
      secretBadge: 'secret',
      sourceEnv: 'from .env',
      sourceOverride: 'Mongo override',
      updatedAt: p => `Updated ${p.at}`,
      neverUpdated: 'No overrides saved yet',
      passwordHint: 'Enter a new plaintext password (hashed on save) or paste a bcrypt hash.',
      empty: 'No settings available',
      categories: {
        whatsapp: 'WhatsApp',
        instagram: 'Instagram',
        openrouter: 'OpenRouter',
        ratelimit: 'Rate limits',
        pdf: 'PDF storage',
        admin: 'Admin auth',
      },
    },
  },
};
