/* Spanish (es) UI catalog. Registered into window.__I18N_CATALOGS['es']. */
window.__I18N_CATALOGS = window.__I18N_CATALOGS || {};
window.__I18N_CATALOGS['es'] = {
  common: {
    nav: {
      overview: 'Inicio', conversations: 'Conversaciones', contacts: 'Contactos',
      clients: 'Clientes', services: 'Servicios', quotes: 'Presupuestos', invoices: 'Facturas', financeiro: 'Finanzas', suppliers: 'Proveedores', employees: 'Colaboradores', payments: 'Pagos', catalog: 'Catálogo',
      persona: 'Persona', settings: 'Ajustes', 'ai-assistant': 'Asistente IA', bookings: 'Reservas', instagram: 'Instagram', agents: 'Agentes',
      groupInbox: 'Bandeja', groupBusiness: 'Negocio', groupBot: 'Automatización', groupSetup: 'Configuración',
    },
    lang: {
      title: 'Idioma', desc: 'Idioma usado en este panel.', label: 'Idioma',
      saved: 'Idioma actualizado ✓', saveFailed: 'No se pudo actualizar el idioma',
    },
    menuOpenAria: 'Abrir menú',
    menuCloseAria: 'Cerrar menú',
    themeToLight: 'Cambiar a tema claro',
    themeToDark: 'Cambiar a tema oscuro',
  },

  app: {
    settingsDesc: 'Canales conectados y configuración del bot.',
    channelsTitle: 'Canales',
    channelsDesc: 'Cuentas donde el asistente responde a tus clientes.',
    colChannel: 'Canal', colAccount: 'Cuenta', colStatus: 'Estado', colActions: 'Acciones',
    connected: 'Conectado', notConnected: 'No conectado',
    igConnect: 'Conectar Instagram', igReconnect: 'Reconectar Instagram', igDisconnect: 'Desconectar',
    waConnect: 'Conectar WhatsApp', waReconnect: 'Reconectar WhatsApp',
    channelsHint: 'WhatsApp e Instagram abren una ventana de Meta para autorizar tu cuenta empresarial. Instagram debe ser Business o Creator.',
    igHint: 'Conectar Instagram abre una ventana de Meta para autorizar tu cuenta profesional. La cuenta debe ser Business o Creator.',
    moreSettingsTitle: 'Más ajustes próximamente',
    moreSettingsDesc: 'Los miembros del equipo se gestionan en el backoffice por ahora.',
    docTemplateTitle: 'Plantilla de presupuesto y factura',
    docTemplateDesc: 'Diseña la página de los PDF de presupuesto y factura. Arrastra y redimensiona las cajas y guarda.',
    docCompanyName: 'Nombre de la empresa', docTagline: 'Eslogan', docTaglinePh: 'p. ej. Construcción y gestión',
    docTaxId: 'NIF / CIF', docTaxIdPh: 'NIF / IVA', docEmail: 'Email', docPhone: 'Teléfono', docAddress: 'Dirección',
    docQuoteTitle: 'Título del presupuesto', docInvoiceTitle: 'Título de la factura',
    docQuotePayment: 'Condiciones de pago (presupuestos)', docInvoicePayment: 'Condiciones de pago (facturas)',
    docTerms: 'Términos y condiciones', docFooter: 'Pie de página',
    docLogo: 'Logotipo', docLogoNone: 'Sin logotipo', docLogoLoading: 'Cargando logotipo…',
    docLogoUpload: 'Subir logotipo', docLogoRemove: 'Quitar logotipo',
    docLogoHint: 'PNG, JPG o WebP, máx. 2 MB. Se muestra en los PDF de presupuesto y factura.',
    docLogoUploaded: 'Logotipo subido', docLogoRemoved: 'Logotipo eliminado', docLogoUploadFailed: 'No se pudo actualizar el logotipo',
    docTemplateSave: 'Guardar plantilla', docTemplateSaved: 'Plantilla de documento guardada',
    docTemplateSaveFailed: 'No se pudo guardar la plantilla',
    docTplDragHint: 'Arrastra una caja para moverla. Redimensiona desde los tiradores. Haz clic en una caja para editar su contenido.',
    docTplOverlap: 'Estas cajas se solapan, así que su texto se imprimirá uno encima del otro. Sepáralas.',
    docTplPreviewQuote: 'Presupuesto', docTplPreviewInvoice: 'Factura',
    docTplResetLayout: 'Restablecer diseño', docTplLayoutReset: 'Diseño restablecido a la página predeterminada',
    docTplLayers: 'Bloques', docTplInspector: 'Bloque seleccionado',
    docTplEmptySelect: 'Haz clic en una caja de la página para editarla.',
    docTplAccent: 'Color de acento', docTplDecor: 'Ondas decorativas',
    docTplShow: 'Mostrar', docTplHide: 'Ocultar',
    docTplPos: 'Posición', docTplSize: 'Tamaño',
    docTplSampleHint: 'La vista previa usa datos de ejemplo. Los presupuestos y facturas reales se rellenan desde el CRM.',
    docTplPageLabel: 'A4 · 210 × 297 mm',
    docTplDirty: 'Cambios sin guardar',
    docTplColService: 'Servicio', docTplColDesc: 'Descripción', docTplColValue: 'Importe',
    docTplColQty: 'Cant.', docTplColPrice: 'Precio',
    docTplClientLabel: 'Cliente', docTplPaymentLabel: 'Forma de pago', docTplTermsLabel: 'Términos y condiciones',
    docTplDateLabel: 'Emitido el', docTplDueLabel: 'Vencimiento', docTplTotalLabel: 'Total',
    docTplSampleClient: 'Cliente de ejemplo', docTplSamplePhone: '+351 210 000 000', docTplSampleClientRef: 'CLT-001  ·  NIF 123456789',
    docTplSampleItem1: 'Pintura interior', docTplSampleItem1Desc: 'Preparación y dos manos',
    docTplSampleItem2: 'Enfoscado exterior', docTplSampleItem2Desc: 'Reparación y acabado de fachada',
    docTplSampleQuoteNo: 'PRE-1042', docTplSampleInvoiceNo: 'FAC-1042',
    docTplBlockLogo: 'Logotipo', docTplBlockContact: 'Contacto', docTplBlockCompany: 'Empresa',
    docTplBlockTitle: 'Título del documento', docTplBlockClient: 'Cliente', docTplBlockItems: 'Líneas',
    docTplBlockTotals: 'Total', docTplBlockPayment: 'Condiciones de pago', docTplBlockTerms: 'Términos',
    docTplBlockFooter: 'Pie de página',
    docTplHideAria: 'Alternar visibilidad',
    docTplColorAria: 'Color de acento',
    docTplTemplates: 'Plantillas',
    docTplTemplatesTitle: 'Plantillas de documento',
    docTplTemplatesDesc: 'Empieza con un diseño o reutiliza uno que hayas guardado. Aplicar una plantilla conserva los datos de tu empresa.',
    docTplTemplatesGallery: 'Diseños iniciales', docTplTemplatesYours: 'Tus plantillas',
    docTplTemplatesEmpty: 'Aún no tienes plantillas guardadas. Guarda tu diseño actual abajo.',
    docTplPresetBuiltIn: 'Incluida',
    docTplPresetApply: 'Aplicar', docTplPresetApplied: 'Plantilla aplicada',
    docTplPresetApplyFailed: 'No se pudo aplicar la plantilla',
    docTplPresetDelete: 'Eliminar', docTplPresetDeleted: 'Plantilla eliminada',
    docTplPresetDeleteFailed: 'No se pudo eliminar la plantilla',
    docTplPresetDeleteConfirmTitle: '¿Eliminar esta plantilla?',
    docTplPresetDeleteConfirmBody: 'Esta acción no se puede deshacer.',
    docTplPresetSaveLabel: 'Guardar el diseño actual como plantilla',
    docTplPresetNamePh: 'p. ej. Campaña de verano',
    docTplPresetSaveBtn: 'Guardar plantilla',
    docTplPresetSaved: 'Plantilla guardada', docTplPresetSaveFailed: 'No se pudo guardar la plantilla',
    docTplPresetNameRequired: 'Ponle un nombre a la plantilla',
    docTplPresetClassic: 'Clásica', docTplPresetModern: 'Moderna', docTplPresetMinimal: 'Minimalista',
    docTplPresetClear: 'Legible', docTplPresetStatement: 'Extracto', docTplPresetMargin: 'Margen',
    docTplPresetClassicDesc: 'Página original con pastillas y letras espaciadas.',
    docTplPresetModernDesc: 'La misma página con pastillas, logotipo a la izquierda, azul.',
    docTplPresetMinimalDesc: 'La misma página con pastillas, cabecera compacta, sin ondas.',
    docTplPresetClearDesc: 'Factura legible: cabecera de empresa, columnas de cant. y precio, sin pastillas.',
    docTplPresetStatementDesc: 'Tarjeta del documento a la derecha, cliente en una caja, misma tabla clara.',
    docTplPresetMarginDesc: 'Banda de acento a la izquierda, misma tabla clara.',
    sessionExpired: 'Sesión expirada',
    igUnavailable: 'La conexión con Instagram no está disponible',
    igAllowPopups: 'Permite las ventanas emergentes para conectar Instagram',
    igConnected: 'Instagram conectado ✓',
    igFailed: reason => `No se pudo conectar Instagram${reason ? ` (${reason})` : ''}`,
    igDisconnectConfirmTitle: '¿Desconectar Instagram?',
    igDisconnectConfirmBody: p => `${p.account} dejará de recibir respuestas automáticas. Puedes reconectarlo cuando quieras.`,
    igDisconnectAction: 'Desconectar', igDisconnected: 'Instagram desconectado', igDisconnectFailed: 'No se pudo desconectar Instagram',
    waNotConfigured: 'La conexión con WhatsApp no está disponible',
    waOpenPopup: 'Abre la ventana de Meta para conectar WhatsApp',
    waConnected: 'WhatsApp conectado ✓',
    waCancelled: 'Conexión de WhatsApp cancelada',
    waMissingCode: 'Meta no devolvió el código de autorización',
    waTimeout: 'Tiempo agotado esperando el registro de WhatsApp',
    waSdkFailed: 'No se pudo cargar el SDK de Facebook',
    waFailed: p => `No se pudo conectar WhatsApp${p?.msg ? ` (${p.msg})` : ''}`,
    webTitle: 'Widget del sitio web',
    webDesc: 'Añade el asistente de chat a tu sitio web. Pega este fragmento justo antes de la etiqueta </body>.',
    webGenerate: 'Generar código del widget',
    webRegenerate: 'Widget activo',
    webCopy: 'Copiar fragmento',
    webCopied: 'Fragmento copiado ✓',
    webGenerated: 'Código del widget generado ✓',
    webGenerateFailed: 'No se pudo generar el código del widget',
    webOriginsLabel: 'Dominios de sitio permitidos (opcional)',
    webOriginsHint: 'Un origen por línea, p. ej. https://www.tusitio.com. Déjalo vacío para permitir cualquier sitio (menos seguro).',
    webOriginsSave: 'Guardar dominios',
    webOriginsSaved: 'Dominios guardados ✓',
    webRowName: 'Sitio web',
    quickCreateSoon: 'La creación rápida de este módulo llegará pronto.',
    clientFormTitle: 'Nuevo cliente',
    clientFormName: 'Nombre', clientFormPhone: 'Teléfono', clientFormAddress: 'Dirección',
    clientPhName: 'Nombre del cliente', clientPhPhone: '+351…', clientPhAddress: 'Calle, ciudad',
    clientSave: 'Crear cliente',
    clientValidate: 'Introduce nombre y teléfono',
    clientCreated: p => `Cliente creado · ${p.name}`,
    clientCreateFailed: 'No se pudo crear el cliente',
    optional: 'opcional',
    catalogFormTitle: 'Nuevo ítem', catalogSave: 'Crear ítem',
    catalogId: 'ID', catalogType: 'Tipo', catalogService: 'Servicio', catalogMaterial: 'Material',
    catalogCategory: 'Categoría', catalogDesc: 'Descripción', catalogUnit: 'Unidad', catalogPrice: 'Precio (€)',
    catalogPhId: 'srv-…', catalogPhCategory: 'Ej.: Fachadas', catalogPhDesc: 'Qué cubre este ítem', catalogPhUnit: 'm2, unidad, servicio…',
    catalogValidate: 'Rellena todos los campos obligatorios', catalogCreated: p => `Ítem creado · ${p.id}`, catalogCreateFailed: 'No se pudo crear el ítem',
    quoteFormTitle: 'Nuevo presupuesto', quoteSave: 'Crear presupuesto',
    quoteValidUntil: 'Válido hasta', quoteNotes: 'Notas', quoteNotesPh: 'Notas opcionales mostradas en el PDF',
    quoteChooseClient: 'Elige un cliente', quoteAddLine: 'Añade al menos una línea', quoteCreated: 'Presupuesto creado', quoteCreateFailed: 'No se pudo crear el presupuesto',
    invoiceFormTitle: 'Nueva factura', invoiceSave: 'Emitir factura',
    invoiceDueDate: 'Vencimiento', invoiceQuoteId: 'ID del presupuesto', invoiceQuoteIdPh: 'Asociar un presupuesto existente (opcional)',
    invoiceChooseClient: 'Elige un cliente', invoiceEnterDueDate: 'Indica la fecha de vencimiento', invoiceAddLine: 'Añade al menos una línea', invoiceCreated: 'Factura emitida', invoiceCreateFailed: 'No se pudo emitir la factura',
    lineClient: 'Cliente', lineChooseClient: 'Seleccionar…', lineItemsLabel: 'Líneas',
    lineColDesc: 'Descripción', lineColQty: 'Cant.', lineColUnit: 'Unidad', lineColPrice: 'Precio',
    lineAddEmpty: 'Añadir línea', lineCatalogPick: 'Del catálogo…', lineAdd: 'Añadir', lineTotal: 'Total',
    lineDescPh: 'Descripción', lineUnitPh: 'un', lineRemove: 'Eliminar línea', lineChooseCatalog: 'Elige un ítem del catálogo',
    loginEyebrow: 'thebots.lab / tenant',
    loginTitle: 'Inicia sesión en el panel',
    loginDesc: 'Accede a los datos del chatbot, conversaciones y CRM.',
    loginEmail: 'Email', loginPassword: 'Contraseña', loginSubmit: 'Entrar', loginInvalid: 'Acceso inválido',
    loginGoogle: 'Continuar con Google', loginOr: 'o entra con tu email y contraseña',
    loginGoogleCancelled: 'Inicio de sesión cancelado', loginGoogleFailed: 'No se pudo iniciar sesión con Google',
    loginGooglePopupBlocked: 'Permite las ventanas emergentes en este sitio para entrar con Google',
    loginGoogleNoAccount: 'Esta cuenta de Google aún no está vinculada a ningún usuario. Entra con tu email y contraseña y vincúlala en tu cuenta.',
    loginGoogleOtherAccount: 'Tu usuario está vinculado a otra cuenta de Google. Entra con esa cuenta.',
    loginInactive: 'Esta cuenta está inactiva',
    accountAria: 'Tu cuenta', accountTitle: 'Cuenta', accountLoadFailed: 'No se pudo cargar tu cuenta',
    accountRoleTENANT_ADMIN: 'Administrador', accountRoleTENANT_MEMBER: 'Miembro',
    accountMethods: 'Cómo entras', accountGoogle: 'Google', accountPassword: 'Contraseña',
    accountLinked: 'Vinculada', accountNotLinked: 'No vinculada', accountOn: 'Activa', accountOff: 'Desactivada',
    accountGoogleOffDetail: 'Un clic, sin contraseña que recordar',
    accountGoogleUnavailable: 'El inicio de sesión con Google no está disponible',
    accountPasswordOnDetail: 'Tu email y contraseña',
    accountPasswordOffDetail: 'Desactivada: entras solo con Google',
    accountHintLink: 'Vincula tu cuenta de Google para entrar con un clic. Después puedes desactivar la contraseña para que solo Google te dé acceso.',
    accountHintBoth: 'Puedes entrar con Google o con tu contraseña. Desactiva la contraseña para entrar solo con Google.',
    accountHintGoogleOnly: 'Solo tu cuenta de Google te da acceso. Para volver a entrar con contraseña, define una.',
    accountGoogleTitle: 'Cuenta de Google', accountGoogleEmail: 'Cuenta vinculada',
    accountGoogleLinkIntro: 'Confirma tu contraseña actual y elige tu cuenta de Google.',
    accountCurrentPassword: 'Contraseña actual',
    accountGoogleLinked: 'Cuenta de Google vinculada',
    accountGoogleUnlinkIntro: 'Después de desvincularla, entras solo con email y contraseña.',
    accountGoogleUnlinkAction: 'Desvincular cuenta de Google', accountGoogleUnlinked: 'Cuenta de Google desvinculada',
    accountGoogleOnlyKeep: 'Es tu única forma de entrar. Para desvincularla, define antes una contraseña.',
    accountSetPasswordAction: 'Definir contraseña',
    accountNewPassword: 'Nueva contraseña', accountNewPasswordHint: 'Al menos 8 caracteres', accountRepeatPassword: 'Repite la nueva contraseña',
    accountSavePassword: 'Guardar contraseña', accountPasswordChanged: 'Contraseña cambiada',
    accountGoogleOnlyTitle: 'Entrar solo con Google',
    accountGoogleOnlyIntro: p => `Desactiva la contraseña para que solo tu cuenta de Google (${p.email}) te dé acceso. Primero confirmas con Google, y puedes volver a definir una contraseña cuando quieras.`,
    accountGoogleOnlyNeedsLink: 'Vincula antes una cuenta de Google para poder entrar solo con Google.',
    accountGoogleOnlyAction: 'Confirmar con Google y desactivar', accountLinkGoogleAction: 'Vincular cuenta de Google',
    accountPasswordOff: 'Contraseña desactivada. Entras solo con Google.',
    accountSetIntro: p => `Entras solo con Google (${p.email}). Define una contraseña para entrar también con tu email.`,
    accountSetAction: 'Confirmar con Google y guardar', accountPasswordSet: 'Contraseña definida',
    accountFailed: 'No se pudo guardar el cambio',
    accountErr_wrong_password: 'Tu contraseña actual es incorrecta',
    accountErr_mismatch: 'Las nuevas contraseñas no coinciden',
    accountErr_password_too_short: 'La nueva contraseña necesita al menos 8 caracteres',
    accountErr_password_too_long: 'La nueva contraseña es demasiado larga',
    accountErr_google_in_use: 'Esa cuenta de Google ya está vinculada a otro usuario',
    accountErr_other_google_account: 'Elige la cuenta de Google vinculada a tu usuario',
    accountErr_already_linked: 'Ya tienes una cuenta de Google vinculada',
    accountErr_password_required: 'Define antes una contraseña',
    accountErr_google_required: 'Vincula antes una cuenta de Google',
    companySwitchAria: 'Cambiar de empresa', companiesSwitchTitle: 'Cambiar de empresa', companiesManage: 'Gestionar empresas',
    companyCurrent: 'Actual', companyOpen: 'Abrir', companyFirst: 'Se abre al entrar', companyStatusSUSPENDED: 'Suspendida',
    companySwitchFailed: 'No se pudo cambiar de empresa',
    settingsCompanies: 'Empresas', companiesTitle: 'Empresas',
    companiesDesc: 'Cada empresa tiene sus propios clientes, documentos, canales y ajustes. Cambia entre ellas desde el nombre de la empresa, arriba del menú.',
    companiesUsage: p => `${p.used} de ${p.limit}`,
    companyAddTitle: 'Añadir empresa',
    companyAddHint: 'Empieza vacía, con los mismos módulos que tu primera empresa. Ábrela para conectar sus canales y configurar sus documentos.',
    companyNameLabel: 'Nombre de la empresa', companyCreate: 'Crear empresa',
    companyCreated: p => `${p.name} creada`, companyCreateFailed: 'No se pudo crear la empresa',
    companiesLimitReached: p => (p.limit === 1
      ? 'Tu plan incluye 1 empresa, ya en uso. Contáctanos para añadir más.'
      : `Tu plan incluye ${p.limit} empresas, todas en uso. Contáctanos para añadir más.`),
    companiesAdminOnly: 'Solo los administradores pueden añadir empresas.',
    companiesLoadFailed: 'No se pudieron cargar tus empresas',
    companyErr_company_limit: 'Has alcanzado el límite de empresas.',
    companyErr_name_required: 'Escribe el nombre de la empresa.',
    companyErr_not_allowed: 'Solo los administradores pueden añadir empresas.',
    companyErr_company_inactive: 'Esa empresa está suspendida.',
    recordDelete: 'Eliminar', recordArchive: 'Archivar', recordRestore: 'Restaurar',
    recordDeleteTitle: p => `¿Eliminar ${p.name}?`, recordDeleteBody: 'Se borra definitivamente. No se puede deshacer.',
    recordArchiveTitle: p => `¿Archivar ${p.name}?`,
    clientArchiveBody: 'Este cliente tiene presupuestos, facturas, servicios o citas, así que no se puede eliminar. Archivar lo oculta de las listas y selectores y conserva sus documentos. Puedes restaurarlo desde Archivados.',
    payeeArchiveBody: 'Este registro tiene pagos, así que no se puede eliminar. Archivar lo oculta de las listas y selectores y conserva sus pagos. Puedes restaurarlo desde Archivados.',
    recordDeleted: 'Eliminado', recordArchived: 'Archivado', recordRestored: 'Restaurado', recordRemoveFailed: 'No se pudo guardar el cambio',
    recordArchivedOn: p => `Archivado el ${p.date}. Queda oculto de las listas y selectores hasta que lo restaures.`,
    directoryActive: 'Activos', directoryArchived: 'Archivados',
    directoryArchivedEmpty: 'Nada archivado', directoryArchivedEmptyDesc: 'Los registros que archives aparecen aquí, listos para restaurar.',
    clientDuplicateArchived: p => `Un cliente archivado ya tiene este número: ${p.name} (${p.number}).`,
    newPrefix: 'Nuevo',
    dashboardWord: 'Panel', searchPlaceholder: 'Buscar…', logout: 'Salir', themeAria: 'Cambiar tema',
    poweredBy: 'Powered by',
    closeAria: 'Cerrar', cancel: 'Cancelar', confirm: 'Confirmar',
    noData: 'Sin datos',
    contactStatusACTIVE: 'Activo', contactStatusBLOCKED: 'Bloqueado', contactStatusRATE_LIMITED: 'Con límite',
    conversationStateACTIVE: 'Abierta', conversationStateARCHIVED: 'Archivada',
    markPaidConfirmTitle: '¿Marcar esta factura como pagada?',
    markPaidConfirmBody: p => `La factura ${p.number} se marcará como pagada.`,
    overviewDesc: 'El pulso del negocio: dinero, personas y lo que te necesita hoy.',
    needsYou: 'Te necesita', needsYouEmpty: 'Estás al día', needsYouEmptyDesc: 'Sin chats en espera, facturas vencidas, reservas pendientes ni comentarios de Instagram.',
    setupTitle: 'Terminar configuración', setupDone: 'La configuración parece completa.',
    todayTitle: 'Hoy',
    waitingChat: 'Esperando respuesta', overdueInvoice: 'Factura vencida', pendingBooking: 'Reserva pendiente', instagramWaitingComment: 'Comentario de Instagram',
    dueSoonInvoice: 'Factura a punto de vencer', overduePayment: 'Pago vencido', dueSoonPayment: 'Pago a vencer', quoteExpiring: 'Presupuesto por caducar', assistantAction: p => `${p.n} ${p.n === 1 ? 'acción' : 'acciones'} del asistente pendientes de aprobación`,
    overdueInvoiceN: p => `${p.n} ${p.n === 1 ? 'factura vencida' : 'facturas vencidas'}`, overduePaymentN: p => `${p.n} ${p.n === 1 ? 'pago vencido' : 'pagos vencidos'}`,
    teachBot: 'Enseñar al bot', setupWidget: 'Añadir el widget web',
    openModule: 'Abrir',
    healthOk: 'Al día', healthWatch: 'Atención', healthUrgent: 'Urgente',
    pulseOk: 'Nada en espera — el día está calmado.',
    pulseNeeds: p => `${p.n} ${p.n === 1 ? 'asunto te necesita' : 'asuntos te necesitan'}`,
    pulseOutstanding: p => `${p.amount} por cobrar`,
    pulseBookingsToday: p => `${p.n} ${p.n === 1 ? 'reserva' : 'reservas'} hoy`,
    hl_collected_month: 'Recibido este mes', hl_outstanding: 'Por cobrar', hl_overdue: 'Vencido',
    hl_pipeline_open: 'Presupuestos abiertos', hl_win_rate: 'Tasa de cierre', hl_waiting: 'Esperando respuesta',
    hl_messages_today: 'Mensajes hoy', hl_bookings_today: 'Reservas hoy', hl_clients: 'Clientes',
    hl_contacts: 'Contactos', hl_instagram_unreplied: 'Comentarios sin responder',
    vsLastMonth: 'vs mes pasado', vsLastWeek: 'vs semana pasada',
    deltaUp: p => `↑ ${p.pct}% ${p.vs}`, deltaDown: p => `↓ ${p.pct}% ${p.vs}`, deltaFlat: p => `= ${p.vs}`,
    snapFinance: 'Finanzas', snapPipeline: 'Pipeline', snapCustomers: 'Clientes', snapInbox: 'Bandeja',
    snapCalendar: 'Esta semana', snapSocial: 'Instagram', snapCatalog: 'Catálogo', snapServices: 'Servicios', snapSuppliers: 'Proveedores', snapEmployees: 'Colaboradores', snapAssistant: 'Asistente',
    cashPaidCount: 'Pagos este mes',
    financeGained: 'Recibido este mes', financeSpent: 'Gastado este mes', financeReceivable: 'Por cobrar', financePayable: 'Por pagar',
    pipelineDrafts: 'Borradores', pipelineSent: 'Enviados', pipelineAccepted: 'Aceptados', pipelineExpiring: 'Caducan esta semana',
    pipelineAcceptedMonth: 'Aceptados este mes',
    customersNewMonth: 'Nuevos este mes', customersNewLastMonth: 'Nuevos el mes pasado',
    inboxWeek: 'Mensajes esta semana', inboxPaused: 'Respuesta automática en pausa', inboxNewContacts: 'Contactos nuevos · 7d',
    calendarPending: 'Por confirmar', calendarNext: 'Siguiente', calendarNone: 'Sin reservas',
    catalogItems: 'Ítems', servicesOpen: 'Abiertos para facturar', servicesInvoicedMonth: 'Facturado este mes',
    suppliersNewMonth: 'Nuevos este mes', suppliersNewLastMonth: 'Nuevos el mes pasado',
    employeesNewMonth: 'Nuevos este mes', employeesNewLastMonth: 'Nuevos el mes pasado',
    assistantPending: 'Acciones por confirmar',
    overviewEmptyTitle: 'Este espacio está listo',
    overviewEmptyDesc: 'Activa módulos en el backoffice para ver dinero, bandeja y agenda aquí.',
    customizeHome: 'Elegir tarjetas',
    settingsHome: 'Inicio',
    homeLayoutTitle: 'Tarjetas de Inicio',
    homeLayoutDesc: 'Elige qué resúmenes aparecen en Inicio. Solo se listan los módulos activos de este espacio.',
    homeLayoutSections: 'De un vistazo',
    homeLayoutSnapshots: 'Paneles',
    homeLayoutShown: 'Visible',
    homeLayoutHidden: 'Oculto',
    homeLayoutSaved: 'Disposición de Inicio guardada',
    homeLayoutSaveFailed: 'No se pudo guardar la disposición de Inicio',
    homeCard_highlights: 'Destacados',
    homeCard_highlightsDesc: 'Los números de la parte superior de Inicio',
    homeCard_pulse: 'Pulso de salud',
    homeCard_pulseDesc: 'Una línea sobre lo que te necesita hoy',
    homeCard_attentionDesc: 'Facturas vencidas, pagos vencidos, chats en espera, reservas por confirmar',
    homeCard_setupDesc: 'Conectar canales y enseñar al bot',
    homeCard_calendar: 'Agenda',
    homeCard_financeDesc: 'Cuánto entró y cuánto salió',
    homeCard_pipelineDesc: 'Presupuestos abiertos y tasa de cierre',
    homeCard_customersDesc: 'Número de clientes y nuevos este mes',
    homeCard_inboxDesc: 'Chats en espera y mensajes de hoy',
    homeCard_calendarDesc: 'Reservas de hoy y por confirmar',
    homeCard_socialDesc: 'Comentarios de Instagram sin respuesta',
    homeCard_catalogDesc: 'Ítems del catálogo',
    homeCard_servicesDesc: 'Trabajo por facturar ligado a clientes',
    homeCard_suppliers: 'Proveedores',
    homeCard_suppliersDesc: 'Directorio de proveedores',
    homeCard_employees: 'Colaboradores',
    homeCard_employeesDesc: 'Personas del equipo',
    homeCard_payments: 'Pagos',
    homeCard_assistantDesc: 'Acciones pendientes de aprobación',
    greetingMorning: 'Buenos días', greetingAfternoon: 'Buenas tardes', greetingEvening: 'Buenas noches',
    dashKpisAria: 'Cifras clave', openModuleAria: 'Abrir {name}',
    kpiNet: 'Saldo del mes', kpiOverdue: '{amount} vencido', kpiDueSoon: p => `${p.n} ${p.n === 1 ? 'vence' : 'vencen'} esta semana`,
    kpiInOut: '{in} recibido · {out} gastado', kpiQuotes: p => `${p.n} ${p.n === 1 ? 'presupuesto' : 'presupuestos'} · ${p.pct}% de cierre`,
    kpiMessagesToday: p => `${p.n} ${p.n === 1 ? 'mensaje' : 'mensajes'} hoy`, kpiThisWeek: '{n} esta semana',
    kpiNewThisMonth: '+{n} este mes', kpiNewThisWeek: '+{n} esta semana',
    dashCashFlow: 'Flujo de caja', dashLast6Months: 'Últimos 6 meses', dashMoneyIn: 'Entradas', dashMoneyOut: 'Salidas',
    dashAvgIn: 'Media de entradas / mes', dashAvgOut: 'Media de salidas / mes', dashIssuedMonth: 'Facturado este mes',
    dashCashEmpty: 'Sin pagos registrados en los últimos 6 meses',
    dashAgendaEmpty: 'No hay reservas hoy', dashNow: 'Ahora',
    dashReceivables: 'Cuentas por cobrar', dashPayables: 'Cuentas por pagar', dashOutstanding: 'Pendiente',
    agingCurrent: 'Aún no vencido', agingWeek: '1–7 días de retraso', agingMonth: '8–30 días de retraso', agingOld: '+30 días de retraso',
    dashTopOverdue: 'Mayores importes vencidos', dashDueSoon: 'Vence esta semana',
    dashOpenQuotesN: p => `${p.n} ${p.n === 1 ? 'presupuesto abierto' : 'presupuestos abiertos'}`,
    dashWeekChange: 'Variación vs semana pasada', dashLast14Days: 'Últimos 14 días',
    dashTopClients: 'Mejores clientes', dashLast12Months: 'Últimos 12 meses',
    dashInvoicesN: p => `${p.n} ${p.n === 1 ? 'factura' : 'facturas'}`, dashPaidPct: '{pct}% pagado',
    dashTopClientsEmpty: 'Sin facturas en los últimos 12 meses',
    dashRecent: 'Actividad reciente', dashRecentEmpty: 'Aún no hay novedades',
    recent_invoice_paid: 'Factura {number} pagada', recent_invoice_issued: 'Factura {number} emitida',
    recent_payment_paid: 'Pago {number} realizado', recent_quote_accepted: 'Presupuesto {number} aceptado',
    recent_quote_created: 'Presupuesto {number} creado', recent_client_created: 'Nuevo cliente', recent_booking_created: 'Nueva reserva',
    settingsAppearance: 'Apariencia',
    appearanceThemeTitle: 'Tema', themeLight: 'Claro', themeLightDesc: 'Superficies claras para trabajar de día.',
    themeDark: 'Oscuro', themeDarkDesc: 'Menos brillo para espacios con poca luz.',
    appearanceActive: 'Activo', appearanceSaved: 'Apariencia actualizada',
    openInbox: 'Abrir bandeja', viewInvoices: 'Ver facturas', viewBookings: 'Ver reservas',
    waiting: 'En espera', noThread: 'Selecciona una conversación', noThreadDesc: 'Elige un cliente a la izquierda para leer y responder.',
    quoteMarkSent: 'Marcar enviado', quoteAccept: 'Aceptar', quoteConvert: 'Convertir en factura',
    quoteConverted: 'Factura emitida desde este presupuesto', quoteStatusUpdated: 'Presupuesto actualizado',
    quoteConvertDue: 'Vencimiento de la factura', quoteConvertFailed: 'No se pudo convertir este presupuesto',
    clientUpdated: 'Cliente actualizado', clientUpdateFailed: 'No se pudo actualizar el cliente', clientEdit: 'Editar cliente',
    clientEyebrow: 'Cliente', clientEditAction: 'Editar', clientSaveChanges: 'Guardar cambios', clientBackAria: p => `Volver a ${p.name}`,
    clientSince: p => `Cliente desde ${p.date}`, clientLastActivity: p => `última actividad ${p.when}`,
    clientVisits: p => `${p.n} ${p.n === 1 ? 'visita' : 'visitas'}`, clientTaxIdShort: p => `NIF ${p.id}`,
    clientCall: 'Llamar', clientWhatsApp: 'WhatsApp', clientOpenChat: 'Abrir conversación',
    clientKpiOutstanding: 'Pendiente de cobro', clientKpiOverdue: p => `${p.amount} vencido`,
    clientKpiUnpaid: p => `${p.n} ${p.n === 1 ? 'factura pendiente' : 'facturas pendientes'}`, clientKpiNothingDue: 'Nada pendiente',
    clientKpiNextBooking: 'Próxima cita', clientKpiNoBooking: 'Ninguna programada',
    clientKpiUnbilled: 'Por facturar', clientKpiServices: p => `${p.n} ${p.n === 1 ? 'servicio' : 'servicios'}`,
    clientKpiBilled: 'Facturado', clientKpiPaid: p => `${p.amount} cobrado`,
    clientKpiQuotes: 'En propuesta', clientKpiOpenQuotes: p => `${p.n} ${p.n === 1 ? 'presupuesto abierto' : 'presupuestos abiertos'}`,
    clientAttention: 'Requiere atención',
    clientAttnOverdue: p => `${p.number} vencida`, clientAttnOverdueDetail: p => `venció ${p.when}`,
    clientAttnUnclosed: 'Cita por cerrar', clientAttnPendingBooking: 'Cita por confirmar',
    clientAttnUnbilled: p => `${p.n} ${p.n === 1 ? 'servicio' : 'servicios'} por facturar`,
    clientAttnQuote: p => `${p.number} esperando respuesta`, clientAttnQuoteDraft: p => `${p.number} sin enviar`,
    clientAttnQuoteExpired: p => `caducó ${p.when}`, clientAttnDueSoon: p => `${p.number} vence pronto`, clientDueWhen: p => `vence ${p.when}`,
    clientValidUntil: p => `válido hasta ${p.date}`, clientCreatedOn: p => `creado el ${p.date}`, clientIssuedOn: p => `emitida el ${p.date}`,
    clientTabActivity: 'Actividad', clientUpcoming: 'Próximas', clientPast: 'Anteriores', clientHistory: 'Historial', clientThDate: 'Fecha',
    clientKindBooking: 'Cita', clientKindService: 'Servicio',
    clientEvtQuote: p => `Presupuesto ${p.number}`, clientEvtInvoice: p => `Factura ${p.number}`,
    clientEvtPaid: p => `Pago recibido · ${p.number}`, clientEvtChat: 'Conversación de WhatsApp',
    clientActivityEmpty: 'Aún sin actividad', clientActivityEmptyDesc: 'Las citas, servicios, presupuestos y facturas de este cliente aparecen aquí.',
    clientNoBookings: 'Aún sin citas', clientNoServices: 'Aún sin servicios', clientNoQuotes: 'Aún sin presupuestos', clientNoInvoices: 'Aún sin facturas',
    clientFinToReceive: p => `${p.amount} por cobrar`, clientFinToPay: p => `${p.amount} por pagar`, clientFinNothingToPay: 'Nada por pagar',
    clientFinNoExpenses: 'Sin gastos vinculados', clientFinMargin: p => `Margen del ${p.pct}%`, clientFinNoMargin: 'Aún sin cobros',
    clientFinExpensesHint: 'Para ver cuánto gastaste con este cliente, vincúlale los pagos al crearlos o desde el detalle de cada pago.',
    clientFinEmpty: 'Aún sin movimientos', clientFinEmptyDesc: 'Aquí aparecen las facturas de este cliente y los pagos vinculados a él.',
    clientFinThMove: 'Movimiento', clientEvtExpense: p => `Pago ${p.number}`, clientAddExpense: 'Registrar gasto', clientFinOpenPage: 'Ver en Finanzas',
    clientInvoiceOpenWork: p => `Facturar trabajo pendiente · ${p.amount}`, clientInvoiceOpenWorkTitle: 'Facturar trabajo pendiente',
    clientIssueInvoice: p => `Emitir factura · ${p.amount}`,
    clientFormEmail: 'Email', clientFormTaxId: 'NIF', clientFormNotes: 'Notas',
    clientPhEmail: 'nombre@ejemplo.es', clientPhTaxId: '12345678Z', clientPhNotes: 'Preferencias, accesos, todo lo que el equipo debe saber',
    clientNotesHint: 'Solo tu equipo ve estas notas.', clientInvalidEmail: 'Introduce un email válido',
    clientDuplicate: p => `${p.name} (${p.number}) ya usa este teléfono.`, clientOpenExisting: 'Abrir',
    recordSupplier: 'Proveedor', recordEmployee: 'Colaborador',
    supplierSince: p => `Proveedor desde ${p.date}`, employeeSince: p => `En el equipo desde ${p.date}`,
    payeePayments: p => `${p.n} ${p.n === 1 ? 'pago' : 'pagos'}`, payeeLastPaid: p => `último pago ${p.when}`,
    payeeKpiToPay: 'Por pagar', payeeKpiUnpaid: p => `${p.n} pendientes`, payeeKpiNothingDue: 'Nada por pagar',
    payeeKpiNextDue: 'Próximo vencimiento', payeeKpiNoneDue: 'Nada programado', payeeKpiPaid: 'Pagado',
    payeeAttnOverdue: p => `${p.number} vencido`, payeeNoPayments: 'Aún sin pagos',
    detailOpenRecordAria: p => `Abrir ${p.name}`, detailOpenDoc: p => `Abrir ${p.number}`,
    detailCreated: 'Creado', detailIssued: 'Emitida', detailInvoice: 'Factura',
    quoteExpiresWhen: p => `caduca ${p.when}`, quoteAlreadyInvoiced: 'Este presupuesto ya tiene factura',
    clientPhoneTaken: 'Ya existe un cliente con este teléfono (revisa también los archivados).',
    supplierPhoneTaken: 'Ya existe un proveedor con este teléfono (revisa también los archivados).',
    employeePhoneTaken: 'Ya existe un colaborador con este teléfono (revisa también los archivados).',
    settingsChannels: 'Canales', settingsWidget: 'Sitio web', settingsLanguage: 'Idioma', settingsDocuments: 'Documentos',
    widgetPreview: 'Vista previa', widgetPreviewHi: 'Hola — ¿cómo podemos ayudar?', widgetPreviewLive: 'Actualización en vivo',
    widgetContentTitle: 'Conversación', widgetAppearanceTitle: 'Apariencia',
    widgetTitleLabel: 'Nombre del asistente', widgetSubtitleLabel: 'Mensaje de estado', widgetWelcomeLabel: 'Mensaje de bienvenida',
    widgetPlaceholderLabel: 'Texto del campo', widgetLauncherLabel: 'Texto del botón', widgetAccentLabel: 'Color de marca',
    widgetPositionLabel: 'Posición', widgetPositionRight: 'Abajo a la derecha', widgetPositionLeft: 'Abajo a la izquierda',
    widgetThemeLabel: 'Tema', widgetThemeLight: 'Claro', widgetThemeDark: 'Oscuro', widgetThemeAuto: 'Configuración del dispositivo',
    widgetInstallTitle: 'Instalar en tu sitio web', widgetInstallHint: 'El fragmento se actualiza mientras personalizas. Cópialo y pégalo antes de la etiqueta </body>.',
    widgetEmptyTitle: 'Crea el chat de tu sitio web', widgetEmptyDesc: 'Genera una clave segura, adapta el asistente a tu marca y previsualiza aquí el resultado.',
    widgetDefaultTitle: 'Chat', widgetDefaultSubtitle: 'Normalmente responde al instante', widgetDefaultWelcome: '¡Hola! ¿Cómo podemos ayudarte?',
    widgetDefaultPlaceholder: 'Escribe un mensaje…', widgetDefaultLauncher: 'Chatea con nosotros',
    personaAdvanced: 'Avanzado', personaAdvancedHint: 'Instrucciones compiladas que usa el bot. Edita solo si sabes lo que cambias.',
    statMessages24h: 'Mensajes 24h', statMessages: 'Mensajes', statContacts: 'Contactos', statConversations: 'Conversaciones', statQuotes: 'Presupuestos', statInvoices: 'Facturas',
    contactsDesc: 'Usuarios finales que hablaron con el bot.',
    thName: 'Nombre', thStatus: 'Estado', thLastSeen: 'Visto', thActions: 'Acciones',
    block: 'Bloquear', unblock: 'Desbloquear',
    conversationsDesc: 'Lee y responde a tus clientes. Cuando respondes, la IA se pausa en esa conversación hasta que la reanudes.',
    thState: 'Estado', thMsgs: 'Msjs', thLast: 'Última',
    threadTitle: 'Conversación',
    assetLabel: 'Activo conectado', assetHint: 'Selecciona la Página, cuenta o número usado para enviar mensajes a clientes.',
    unnamedAsset: 'Cuenta sin nombre', recipient: 'Destinatario', noMessagingAssets: 'Conecta Instagram o WhatsApp para enviar mensajes',
    webWidgetAsset: 'Widget del sitio web', webConversationReadOnly: 'Las conversaciones del sitio web las responde el bot en directo y aquí son de solo lectura.',
    autoReplyToggleFailed: 'No se pudo cambiar la respuesta automática',
    // Bandeja de conversaciones
    channel_WHATSAPP: 'WhatsApp', channel_INSTAGRAM: 'Instagram', channel_WEB: 'Chat del sitio web',
    inboxListAria: 'Conversaciones', inboxFilterAria: 'Filtrar conversaciones', inboxAssetAria: 'Cuenta de mensajería',
    inboxFilter_all: 'Todas', inboxFilter_needs: 'Por responder', inboxFilter_unread: 'No leídas', inboxFilter_paused: 'IA en pausa',
    inboxFilterEmpty_all: 'No hay conversaciones aquí', inboxFilterEmpty_needs: 'Todos los clientes tienen respuesta',
    inboxFilterEmpty_unread: 'Lo tienes todo leído', inboxFilterEmpty_paused: 'La IA está respondiendo en todas las conversaciones',
    inboxShowAll: 'Mostrar todas', inboxSearchEmpty: 'Ninguna conversación coincide con la búsqueda',
    inboxNew: 'Nuevo mensaje', inboxEmptyTitle: 'Aún no hay conversaciones',
    inboxEmptyDesc: 'Cuando los clientes escriban a tu número, sus conversaciones aparecerán aquí.',
    inboxConnectDesc: 'Conecta WhatsApp o Instagram en Ajustes para leer y responder a los clientes aquí.',
    inboxOpenSettings: 'Abrir ajustes',
    inboxUnreadAria: p => `${p.n} sin leer`, inboxAiPrefix: 'IA: ', inboxAiOffShort: 'IA en pausa',
    inboxYou: 'Tú', inboxTeam: 'Equipo', inboxAuthorAi: 'Asistente IA',
    inboxTemplateLabel: p => `Plantilla · ${p.name}`,
    inboxBack: 'Volver a las conversaciones', inboxLogAria: p => `Mensajes con ${p.name}`,
    inboxJumpNew: 'Mensajes nuevos', inboxNewFrom: p => `Nuevo mensaje de ${p.name}`,
    inboxThreadFailed: 'No se pudo cargar esta conversación', inboxTryAgain: 'Reintentar',
    inboxNoMessagesTitle: 'Aún no hay mensajes', inboxNoMessagesDesc: 'Los mensajes con este cliente aparecerán aquí.',
    inboxMedia_image: 'Foto', inboxMedia_audio: 'Mensaje de voz', inboxMedia_video: 'Vídeo', inboxMedia_document: 'Documento',
    inboxStatusSending: 'Enviando…', inboxStatusSent: 'Enviado', inboxStatusDelivered: 'Entregado', inboxStatusRead: 'Leído', inboxStatusFailed: 'No entregado',
    inboxRetry: 'Reintentar', inboxRetried: 'Mensaje reenviado',
    inboxWindowOpen: p => `Ventana de respuesta · ${p.left}`, inboxWindowClosing: p => `La ventana cierra en ${p.left}`, inboxWindowClosed: 'Ventana de respuesta cerrada',
    inboxWindowHelp: 'WhatsApp permite respuestas libres durante 24 horas después del último mensaje del cliente. Después, solo plantillas aprobadas.',
    inboxAiOn: 'IA respondiendo', inboxAiPaused: 'IA en pausa', inboxAiPause: 'Pausar IA', inboxAiResume: 'Reanudar IA',
    inboxAiPausedTitle: 'IA en pausa en esta conversación',
    inboxAiPausedDesc: 'Los nuevos mensajes del cliente se guardan aquí, pero no recibirán respuesta automática hasta que reanudes la IA.',
    inboxPausedBy: p => `Pausada por ${p.who}`,
    inboxAiPausedToast: 'IA en pausa en esta conversación', inboxAiResumedToast: 'La IA volverá a responder a este cliente',
    inboxSent: 'Mensaje enviado', inboxSentAiPaused: 'Mensaje enviado · IA en pausa mientras atiendes esta conversación',
    inboxComposerAria: 'Tu respuesta', inboxComposerPlaceholder: p => `Responder a ${p.name}…`,
    inboxComposerHint: 'Enter para enviar · Shift+Enter para una nueva línea',
    inboxCharsLeft: p => `Quedan ${p.n} caracteres`, inboxCharsOver: p => `${p.n} caracteres por encima del límite`,
    inboxClosingSoon: p => `La ventana de respuesta cierra en ${p.left}. Después, solo se podrán enviar plantillas.`,
    inboxSend: 'Enviar', inboxSending: 'Enviando…', inboxSendTemplate: 'Enviar plantilla',
    inboxTemplateButton: 'Plantilla', inboxTemplateButtonTitle: 'Enviar una plantilla aprobada de WhatsApp',
    inboxWindowClosedTitle: 'La ventana de respuesta de 24 horas está cerrada',
    inboxWindowClosedDesc: 'WhatsApp solo permite plantillas aprobadas hasta que el cliente vuelva a escribir.',
    inboxNeverWroteTitle: 'Empieza con una plantilla',
    inboxNeverWroteDesc: 'Este cliente aún no te ha escrito, así que WhatsApp solo permite una plantilla aprobada.',
    inboxNoChannel: 'Esta cuenta ya no está conectada. Vuelve a conectarla en Ajustes para responder.',
    inboxNewTitle: 'Nuevo mensaje de WhatsApp', inboxTemplateTitleTo: p => `Plantilla para ${p.name}`,
    inboxPhoneLabel: 'Número de WhatsApp', inboxPhonePlaceholder: '+34 612 345 678',
    inboxPhoneHint: 'Incluye el prefijo del país. El primer mensaje a un contacto nuevo debe ser una plantilla aprobada.',
    inboxTemplateField: 'Plantilla', inboxTemplateVar: p => `Variable {{${p.name}}}`,
    inboxTemplateNoVars: 'Esta plantilla no tiene variables.', inboxTemplatePreview: 'Vista previa',
    inboxTemplateHint: 'Las plantillas se pueden enviar en cualquier momento, incluso después de que se cierre la ventana de respuesta.',
    inboxTemplateHintNew: 'La conversación se abre en tu bandeja con la IA en pausa hasta que la reanudes.',
    inboxTemplateUnsupportedShort: 'no compatible aquí',
    inboxTemplateCategory_MARKETING: 'Marketing', inboxTemplateCategory_UTILITY: 'Utilidad', inboxTemplateCategory_AUTHENTICATION: 'Autenticación',
    inboxTemplatesEmptyTitle: 'Aún no hay plantillas aprobadas',
    inboxTemplatesEmptyDesc: 'Crea una aquí. Podrás enviarla en cuanto Meta la apruebe.',
    inboxTemplatesManage: 'Gestionar plantillas', inboxTemplatesRefresh: 'Actualizar',
    inboxTemplatesFailedTitle: 'No se pudieron cargar las plantillas', inboxTemplateSent: 'Plantilla enviada',
    inboxErr_window_closed: 'La ventana de respuesta de 24 horas está cerrada. Envía una plantilla aprobada.',
    inboxErr_recipient_not_allowed: 'Este número de prueba solo puede escribir a los números de su lista de destinatarios en el App Dashboard de Meta.',
    inboxErr_undeliverable: 'WhatsApp no pudo entregar este mensaje. Puede que el número no use WhatsApp.',
    inboxErr_marketing_limited: 'Meta retuvo este mensaje de marketing para proteger la experiencia del cliente.',
    inboxErr_rate_limited: 'Demasiados mensajes en poco tiempo. Espera un momento y vuelve a intentarlo.',
    inboxErr_template_params: 'Completa todas las variables de la plantilla.',
    inboxErr_template_unavailable: 'Esta plantilla está en pausa, desactivada o no existe en ese idioma.',
    inboxErr_template_not_found: 'Esa plantilla ya no existe. Actualiza la lista y elige otra.',
    inboxErr_template_unsupported: 'Esta plantilla necesita multimedia o botones que no se pueden completar aquí.',
    inboxErr_not_registered: 'Este número de WhatsApp aún no está registrado en Meta.',
    inboxErr_account_restricted: 'Meta ha restringido esta cuenta de WhatsApp. Revisa WhatsApp Manager.',
    inboxErr_token_invalid: 'La conexión con WhatsApp caducó. Vuelve a conectar WhatsApp en Ajustes.',
    inboxErr_permission_denied: 'Esta aplicación aún no tiene permiso para enviar desde esta cuenta de WhatsApp.',
    inboxErr_invalid_text: 'Escribe un mensaje de hasta 4096 caracteres.',
    inboxErr_invalid_phone: 'Introduce el número completo, con el prefijo del país.',
    inboxErr_no_channel: 'No hay ningún número de WhatsApp conectado.',
    inboxErr_no_waba: 'Las plantillas necesitan una cuenta de WhatsApp conectada con el registro de Meta en Ajustes.',
    inboxErr_templates_failed: 'Meta no devolvió las plantillas. Inténtalo de nuevo en un momento.',
    inboxErr_not_retryable: 'Este mensaje no se puede reenviar.',
    inboxErr_not_found: 'Esta conversación o mensaje ya no existe.',
    inboxErr_web_read_only: 'Las conversaciones del sitio web las responde el bot y aquí son de solo lectura.',
    inboxErr_templates_whatsapp_only: 'Las plantillas solo son para conversaciones de WhatsApp.',
    inboxErr_asset_mismatch: 'Esta conversación pertenece a otra cuenta.',
    inboxErr_send_failed: 'No se pudo enviar el mensaje.',
    inboxMediaExpand: 'Ver más grande', inboxMediaDownload: 'Descargar',
    inboxErr_media_unavailable: 'Este archivo ya no está disponible. Meta guarda los archivos de los clientes durante 30 días.',
    inboxErr_media_too_large: 'Este archivo es demasiado grande para abrirlo aquí. Ábrelo en WhatsApp.',
    inboxErr_template_name_invalid: 'Usa letras minúsculas, números y guiones bajos en el nombre.',
    inboxErr_template_language_invalid: 'Elige un idioma para la plantilla.',
    inboxErr_template_category_invalid: 'Elige Utilidad o Marketing.',
    inboxErr_template_header_invalid: 'El encabezado admite hasta 60 caracteres, en una línea y sin variables.',
    inboxErr_template_footer_invalid: 'El pie admite hasta 60 caracteres, en una línea y sin variables.',
    inboxErr_template_body_invalid: 'Escribe el mensaje, con hasta 1024 caracteres.',
    inboxErr_template_variables_invalid: 'Numera las variables {{1}}, {{2}}… en orden y no empieces ni termines el mensaje con una.',
    inboxErr_template_examples_missing: 'Da un ejemplo para cada variable para que Meta pueda revisar la plantilla.',
    inboxErr_template_buttons_invalid: 'Usa hasta 3 respuestas rápidas distintas, de hasta 25 caracteres.',
    inboxErr_template_create_failed: 'Meta no aceptó la plantilla.',
    inboxErr_template_delete_failed: 'Meta no eliminó la plantilla.',
    // Plantillas de WhatsApp (Ajustes)
    settingsTemplates: 'Plantillas de WhatsApp',
    tplTitle: 'Plantillas de mensaje', tplNew: 'Nueva plantilla',
    tplIntro: 'WhatsApp solo permite iniciar una conversación, o responder después de 24 horas, con una plantilla aprobada por Meta. Las plantillas nuevas suelen revisarse en pocos minutos.',
    tplEmptyDesc: 'Crea una plantilla para recordatorios, confirmaciones o seguimientos. Podrás enviarla desde cualquier conversación en cuanto Meta la apruebe.',
    tplColName: 'Plantilla', tplColLanguage: 'Idioma', tplColCategory: 'Categoría', tplColStatus: 'Estado',
    tplStatus_APPROVED: 'Aprobada', tplStatus_PENDING: 'En revisión', tplStatus_REJECTED: 'Rechazada', tplStatus_PAUSED: 'En pausa', tplStatus_DISABLED: 'Desactivada', tplStatus_IN_APPEAL: 'En apelación',
    tplRejectedReason: p => `Motivo: ${p.reason}`,
    tplDelete: 'Eliminar', tplDeleteAria: p => `Eliminar la plantilla ${p.name}`,
    tplDeleteTitle: '¿Eliminar esta plantilla?',
    tplDeleteBody: p => `${p.name} (${p.language}) se eliminará de WhatsApp. Meta no permite reutilizar el nombre durante 4 semanas.`,
    tplDeleted: 'Plantilla eliminada',
    tplNewTitle: 'Nueva plantilla de WhatsApp',
    tplFieldName: 'Nombre', tplNamePlaceholder: 'recordatorio_cita', tplNameHint: 'Solo lo ves tú. Letras minúsculas, números y guiones bajos.',
    tplFieldCategory: 'Categoría', tplFieldLanguage: 'Idioma', tplFieldHeader: 'Encabezado', tplOptional: 'opcional',
    tplFieldBody: 'Mensaje', tplAddVariable: 'Añadir variable',
    tplBodyHint: 'Usa {{1}}, {{2}}… para los datos que cambian, como un nombre o una hora.',
    tplExampleFor: p => `Ejemplo para {{${p.name}}}`, tplExamplePlaceholder: 'p. ej., Ana',
    tplFieldFooter: 'Pie', tplFieldButtons: 'Respuestas rápidas', tplAddButton: 'Añadir respuesta rápida',
    tplButtonLabel: p => `Respuesta rápida ${p.n}`, tplRemoveButton: 'Quitar respuesta rápida',
    tplCategoryUtilityHint: 'Confirmaciones, recordatorios y novedades sobre algo que el cliente pidió.',
    tplCategoryMarketingHint: 'Ofertas, novedades e invitaciones. Meta puede limitar la frecuencia con que los clientes las reciben.',
    tplReviewHint: 'Meta revisa cada plantilla antes de poder enviarla. Los ejemplos ayudan a aprobarla.',
    tplPreviewEmpty: 'Escribe el mensaje para ver cómo quedará.',
    tplSubmit: 'Enviar a revisión',
    tplSubmittedToast: 'Plantilla enviada. Meta suele revisarla en pocos minutos.',
    tplApprovedToast: 'Plantilla aprobada y lista para enviar',
    openChat: 'Abrir chat',
    clientsDesc: 'CRM · Clientes.', thPhone: 'Teléfono', thAddress: 'Dirección', thNo: 'Nº',
    quotesDesc: 'CRM · Propuestas comerciales.', thNumber: 'Número', thClient: 'Cliente', thTotal: 'Total',
    invoicesDesc: 'CRM · Facturas emitidas.', thDueDate: 'Vencimiento',
    thPdf: 'PDF', thPdfActions: 'PDF · Acciones', viewPdf: 'Ver PDF', pdfPending: 'pendiente',
    errorPdf: p => `Error PDF: ${p.msg}`, loadFailed: 'No se pudo cargar esta sección',
    markPaid: 'Marcar pagada', markedPaid: p => `Factura ${p.number} marcada como pagada`, markPaidFailed: 'No se pudo marcar la factura como pagada',
    invoiceFromQuote: p => `Del presupuesto ${p.number}`, paidOnLabel: 'Pagada el',
    catalogDesc: 'CRM · Servicios y materiales estándar.', thType: 'Tipo', thCategory: 'Categoría', thDescription: 'Descripción', thUnit: 'Unid.', thPrice: 'Precio',
    personaDesc: 'Personalidad del bot — sintetizada a partir de las notas y archivos que subes.',
    personaCompiling: 'Sintetizando…', statVersion: 'Versión', statTokens: 'Tokens est.', statUpdated: 'Actualizado',
    testBotTitle: 'Probar el bot', clear: 'Limpiar',
    testBotDesc: 'Chatea con el bot usando la persona actual para probar el tono y las respuestas. Los mensajes de prueba no se guardan y no crean clientes, presupuestos ni facturas.',
    chatPlaceholder: 'Escribe un mensaje de prueba…', send: 'Enviar',
    chatEmpty: 'Envía un mensaje para probar la persona del bot.', typing: 'escribiendo…', chatError: '⚠️ Error al contactar con el bot. Inténtalo de nuevo.',
    addInfoTitle: 'Añadir información',
    addInfoDesc: 'Escribe una nota o sube un archivo (PDF, TXT, MD). Se sintetiza en el archivo de instrucciones de abajo.',
    noteLabel: 'Nota', notePlaceholder: 'P. ej.: Somos una clínica dental en Lisboa. Tono cálido, trato formal...', addNote: 'Añadir nota',
    fileLabel: 'Archivo', fileHint: 'PDF, TXT o Markdown. El texto se extrae y se sintetiza.',
    sourcesTitle: 'Fuentes', sourcesDesc: 'Material en bruto que alimenta la síntesis.', rebuildAll: 'Recompilar todo',
    sourceSynced: 'sincronizado', sourcePending: 'pendiente', remove: 'Quitar',
    thSource: 'Fuente', thCreated: 'Creado',
    noSourcesTitle: 'Aún sin fuentes', noSourcesDesc: 'Añade una nota o archivo arriba.',
    compiledTitle: 'Archivo de instrucciones compilado',
    compiledDesc: 'Resultado de la síntesis. Puedes editarlo manualmente; la próxima síntesis lo revisará.',
    compiledPlaceholder: 'Todavía vacío — añade información arriba para dar personalidad al bot.',
    saveManual: 'Guardar edición manual',
    personaSaved: 'Persona guardada', noteAdded: 'Nota añadida — sintetizando', fileUploaded: 'Archivo subido — sintetizando', rebuildStarted: 'Recompilación iniciada', uploadFailed: 'Error al subir',
    assistantDesc: 'Pregunta sobre los datos del negocio y completa tareas del panel con tu aprobación.',
    assistantNewThread: 'Nueva conversación', assistantNoThreads: 'Todavía no hay conversaciones',
    assistantEmpty: 'Empieza preguntando por clientes, catálogo, presupuestos o facturas.', assistantPlaceholder: 'Pregunta al asistente…',
    assistantError: 'El asistente no pudo responder. Inténtalo de nuevo.', assistantActionError: 'No se pudo actualizar la acción.',
    assistantProposedAction: 'Acción propuesta', assistantConfirm: 'Confirmar acción', assistantCancel: 'Cancelar',
    assistantStatusPENDING: 'Esperando aprobación', assistantStatusEXECUTING: 'En curso', assistantStatusCONFIRMED: 'Completada', assistantStatusFAILED: 'Fallida', assistantStatusCANCELLED: 'Cancelada',
    assistantCreateClient: p => `Crear cliente ${p.name}`, assistantCreateQuote: 'Crear presupuesto', assistantUpdateQuote: p => `Actualizar presupuesto ${p.id}`,
    assistantCreateInvoice: 'Crear factura', assistantMarkPaid: p => `Marcar factura ${p.id} como pagada`, assistantChangeData: 'Cambiar datos del panel',
    assistantClientRef: p => `Cliente: ${p.id}`, assistantQuoteRef: p => `Presupuesto: ${p.id}`, assistantInvoiceRef: p => `Factura: ${p.id}`,
    assistantValidUntil: p => `Válido hasta: ${p.date}`, assistantDueDate: p => `Vencimiento: ${p.date}`, assistantNewStatus: p => `Nuevo estado: ${p.status}`,
    assistantDownloadPdf: p => p.number ? `Descargar PDF ${p.number}` : 'Descargar PDF',
    bookingsDesc: 'Citas de los servicios de tu catálogo, vinculadas a clientes y facturadas al completarse.',
    bookingsWeek: 'Semana', bookingsAgenda: 'Agenda', bookingsAgendaTitle: p => `Próximos ${p.days} días`,
    bookingsPrev: 'Semana anterior', bookingsNext: 'Semana siguiente', bookingsToday: 'Esta semana',
    bookingsStatToday: 'Hoy', bookingsStatWeek: 'Semana', bookingsStatPending: 'Por confirmar', bookingsStatValue: 'Valor de la semana',
    bookingsNew: 'Nueva cita', bookingsEdit: 'Editar cita', bookingsSave: 'Guardar cita', bookingsNewForClient: 'Nueva cita',
    bookingsContactName: 'Nombre del contacto', bookingsContactPhone: 'Teléfono', bookingsService: 'Servicio',
    bookingsStart: 'Inicio', bookingsNotes: 'Notas', bookingsStatus: 'Estado', bookingsSource: 'Origen', bookingsOptional: 'opcional',
    bookingsDate: 'Fecha', bookingsTime: 'Hora', bookingsDurationShort: 'Duración (min)', bookingsPrice: 'Precio €',
    bookingsFreeTimes: 'Horas libres', bookingsNoFreeTimes: 'No hay horas libres este día', bookingsPickServiceFirst: 'Elige un servicio y una fecha para ver las horas libres',
    bookingsOutsideHours: 'Fuera del horario de apertura — puedes guardarla igualmente.',
    bookingsChooseService: '— Elegir servicio —', bookingsCreated: 'Cita creada', bookingsUpdated: 'Cita actualizada',
    bookingsConflict: 'Ese horario se solapa con otra cita', bookingsValidate: 'Completa servicio, fecha, hora, nombre y teléfono',
    bookingsSaveFailed: 'No se pudo guardar la cita', bookingsStatusChanged: p => `Cita: ${p.status}`,
    bookingsLinkedClient: p => `Vinculada al cliente ${p.name}.`, bookingsUnlink: 'Desvincular',
    bookingsClientHint: 'Escribe para buscar un cliente. Un contacto nuevo se guarda como cliente.',
    bookingsClientNoShows: p => `${p.n} ${p.n === 1 ? 'ausencia' : 'ausencias'}`,
    bookingsToConfirm: 'Por confirmar', bookingsToConfirmAll: 'Ver todas',
    bookingsConfirm: 'Confirmar', bookingsDecline: 'Rechazar', bookingsComplete: 'Completar', bookingsNoShow: 'No vino',
    bookingsCancel: 'Cancelar cita', bookingsReopen: 'Reabrir', bookingsEditAction: 'Editar', bookingsBack: 'Volver', bookingsOpenService: 'Abrir servicio',
    bookingsInvoice: 'Facturar', bookingsInvoiced: 'Facturada', bookingsBilled: 'Añadida a Servicios, lista para facturar.',
    bookingsCancelConfirmTitle: '¿Cancelar esta cita?', bookingsCancelConfirmBody: p => `${p.name} · ${p.when}. El horario queda libre para otras citas.`,
    bookingsCancelOk: 'Cancelar cita',
    bookingsSetupTitle: 'Configurar reservas',
    bookingsSetupServices: 'Elegir servicios reservables', bookingsSetupServicesDesc: 'Activa la reserva en servicios del catálogo y define cuánto dura cada uno.',
    bookingsSetupHours: 'Definir horario', bookingsSetupHoursDesc: 'Los clientes solo pueden reservar dentro de este horario.',
    bookingsManageServices: 'Servicios', bookingsManageAvailability: 'Horario',
    bookingsServicesHint: 'Estos son los servicios de tu catálogo. Marca los que los clientes pueden reservar y define cuánto dura cada uno.',
    bookingsBookable: 'Reservable', bookingsGoCatalog: 'Editar nombres y precios en Catálogo',
    bookingsNoServices: 'No hay servicios en el catálogo', bookingsNoServicesDesc: 'Añade uno abajo — también queda en el catálogo.',
    bookingsServiceName: 'Nombre del servicio', bookingsServiceSaved: 'Servicio guardado', bookingsAddService: 'Añadir servicio',
    bookingsHoursHint: 'Horario para citas. Añade un segundo tramo el mismo día para la pausa de la comida.',
    bookingsHoursInvalid: 'Cada tramo debe terminar después de empezar', bookingsRemoveWindow: 'Quitar tramo',
    bookingsAvailabilitySaved: 'Horario guardado', bookingsSaveHours: 'Guardar horario',
    bookingsAddWindow: 'Añadir tramo', bookingsDay: 'Día', bookingsFrom: 'Desde', bookingsTo: 'Hasta',
    bookingsEmptyList: 'No se encontraron citas',
    bookingsEmptyAgenda: 'Aún no hay citas', bookingsEmptyAgendaDesc: 'Las nuevas citas del panel, de WhatsApp y del asistente aparecen aquí.',
    bookingsThWhen: 'Cuándo', bookingsThContact: 'Contacto', bookingsThService: 'Servicio', bookingsThStatus: 'Estado', bookingsStatusAll: 'Todas',
    bookingStatusPENDING: 'Pendiente', bookingStatusCONFIRMED: 'Confirmada', bookingStatusCANCELLED: 'Cancelada', bookingStatusCOMPLETED: 'Completada', bookingStatusNO_SHOW: 'No vino',
    bookingsSourceDASHBOARD: 'Panel', bookingsSourceADMIN: 'Backoffice', bookingsSourceWHATSAPP: 'WhatsApp',
    bookingsSourceINSTAGRAM: 'Instagram', bookingsSourceWEB: 'Chat web', bookingsSourceASSISTANT: 'Asistente IA',
    bookingsErr_conflict: 'Ese horario se solapa con otra cita', bookingsErr_outside_hours: 'Esa hora está fuera del horario de apertura',
    bookingsErr_in_past: 'Esa hora ya pasó', bookingsErr_service_not_bookable: 'Ese servicio no se puede reservar',
    bookingsErr_service_not_found: 'Ese servicio ya no existe', bookingsErr_contact_required: 'Indica el nombre y el teléfono del contacto',
    bookingsErr_invalid_time: 'Revisa la fecha, la hora y la duración', bookingsErr_client_not_found: 'Ese cliente ya no existe',
    bookingsErr_booking_not_found: 'Esa cita ya no existe',
    assistantCreateBooking: 'Crear cita', assistantRescheduleBooking: 'Mover cita', assistantCancelBooking: 'Cancelar cita',
    assistantConfirmBooking: 'Confirmar cita', assistantBookingRef: p => `Cita: ${p.id}`,
    weekday1: 'Lun', weekday2: 'Mar', weekday3: 'Mié', weekday4: 'Jue', weekday5: 'Vie', weekday6: 'Sáb', weekday7: 'Dom',
    instagramDesc: 'Revisa los comentarios de tus publicaciones de Instagram y responde desde aquí.',
    instagramNeedsReply: 'Necesita respuesta', instagramPosts: 'Publicaciones',
    instagramEmptyComments: 'Ningún comentario pendiente',
    instagramEmptyCommentsDesc: 'Los comentarios nuevos de tus publicaciones aparecerán aquí.',
    instagramEmptyPosts: 'Aún no hay publicaciones',
    instagramEmptyPostsDesc: 'Conecta Instagram, publica y vuelve a abrir esta página.',
    instagramNotConnected: 'Instagram no está conectado',
    instagramNotConnectedDesc: 'Conecta tu cuenta profesional en Ajustes para ver publicaciones y comentarios.',
    instagramReconnectBanner: 'Vuelve a conectar Instagram para revisar los comentarios de tus publicaciones.',
    instagramThPost: 'Publicación', instagramThComment: 'Comentario', instagramThFrom: 'De', instagramThWhen: 'Cuándo',
    instagramReply: 'Responder', instagramReplyPlaceholder: 'Escribe una respuesta pública…',
    instagramReplied: 'Respuesta enviada', instagramReplyFailed: 'No se pudo enviar la respuesta',
    instagramOpenPost: 'Abrir en Instagram', instagramUnreplied: 'Sin respuesta',
    instagramNoCaption: 'Sin pie de foto', instagramGoSettings: 'Abrir Ajustes',
    instagramSyncFailed: 'No se pudo actualizar Instagram',
  },

  admin: {
    nav: { clientes: 'Clientes', servicos: 'Servicios', orcamentos: 'Presupuestos', faturas: 'Facturas', fornecedores: 'Proveedores', colaboradores: 'Colaboradores', pagamentos: 'Pagos', items: 'Ítems estándar', bookings: 'Reservas' },
    crumbRoot: 'Panel',
    brandSub: 'Tenant · Gestión',
    searchPlaceholder: 'Buscar en esta vista…',
    export: 'Exportar', exportTitle: 'Exportar CSV', exportSoon: 'Exportar · próximamente',
    backoffice: '← Backoffice', themeAria: 'Cambiar tema', closeAria: 'Cerrar',
    kpiReceivable: 'Por cobrar', kpiPaid: 'Recibido este mes',
    saving: 'Guardando…', cancel: 'Cancelar', save: 'Guardar', confirm: 'Confirmar', delete: 'Eliminar',
    loading: 'Cargando…', loadError: 'Error al cargar',
    login: { eyebrow: p => `thebots.lab / ${p.tenant}`, title: 'Entrar al CRM', desc: 'Usa la contraseña de operador para abrir este panel de gestión.', password: 'Contraseña', submit: 'Entrar', invalid: 'Acceso inválido', crumb: 'Acceso' },
    invalidTenantTitle: 'Tenant inválido', invalidTenantDesc: 'Vuelve al backoffice y abre un CRM válido.',
    titleSuffix: 'Panel de Gestión',
    pdfPending: 'pendiente',
    errorPdf: p => `Error PDF: ${p.msg}`,
    error: p => `Error: ${p.msg}`,
    quoteStatus: { PENDENTE: 'Pendiente', SENT: 'Enviado', ACEITO: 'Aceptado' },
    invoiceStatus: { PENDING: 'Pendiente', PAID: 'Pagada', OVERDUE: 'Vencida', CANCELLED: 'Cancelada' },
    paymentStatus: { PENDING: 'Pendiente', PAID: 'Pagado', OVERDUE: 'Vencido', CANCELLED: 'Cancelado' },
    tabs: {
      clientes: { title: 'Clientes', desc: 'Directorio de clientes de la empresa.', newLabel: 'Nuevo cliente' },
      orcamentos: { title: 'Presupuestos', desc: 'Propuestas comerciales emitidas.', newLabel: 'Nuevo presupuesto' },
      faturas: { title: 'Facturas', desc: 'Facturas emitidas y su estado.', newLabel: 'Nueva factura' },
      items: { title: 'Ítems estándar', desc: 'Catálogo de servicios y materiales para presupuestos y facturas.', newLabel: 'Nuevo ítem' },
      servicos: { title: 'Servicios', desc: 'Trabajo ligado a un cliente. Agrupa filas abiertas en una sola factura.', newLabel: 'Nuevo servicio' },
      fornecedores: { title: 'Proveedores', desc: 'Personas y empresas a las que pagas.', newLabel: 'Nuevo proveedor' },
      colaboradores: { title: 'Colaboradores', desc: 'Personas del equipo. Registra un pago desde aquí.', newLabel: 'Nuevo colaborador' },
      pagamentos: { title: 'Pagos', desc: 'Cuentas ligadas a un proveedor o a un colaborador. Márcalas pagadas cuando salga el dinero.', newLabel: 'Nuevo pago' },
      financeiro: { title: 'Finanzas', desc: 'Dinero recibido y gastado, por semana o por mes.' },
      bookings: { title: 'Reservas', desc: 'Citas de los servicios de tu catálogo, vinculadas a clientes y facturadas al completarse.', newLabel: 'Nueva cita' },
    },
    clients: {
      total: 'Total', new30: 'Nuevos · 30d', directory: 'Directorio',
      one: 'cliente', many: 'clientes',
      thName: 'Nombre', thAddress: 'Dirección', thPhone: 'Teléfono', thCreated: 'Creado', thNo: 'Nº Cliente',
      emptyTitle: 'No se encontraron clientes', emptyDesc: 'Ajusta la búsqueda o crea un nuevo cliente.',
      formName: 'Nombre', formAddress: 'Dirección', formPhone: 'Teléfono',
      phName: 'Ej: Manuel Costa, S.L.', phAddress: 'Ej: Calle de las Flores 12, 1200-001 Lisboa', phPhone: '+351 912 345 678',
      eyebrow: 'Clientes', formTitle: 'Nuevo cliente', saveLabel: 'Crear cliente',
      validate: 'Introduce nombre y teléfono', created: p => `Cliente creado · ${p.name}`,
    },
    quotes: {
      total: 'Total', sent: 'Abiertos', accepted: 'Aceptados', proposals: 'Propuestas', filterAll: 'Todos',
      thNumber: 'Número', thClient: 'Cliente', thStatus: 'Estado', thValidUntil: 'Válido hasta', thTotal: 'Total', thPdf: 'PDF',
      emptyTitle: 'Sin presupuestos', emptyDesc: 'Crea el primer presupuesto con el botón de arriba.',
      validUntil: 'Válido hasta', optional: 'opcional', notes: 'Notas', notesPlaceholder: 'Notas internas, condiciones, plazos…',
      eyebrow: 'Presupuestos', formTitle: 'Nuevo presupuesto', saveLabel: 'Crear presupuesto',
      chooseClient: 'Elige un cliente', addLine: 'Añade al menos una línea', created: 'Presupuesto creado',
    },
    services: {
      open: 'Abierto', invoiced: 'Facturado', cancelled: 'Cancelado', work: 'Trabajo del cliente', filterAll: 'Todos',
      viewList: 'Lista', byWeek: 'Por semana', byMonth: 'Por mes', summaryWeek: 'Resumen de la semana', summaryMonth: 'Resumen del mes',
      periodPrev: 'Anterior', periodNext: 'Siguiente', periodCurrent: 'Actual',
      vsPrev: p => `frente al anterior · ${p.delta}`,
      thPeriod: 'Periodo', thCount: 'Servicios',
      summaryEmpty: 'Nada en este resumen', summaryEmptyDesc: 'El trabajo aparece aquí cuando tiene fecha.',
      thWhen: 'Cuándo', thClient: 'Cliente', thService: 'Servicio', thQty: 'Cant.', thTotal: 'Total', thStatus: 'Estado',
      emptyTitle: 'Aún no hay servicios', emptyDesc: 'Liga trabajo a un cliente y factura varias filas a la vez.',
      emptyFiltered: 'No hay servicios en este filtro', emptyFilteredDesc: 'Prueba con otro cliente o limpia los filtros.',
      filterClientAll: 'Todos los clientes',
      formTitle: 'Nuevo servicio', editTitle: 'Editar servicio', save: 'Guardar servicio',
      name: 'Servicio', namePh: 'Ej.: Pintura de fachada',
      fromCatalog: 'Del catálogo', fromBooking: 'de una cita', fromCatalogNone: '— Servicio a medida —',
      qty: 'Cantidad', unit: 'Unidad', price: 'Precio unitario €', when: 'Realizado el', notes: 'Notas',
      validate: 'Elige un cliente y nombra el servicio',
      created: 'Servicio añadido', updated: 'Servicio actualizado', saveFailed: 'No se pudo guardar el servicio',
      cancel: 'Cancelar servicio', cancelConfirmTitle: '¿Cancelar este servicio?',
      cancelConfirmBody: p => `"${p.name}" se queda en la lista como cancelado y ya no se puede facturar.`,
      cancelOk: 'Cancelar servicio', cancelled: 'Servicio cancelado', cancelFailed: 'No se pudo cancelar el servicio',
      delete: 'Eliminar servicio', deleteConfirmTitle: '¿Eliminar este servicio?',
      deleteConfirmBody: p => `"${p.name}" se eliminará. Esta acción no se puede deshacer.`,
      deleteOk: 'Eliminar servicio', deleted: 'Servicio eliminado', deleteFailed: 'No se pudo eliminar el servicio',
      invoicedLocked: 'Este servicio ya fue facturado y no se puede cambiar, cancelar ni eliminar.',
      invoiceSelected: 'Facturar seleccionados', invoiceDue: 'Vencimiento de la factura',
      invoiceNeedSameClient: 'Selecciona servicios abiertos del mismo cliente',
      invoiceNeedRows: 'Selecciona al menos un servicio abierto',
      issuedFrom: p => `Factura ${p.number} emitida a partir de los servicios`,
      invoiceFailed: 'No se pudieron facturar estos servicios',
      addForClient: 'Añadir servicio',
      invoiceNow: 'Facturar', reopen: 'Reabrir', reopened: 'Servicio reabierto', reopenFailed: 'No se pudo reabrir el servicio', openBooking: 'Abrir cita',
    },
    suppliers: {
      total: 'Total', new30: 'Nuevos · 30d', directory: 'Directorio', filterAll: 'Todos los proveedores',
      thName: 'Nombre', thAddress: 'Dirección', thPhone: 'Teléfono', thCreated: 'Creado', thNo: 'Nº Proveedor',
      emptyTitle: 'Aún no hay proveedores', emptyDesc: 'Añade un proveedor y luego registra pagos.',
      formTitle: 'Nuevo proveedor', editTitle: 'Editar proveedor', save: 'Guardar proveedor',
      formName: 'Nombre', formPhone: 'Teléfono', formAddress: 'Dirección',
      phName: 'Ej.: Tintas Norte, S.L.', phPhone: '+351 210 000 000', phAddress: 'Ej.: Zona Industrial, Porto',
      validate: 'Indica nombre y teléfono',
      created: 'Proveedor añadido', updated: 'Proveedor actualizado', saveFailed: 'No se pudo guardar el proveedor',
      addPayment: 'Añadir pago',
    },
    employees: {
      total: 'Total', new30: 'Nuevos · 30d', directory: 'Directorio',
      thName: 'Nombre', thRole: 'Función', thPhone: 'Teléfono', thCreated: 'Creado', thNo: 'Nº Colaborador',
      emptyTitle: 'Aún no hay colaboradores', emptyDesc: 'Añade a las personas del equipo y luego registra pagos.',
      addPayment: 'Añadir pago',
      formTitle: 'Nuevo colaborador', editTitle: 'Editar colaborador', save: 'Guardar colaborador',
      formName: 'Nombre', formPhone: 'Teléfono', formRole: 'Función',
      phName: 'Ej.: Ana Costa', phPhone: '+351 912 345 678', phRole: 'Ej.: Pintor',
      validate: 'Indica nombre y teléfono',
      created: 'Colaborador añadido', updated: 'Colaborador actualizado', saveFailed: 'No se pudo guardar el colaborador',
    },
    payments: {
      paid: 'Pagado', pending: 'Por pagar', overdue: 'Vencido', ledger: 'Salidas', filterAll: 'Todos',
      filterSupplierAll: 'Todos los proveedores', filterPayeeAll: 'Todos',
      thNumber: 'Número', thSupplier: 'Proveedor', thEmployee: 'Colaborador', thPayee: 'Pagado a', thStatus: 'Estado', thDueDate: 'Vencimiento', thTotal: 'Total',
      emptyTitle: 'Aún no hay pagos', emptyDesc: 'Registra una cuenta de un proveedor o colaborador y márcala como pagada.',
      emptyFiltered: 'No hay pagos en este filtro', emptyFilteredDesc: 'Prueba con otra persona o limpia los filtros.',
      formTitle: 'Nuevo pago', save: 'Guardar pago',
      payee: 'Pagar a', paySupplier: 'Proveedor', payEmployee: 'Colaborador',
      chooseSupplier: 'Elige un proveedor', chooseSupplierEmpty: '— Elegir proveedor —',
      chooseEmployee: 'Elige un colaborador', chooseEmployeeEmpty: '— Elegir colaborador —',
      needSupplier: 'Añade un proveedor primero', needEmployee: 'Añade un colaborador primero', needPayee: 'Añade un proveedor o un colaborador primero',
      enterDueDate: 'Indica la fecha de vencimiento', addLine: 'Añade al menos una línea',
      amount: 'Importe €', enterAmount: 'Indica el importe',
      generalEntry: 'Descripción', generalEntryValue: 'Pago',
      notes: 'Notas', notesPh: 'Nota interna…',
      client: 'Cliente', clientNone: '— Sin cliente —', noClient: 'Sin cliente',
      clientHint: 'Vincula el gasto al cliente para el que se hizo: cuenta como gastado en las finanzas de ese cliente.',
      linkClient: 'Vincular a un cliente', changeClient: 'Cambiar cliente', clientFormTitle: 'Cliente del pago', clientSave: 'Guardar',
      clientSaved: 'Cliente del pago actualizado', clientSaveFailed: 'No se pudo actualizar el cliente',
      created: 'Pago registrado', saveFailed: 'No se pudo guardar el pago',
      markPaid: 'Marcar pagado', markedPaid: p => `Pago ${p.number} marcado como pagado`,
      markPaidFailed: 'No se pudo marcar este pago como pagado',
      markPaidConfirmTitle: '¿Marcar este pago como pagado?',
      markPaidConfirmBody: p => `Esto registra que ${p.number} se pagó.`,
    },
    invoices: {
      paid: 'Pagado', pending: 'Pendiente', overdue: 'Vencido', documents: 'Documentos', filterAll: 'Todos',
      viewList: 'Lista', byWeek: 'Por semana', byMonth: 'Por mes', summaryWeek: 'Resumen de la semana', summaryMonth: 'Resumen del mes',
      periodPrev: 'Anterior', periodNext: 'Siguiente', periodCurrent: 'Actual',
      vsPrev: p => `frente al anterior · ${p.delta}`,
      thPeriod: 'Periodo', thCount: 'Facturas',
      summaryEmpty: 'Nada en este resumen', summaryEmptyDesc: 'Las facturas aparecen aquí cuando se emiten.',
      thNumber: 'Número', thClient: 'Cliente', thStatus: 'Estado', thDueDate: 'Vencimiento', thTotal: 'Total', thPdfActions: 'PDF · Acciones',
      emptyTitle: 'Sin facturas', emptyDesc: 'Emite la primera factura con el botón de arriba.',
      markPaid: 'Marcar pagada', markedPaid: p => `Factura ${p.number} marcada como pagada`,
      dueDate: 'Vencimiento', quoteId: 'ID Presupuesto', quoteIdPlaceholder: 'ID del presupuesto asociado',
      eyebrow: 'Facturas', formTitle: 'Nueva factura', saveLabel: 'Emitir factura',
      chooseClient: 'Elige un cliente', enterDueDate: 'Indica la fecha de vencimiento', addLine: 'Añade al menos una línea', issued: 'Factura emitida',
    },
    financeiro: {
      viewList: 'Lista', byWeek: 'Por semana', byMonth: 'Por mes', summaryWeek: 'Resumen de la semana', summaryMonth: 'Resumen del mes',
      periodPrev: 'Anterior', periodNext: 'Siguiente', periodCurrent: 'Actual',
      vsPrev: p => `frente al anterior · ${p.delta}`,
      thPeriod: 'Periodo', thWhen: 'Fecha', thWho: 'Cliente / Proveedor', thRef: 'Referencia', thTotal: 'Importe',
      filterAll: 'Todos', received: 'Recibido', spent: 'Gastado', net: 'Neto', ledger: 'Movimientos',
      summaryEmpty: 'Nada en este resumen', summaryEmptyDesc: 'Los movimientos aparecen aquí cuando una factura o un pago se marca como pagado.',
      emptyTitle: 'Aún sin movimientos', emptyDesc: 'Los movimientos aparecen aquí cuando una factura o un pago se marca como pagado.',
      filterClientAll: 'Todos los clientes', filterClientAria: 'Filtrar por cliente',
      emptyClient: 'Sin movimientos con este cliente', emptyClientDesc: 'Aquí aparecen las facturas que pagó este cliente y los pagos vinculados a él.',
    },
    lines: {
      client: 'Cliente', chooseClient: '— Elegir cliente —',
      services: 'Servicios', materials: 'Materiales', label: 'Líneas',
      colDescription: 'Descripción', colQty: 'Cant.', colUnit: 'Unid.', colPrice: 'Precio €',
      addEmpty: '+ Línea vacía', catalogPick: 'Catálogo · Servicios / Materiales', add: 'Añadir', total: 'Total',
      descPlaceholder: 'Descripción de la línea…', unitPlaceholder: 'ud', removeLine: 'Quitar línea', chooseCatalogItem: 'Elige un ítem del catálogo',
    },
    items: {
      bookableLabel: 'Los clientes pueden reservar este servicio', bookableHint: 'Aparece en Reservas, en el bot de WhatsApp y en el asistente.',
      durationLabel: 'Duración (min)', bookablePill: p => `Reservable · ${p.min} min`,
      services: 'Servicios', materials: 'Materiales', catalogTitle: 'Catálogo', tag: p => `${p.n} ítems`,
      thType: 'Tipo', thCategory: 'Categoría', thDescription: 'Descripción', thUnit: 'Unid.', thPrice: 'Precio', thActions: 'Acciones',
      emptyTitle: 'Catálogo vacío', emptyDesc: 'Añade servicios o materiales para reutilizar en presupuestos.',
      pillService: 'SERVICIO', pillMaterial: 'MATERIAL', editTitle: 'Editar', deleteTitle: 'Eliminar',
      idLabel: 'ID · slug', typeLabel: 'Tipo', service: 'Servicio', material: 'Material',
      categoryLabel: 'Categoría', descLabel: 'Descripción', unitLabel: 'Unidad', priceLabel: 'Precio (EUR)',
      phId: 'ej: srv-pintura-interior', phCategory: 'Ej: Pintura, Estructurales, Mano de obra…', phDesc: 'Descripción visible en presupuestos', phUnit: 'm², h, ud, rl…',
      editingHint: p => `Editando ${p.id} — los cambios se aplican a nuevos presupuestos.`,
      eyebrow: 'Ítems estándar', newTitle: 'Nuevo ítem de catálogo', editTitleFull: p => `Editar · ${p.id}`,
      saveChanges: 'Guardar cambios', createItem: 'Crear ítem',
      fillRequired: 'Rellena todos los campos obligatorios', updated: p => `Ítem actualizado · ${p.id}`, created: p => `Ítem creado · ${p.id}`,
      confirmTitle: '¿Eliminar ítem del catálogo?', confirmBody: p => `"${p.desc}" se eliminará. Los presupuestos ya emitidos no se verán afectados.`,
      confirmOk: 'Eliminar ítem', deleted: p => `Ítem eliminado · ${p.id}`,
    },
  },

  backoffice: {
    login: { eyebrow: 'thebots.lab / platform', title: 'Backoffice', desc: 'Acceso de operador para gestionar bots, tenants y equipos.', password: 'Contraseña', submit: 'Entrar', invalid: 'Acceso inválido', google: 'Continuar con Google', or: 'o usa la contraseña de administrador', notAllowed: 'Esta cuenta de Google no tiene acceso al backoffice', googleFailed: 'No se pudo iniciar sesión con Google', cancelled: 'Inicio de sesión cancelado', unavailable: 'No hay ningún método de acceso configurado.' },
    cancel: 'Cancelar', save: 'Guardar', confirm: 'Confirmar', delete: 'Eliminar', loadError: 'Error al cargar',
    error: p => `Error: ${p.msg}`,
    kpiActive: 'Activos', kpiMessages: 'Mensajes', searchPlaceholder: 'Buscar tenant…', themeAria: 'Cambiar tema',
    logout: 'Salir', crumbRoot: 'Plataforma', drawerEyebrow: 'Tenant', brandSub: 'Plataforma · Tenants', closeAria: 'Cerrar',
    heroTitle: 'Tenants', heroDesc: 'Bots/clientes configurados en esta plataforma.',
    botsTitle: 'Bots',
    thName: 'Nombre', thSlug: 'Slug', thChannels: 'Canales', thStatus: 'Estado', thMsgs: 'Msjs', thLastActivity: 'Última actividad', thActions: 'Acciones',
    thDeletedAt: 'Eliminado el',
    filters: { all: 'Todos', ACTIVE: 'Activos', SUSPENDED: 'Suspendidos', DELETED: 'Eliminados' },
    status: { ACTIVE: 'Activo', SUSPENDED: 'Suspendido', DELETED: 'Eliminado' },
    statusFilterAria: 'Filtrar tenants por estado',
    emptyTenants: 'No se encontraron tenants',
    emptyActive: 'Ningún tenant activo', emptySuspended: 'Ningún tenant suspendido',
    emptyDeleted: 'Ningún tenant eliminado', emptyDeletedDesc: 'Los tenants que elimines aparecen aquí, listos para restaurar.',
    emptySearch: p => `Ningún tenant aquí coincide con "${p.q}"`,
    showMatches: p => `Ver ${p.n} en ${p.label}`,
    openDashboard: 'Abrir panel', users: 'Usuarios', edit: 'Editar', suspend: 'Suspender', activate: 'Activar', reload: 'Recargar',
    restore: 'Restaurar',
    pipelineReloaded: 'Pipeline recargada',
    noToken: 'sin token', token: 'token',
    usersTitle: p => `Usuarios del panel · ${p.slug}`,
    thEmail: 'Email', thRole: 'Rol',
    noUsers: 'Sin usuarios', disable: 'Desactivar',
    emailLabel: 'Email', tempPassword: 'Contraseña temporal', roleLabel: 'Rol',
    createUser: 'Crear usuario', emailPasswordRequired: 'Email y contraseña obligatorios', userCreated: 'Usuario creado',
    userDisabled: 'Usuario desactivado', userActivated: 'Usuario activado',
    tenantNameLabel: 'Nombre', tenantSlugLabel: 'Slug', languageLabel: 'Idioma',
    modelOverride: 'Modelo (override)', modelPlaceholder: 'vacío = por defecto',
    ratePerHour: 'Límite / hora', ratePerDay: 'Límite / día',
    modulesLabel: 'Módulos', modulesHint: 'Solo la vista general permanece activa. Todos los demás módulos — mensajería incluida — son opcionales.',
    selectAllModules: 'Todos', selectNoModules: 'Ninguno',
    channelsLabel: 'Canales', connectWhatsApp: 'Conectar WhatsApp', connectInstagram: 'Conectar Instagram', addChannel: '+ Añadir canal',
    colPlatform: 'Plataforma', colExternalId: 'ID externo', colAccessToken: 'Token de acceso',
    channelsHint: 'Los canales son opcionales — puedes crear el tenant sin ninguno y conectarlo más tarde. El token de Instagram es obligatorio al añadir un canal. Al editar, deja el token vacío para conservar el existente.',
    noChannels: 'Sin canales. Este tenant funciona sin ninguno.',
    chExternalPlaceholder: 'phone_number_id o ID de cuenta IG', chTokenUnchanged: 'sin cambios', chTokenPlaceholder: 'token de acceso', removeChannel: 'Quitar canal',
    editTenant: p => `Editar · ${p.slug}`, newTenant: 'Nuevo bot/cliente', saveChanges: 'Guardar cambios', createTenant: 'Crear tenant',
    nameRequired: 'Nombre obligatorio', igNeedsToken: 'Instagram necesita un Page access token',
    tenantUpdated: 'Tenant actualizado', botCreated: 'Bot creado. Conecta los canales a la app de Meta y apunta el webhook.',
    suspendTitle: '¿Suspender tenant?', activateTitle: '¿Activar tenant?', tenantLine: p => `Tenant ${p.slug}`,
    deleteTitle: '¿Eliminar tenant?',
    deleteBody: p => `${p.name} (${p.slug}) deja de responder en sus canales y sus usuarios ya no pueden entrar. Sus datos se conservan y puedes restaurarlo desde Eliminados.`,
    deleted: p => `${p.name} eliminado. Está en Eliminados si necesitas recuperarlo.`,
    restoreTitle: '¿Restaurar tenant?',
    restoreBody: p => `${p.name} (${p.slug}) vuelve a estar activo: el bot responde en sus canales y sus usuarios pueden entrar.`,
    restoreCompaniesNote: p => (p.n === 1 ? 'La empresa eliminada con él también vuelve.' : `Las ${p.n} empresas eliminadas con él también vuelven.`),
    restored: p => `${p.name} restaurado`,
    restoreParentFirst: p => `Restaura primero ${p.name}`,
    comesBackWith: p => `Vuelve con ${p.name}`,
    deletedWith: p => (p.n === 1 ? '1 empresa vuelve con él' : `${p.n} empresas vuelven con él`),
    restoreCompanyLimit: p => `${p.name} ya usa sus ${p.limit} empresas permitidas. Aumenta su límite de empresas y luego restaura.`,
    notDeleted: p => `${p.name} ya no está eliminado.`,
    tenantDeleted: 'Este tenant se eliminó mientras tanto.',
    slugTaken: p => `El slug ${p.slug} ya está en uso. Elige otro.`,
    slugTakenDeleted: p => `El slug ${p.slug} pertenece a un tenant eliminado. Restáuralo desde Eliminados o elige otro slug.`,
    maxCompaniesLabel: 'Empresas permitidas',
    maxCompaniesHint: 'Cuántas empresas puede tener este tenant, incluida esta. Sus administradores las añaden en el panel, en Ajustes → Empresas.',
    companyOf: p => `Empresa de ${p.name}`, companiesTag: p => `${p.used}/${p.limit} empresas`,
    usersAllCompanies: 'Estos usuarios entran en todas las empresas de este tenant.',
    cascadeNote: p => (p.n === 1 ? 'La otra empresa también cambia.' : `Las otras ${p.n} empresas también cambian.`),
    igSessionExpired: 'Sesión expirada', igNotConfigured: 'Instagram OAuth no configurado (IG_APP_ID)',
    igAllowPopups: 'Permite las ventanas emergentes para conectar Instagram', igConnected: 'Instagram conectado ✓', igFailed: p => `Instagram falló: ${p.reason || 'error'}`,
    waNotConfigured: 'WhatsApp Embedded Signup no configurado', waOpenPopup: 'Abre la ventana de Meta para conectar WhatsApp', waConnected: 'WhatsApp conectado',
    waCancelled: 'Conexión de WhatsApp cancelada', waMissingCode: 'Meta no devolvió el código de autorización',
    waTimeout: 'Tiempo agotado esperando el Embedded Signup', waSdkFailed: 'No se pudo cargar el SDK de Facebook', waFailed: p => `WhatsApp falló: ${p.msg}`,
    admins: {
      nav: 'Administradores',
      title: 'Administradores',
      desc: 'Quién puede entrar en el backoffice con Google. Pueden gestionar todos los tenants y los ajustes de la plataforma.',
      listTitle: 'Pueden entrar',
      thEmail: 'Email', thSource: 'Acceso', thAdded: 'Añadido',
      you: 'tú',
      sourceEnv: '.env del servidor', sourceBackoffice: 'Backoffice',
      envLocked: 'Cámbialo en el .env del servidor',
      addedBy: p => (p.by ? `${p.date} por ${p.by}` : p.date),
      remove: 'Quitar',
      addTitle: 'Añadir administrador',
      emailLabel: 'Email de la cuenta de Google',
      emailPlaceholder: 'nombre@ejemplo.com',
      addHint: 'Entra con la cuenta de Google que usa exactamente este email.',
      add: 'Dar acceso',
      googleNotReady: 'El inicio de sesión con Google no está configurado en este servidor (FIREBASE_* en .env), así que nadie puede entrar con Google todavía.',
      addConfirmTitle: '¿Dar acceso al backoffice?',
      addConfirmBody: p => `${p.email} podrá entrar con Google y gestionar todos los tenants, sus usuarios y los ajustes de la plataforma.`,
      added: p => `${p.email} ya puede entrar`,
      removeConfirmTitle: '¿Quitar el acceso al backoffice?',
      removeConfirmBody: p => `${p.email} ya no podrá entrar, y una sesión que tenga abierta termina en su próxima acción.`,
      removed: p => `${p.email} ya no tiene acceso`,
      invalidEmail: 'Escribe un email válido',
      alreadyAllowed: 'Ese email ya puede entrar',
      fromEnv: 'Este email está en el .env del servidor, así que solo se puede quitar allí',
      cannotRemoveSelf: 'No puedes quitar tu propio acceso',
      notFound: 'Ese email ya no tiene acceso',
    },
    backups: {
      nav: 'Copias de seguridad',
      title: 'Copias de seguridad',
      desc: 'El servidor hace una copia de la base de datos cada noche y la guarda fuera del servidor. Hacer copia ahora crea una copia extra, por ejemplo antes de un cambio arriesgado.',
      backupNow: 'Hacer copia ahora',
      inProgress: 'Copia en curso',
      requestedToast: 'Copia solicitada. El servidor la empieza en menos de un minuto.',
      doneToast: 'Copia terminada',
      failedToast: 'La copia falló',
      busy: 'Ya hay una copia en espera o en curso',
      lastTitle: 'Última copia pedida desde aquí',
      state: { requested: 'En espera', running: 'En curso', succeeded: 'Hecha', failed: 'Falló', stalled: 'No terminó' },
      requestedLine: p => `Pedida el ${p.at}${p.by ? ` por ${p.by}` : ''}. El servidor la empieza en menos de un minuto.`,
      runningLine: p => `Empezó el ${p.at}${p.by ? ` · pedida por ${p.by}` : ''}`,
      succeededLine: p => `Terminó el ${p.at} · ${p.archive}`,
      failedLine: p => `Falló el ${p.at}. El final de su salida:`,
      stalledLine: p => `Empezó el ${p.at} pero nunca respondió. Puedes empezar otra.`,
      runnerOffline: p => `El ejecutor de copias del servidor dio señal por última vez el ${p.at}, así que una copia nueva no empezará hasta que vuelva a funcionar.`,
      runnerMissing: 'El ejecutor de copias aún no está instalado en el servidor, así que Hacer copia ahora no puede empezar una copia.',
      listTitle: 'Copias en el servidor',
      thDate: 'Hecha', thFile: 'Archivo', thSize: 'Tamaño', thOffsite: 'Fuera del servidor',
      copied: 'Copiada', notCopied: 'Sin registro',
      emptyTitle: 'Aún no hay copias',
      emptyDesc: 'La copia nocturna o Hacer copia ahora pondrán aquí la primera.',
      unavailableTitle: 'Las copias no están configuradas aquí',
      unavailableDesc: 'El servidor no ha montado sus carpetas de copias en la app, así que no se pueden ver ni iniciar desde aquí.',
    },
    platformSettings: {
      nav: 'Ajustes de plataforma',
      title: 'Ajustes de plataforma',
      desc: 'Overrides en tiempo de ejecución guardados en MongoDB. Los secretos van enmascarados; revelación bajo demanda. URI de Mongo y puerto siguen solo en .env.',
      save: 'Guardar overrides',
      reload: 'Recargar desde Mongo',
      saved: 'Ajustes guardados',
      reloaded: 'Ajustes recargados',
      reveal: 'Revelar',
      hide: 'Ocultar',
      clear: 'Quitar override',
      secretBadge: 'secreto',
      sourceEnv: 'desde .env',
      sourceOverride: 'override Mongo',
      updatedAt: p => `Actualizado ${p.at}`,
      neverUpdated: 'Aún no hay overrides guardados',
      passwordHint: 'Introduce una contraseña en texto (se hashea al guardar) o pega un hash bcrypt.',
      empty: 'No hay ajustes disponibles',
      categories: {
        whatsapp: 'WhatsApp',
        instagram: 'Instagram',
        openrouter: 'OpenRouter',
        ratelimit: 'Límites de uso',
        pdf: 'Almacenamiento PDF',
        admin: 'Auth admin',
      },
    },
  },
};
