/* Spanish (es) UI catalog. Registered into window.__I18N_CATALOGS['es']. */
window.__I18N_CATALOGS = window.__I18N_CATALOGS || {};
window.__I18N_CATALOGS['es'] = {
  common: {
    nav: {
      overview: 'Resumen', conversations: 'Conversaciones', contacts: 'Contactos',
      clients: 'Clientes', quotes: 'Presupuestos', invoices: 'Facturas', catalog: 'Catálogo',
      persona: 'Persona', settings: 'Ajustes',
    },
    lang: {
      title: 'Idioma', desc: 'Idioma usado en este panel.', label: 'Idioma',
      saved: 'Idioma actualizado ✓', saveFailed: 'No se pudo actualizar el idioma',
    },
  },

  app: {
    settingsDesc: 'Canales conectados y configuración del bot.',
    channelsTitle: 'Canales',
    channelsDesc: 'Cuentas donde el asistente responde a tus clientes.',
    colChannel: 'Canal', colAccount: 'Cuenta', colStatus: 'Estado', colActions: 'Acciones',
    connected: 'Conectado', notConnected: 'No conectado',
    igConnect: 'Conectar Instagram', igReconnect: 'Reconectar Instagram',
    igHint: 'Conectar Instagram abre una ventana de Meta para autorizar tu cuenta profesional. La cuenta debe ser Business o Creator.',
    moreSettingsTitle: 'Más ajustes próximamente',
    moreSettingsDesc: 'Los miembros del equipo se gestionan en el backoffice por ahora. Perfil de empresa / marca en PDF aún pendiente.',
    sessionExpired: 'Sesión expirada',
    igUnavailable: 'La conexión con Instagram no está disponible',
    igAllowPopups: 'Permite las ventanas emergentes para conectar Instagram',
    igConnected: 'Instagram conectado ✓',
    igFailed: reason => `No se pudo conectar Instagram${reason ? ` (${reason})` : ''}`,
    webTitle: 'Widget del sitio web',
    webDesc: 'Añade el asistente de chat a tu sitio web. Pega este fragmento justo antes de la etiqueta </body>.',
    webGenerate: 'Generar código del widget',
    webRegenerate: 'Widget activo',
    webCopy: 'Copiar fragmento',
    webCopied: 'Fragmento copiado ✓',
    webGenerated: 'Código del widget generado ✓',
    webGenerateFailed: 'No se pudo generar el código del widget',
    webOriginsLabel: 'Dominios de sitio permitidos (opcional)',
    webOriginsHint: 'Un origen por línea, p. ej. https://www.tusitio.com. Déjalo vacío para permitir cualquier sitio (menos seguro).',
    webOriginsSave: 'Guardar dominios',
    webOriginsSaved: 'Dominios guardados ✓',
    webRowName: 'Sitio web',
    quickCreateSoon: 'La creación rápida de este módulo llegará pronto.',
    clientFormTitle: 'Nuevo cliente',
    clientFormName: 'Nombre', clientFormPhone: 'Teléfono', clientFormAddress: 'Dirección',
    clientPhName: 'Nombre del cliente', clientPhPhone: '+351…', clientPhAddress: 'Calle, ciudad',
    clientSave: 'Crear cliente',
    clientValidate: 'Introduce nombre y teléfono',
    clientCreated: p => `Cliente creado · ${p.name}`,
    clientCreateFailed: 'No se pudo crear el cliente',
    optional: 'opcional',
    catalogFormTitle: 'Nuevo ítem', catalogSave: 'Crear ítem',
    catalogId: 'ID', catalogType: 'Tipo', catalogService: 'Servicio', catalogMaterial: 'Material',
    catalogCategory: 'Categoría', catalogDesc: 'Descripción', catalogUnit: 'Unidad', catalogPrice: 'Precio (€)',
    catalogPhId: 'srv-…', catalogPhCategory: 'Ej.: Fachadas', catalogPhDesc: 'Qué cubre este ítem', catalogPhUnit: 'm2, unidad, servicio…',
    catalogValidate: 'Rellena todos los campos obligatorios', catalogCreated: p => `Ítem creado · ${p.id}`, catalogCreateFailed: 'No se pudo crear el ítem',
    quoteFormTitle: 'Nuevo presupuesto', quoteSave: 'Crear presupuesto',
    quoteValidUntil: 'Válido hasta', quoteNotes: 'Notas', quoteNotesPh: 'Notas opcionales mostradas en el PDF',
    quoteChooseClient: 'Elige un cliente', quoteAddLine: 'Añade al menos una línea', quoteCreated: 'Presupuesto creado', quoteCreateFailed: 'No se pudo crear el presupuesto',
    invoiceFormTitle: 'Nueva factura', invoiceSave: 'Emitir factura',
    invoiceDueDate: 'Vencimiento', invoiceQuoteId: 'ID del presupuesto', invoiceQuoteIdPh: 'Asociar un presupuesto existente (opcional)',
    invoiceChooseClient: 'Elige un cliente', invoiceEnterDueDate: 'Indica la fecha de vencimiento', invoiceAddLine: 'Añade al menos una línea', invoiceCreated: 'Factura emitida', invoiceCreateFailed: 'No se pudo emitir la factura',
    lineClient: 'Cliente', lineChooseClient: 'Seleccionar…', lineItemsLabel: 'Líneas',
    lineColDesc: 'Descripción', lineColQty: 'Cant.', lineColUnit: 'Unidad', lineColPrice: 'Precio',
    lineAddEmpty: 'Añadir línea', lineCatalogPick: 'Del catálogo…', lineAdd: 'Añadir', lineTotal: 'Total',
    lineDescPh: 'Descripción', lineUnitPh: 'un', lineRemove: 'Eliminar línea', lineChooseCatalog: 'Elige un ítem del catálogo',
    loginEyebrow: 'thebots.lab / tenant',
    loginTitle: 'Inicia sesión en el panel',
    loginDesc: 'Accede a los datos del chatbot, conversaciones y CRM.',
    loginEmail: 'Email', loginPassword: 'Contraseña', loginSubmit: 'Entrar', loginInvalid: 'Acceso inválido',
    newPrefix: 'Nuevo',
    dashboardWord: 'Panel', searchPlaceholder: 'Buscar…', logout: 'Salir', themeAria: 'Cambiar tema',
    noData: 'Sin datos',
    overviewDesc: 'Estado del chatbot y actividad reciente.',
    statMessages24h: 'Mensajes 24h', statMessages: 'Mensajes', statContacts: 'Contactos', statConversations: 'Conversaciones', statQuotes: 'Presupuestos', statInvoices: 'Facturas',
    contactsDesc: 'Usuarios finales que hablaron con el bot.',
    thName: 'Nombre', thStatus: 'Estado', thLastSeen: 'Visto', thActions: 'Acciones',
    block: 'Bloquear', unblock: 'Desbloquear',
    conversationsDesc: 'Historial de conversaciones (solo lectura).',
    thState: 'Estado', thMsgs: 'Msjs', thLast: 'Última',
    threadTitle: 'Conversación', noMessages: 'Sin mensajes',
    clientsDesc: 'CRM · Clientes.', thPhone: 'Teléfono', thAddress: 'Dirección', thNo: 'Nº',
    quotesDesc: 'CRM · Propuestas comerciales.', thNumber: 'Número', thClient: 'Cliente', thTotal: 'Total',
    invoicesDesc: 'CRM · Facturas emitidas.', thDueDate: 'Vencimiento',
    catalogDesc: 'CRM · Servicios y materiales estándar.', thType: 'Tipo', thCategory: 'Categoría', thDescription: 'Descripción', thUnit: 'Unid.', thPrice: 'Precio',
    personaDesc: 'Personalidad del bot — sintetizada a partir de las notas y archivos que subes.',
    personaCompiling: 'Sintetizando…', statVersion: 'Versión', statTokens: 'Tokens est.', statUpdated: 'Actualizado',
    testBotTitle: 'Probar el bot', clear: 'Limpiar',
    testBotDesc: 'Chatea con el bot usando la persona actual para probar el tono y las respuestas. Los mensajes de prueba no se guardan y no crean clientes, presupuestos ni facturas.',
    chatPlaceholder: 'Escribe un mensaje de prueba…', send: 'Enviar',
    chatEmpty: 'Envía un mensaje para probar la persona del bot.', typing: 'escribiendo…', chatError: '⚠️ Error al contactar con el bot. Inténtalo de nuevo.',
    addInfoTitle: 'Añadir información',
    addInfoDesc: 'Escribe una nota o sube un archivo (PDF, TXT, MD). Se sintetiza en el archivo de instrucciones de abajo.',
    noteLabel: 'Nota', notePlaceholder: 'P. ej.: Somos una clínica dental en Lisboa. Tono cálido, trato formal...', addNote: 'Añadir nota',
    fileLabel: 'Archivo', fileHint: 'PDF, TXT o Markdown. El texto se extrae y se sintetiza.',
    sourcesTitle: 'Fuentes', sourcesDesc: 'Material en bruto que alimenta la síntesis.', rebuildAll: 'Recompilar todo',
    sourceSynced: 'sincronizado', sourcePending: 'pendiente', remove: 'Quitar',
    thSource: 'Fuente', thCreated: 'Creado',
    noSourcesTitle: 'Aún sin fuentes', noSourcesDesc: 'Añade una nota o archivo arriba.',
    compiledTitle: 'Archivo de instrucciones compilado',
    compiledDesc: 'Resultado de la síntesis. Puedes editarlo manualmente; la próxima síntesis lo revisará.',
    compiledPlaceholder: 'Todavía vacío — añade información arriba para dar personalidad al bot.',
    saveManual: 'Guardar edición manual',
    personaSaved: 'Persona guardada', noteAdded: 'Nota añadida — sintetizando', fileUploaded: 'Archivo subido — sintetizando', rebuildStarted: 'Recompilación iniciada', uploadFailed: 'Error al subir',
  },

  admin: {
    nav: { clientes: 'Clientes', orcamentos: 'Presupuestos', faturas: 'Facturas', items: 'Ítems estándar' },
    crumbRoot: 'Panel',
    brandSub: 'Tenant · Gestión',
    searchPlaceholder: 'Buscar en esta vista…',
    export: 'Exportar', exportTitle: 'Exportar CSV', exportSoon: 'Exportar · próximamente',
    backoffice: '← Backoffice', themeAria: 'Cambiar tema', closeAria: 'Cerrar',
    kpiReceivable: 'Por cobrar', kpiPaid: 'Cobrado este mes',
    saving: 'Guardando…', cancel: 'Cancelar', save: 'Guardar', confirm: 'Confirmar', delete: 'Eliminar',
    loading: 'Cargando…', loadError: 'Error al cargar',
    login: { eyebrow: p => `thebots.lab / ${p.tenant}`, title: 'Entrar al CRM', desc: 'Usa la contraseña de operador para abrir este panel de gestión.', password: 'Contraseña', submit: 'Entrar', invalid: 'Acceso inválido', crumb: 'Acceso' },
    invalidTenantTitle: 'Tenant inválido', invalidTenantDesc: 'Vuelve al backoffice y abre un CRM válido.',
    titleSuffix: 'Panel de Gestión',
    pdfPending: 'pendiente',
    errorPdf: p => `Error PDF: ${p.msg}`,
    error: p => `Error: ${p.msg}`,
    quoteStatus: { PENDENTE: 'Pendiente', ACEITO: 'Aceptado' },
    invoiceStatus: { PENDING: 'PENDIENTE', PAID: 'PAGADA', OVERDUE: 'VENCIDA', CANCELLED: 'CANCELADA' },
    tabs: {
      clientes: { title: 'Clientes', desc: 'Directorio de clientes de la empresa.', newLabel: 'Nuevo cliente' },
      orcamentos: { title: 'Presupuestos', desc: 'Propuestas comerciales emitidas.', newLabel: 'Nuevo presupuesto' },
      faturas: { title: 'Facturas', desc: 'Facturas emitidas y su estado.', newLabel: 'Nueva factura' },
      items: { title: 'Ítems estándar', desc: 'Catálogo de servicios y materiales para presupuestos y facturas.', newLabel: 'Nuevo ítem' },
    },
    clients: {
      total: 'Total', new30: 'Nuevos · 30d', directory: 'Directorio',
      one: 'cliente', many: 'clientes',
      thName: 'Nombre', thAddress: 'Dirección', thPhone: 'Teléfono', thCreated: 'Creado', thNo: 'Nº Cliente',
      emptyTitle: 'No se encontraron clientes', emptyDesc: 'Ajusta la búsqueda o crea un nuevo cliente.',
      formName: 'Nombre', formAddress: 'Dirección', formPhone: 'Teléfono',
      phName: 'Ej: Manuel Costa, S.L.', phAddress: 'Ej: Calle de las Flores 12, 1200-001 Lisboa', phPhone: '+351 912 345 678',
      eyebrow: 'Clientes', formTitle: 'Nuevo cliente', saveLabel: 'Crear cliente',
      validate: 'Introduce nombre y teléfono', created: p => `Cliente creado · ${p.name}`,
    },
    quotes: {
      total: 'Total', sent: 'Enviados', accepted: 'Aceptados', proposals: 'Propuestas', filterAll: 'Todos',
      thNumber: 'Número', thClient: 'Cliente', thStatus: 'Estado', thValidUntil: 'Válido hasta', thTotal: 'Total', thPdf: 'PDF',
      emptyTitle: 'Sin presupuestos', emptyDesc: 'Crea el primer presupuesto con el botón de arriba.',
      validUntil: 'Válido hasta', optional: 'opcional', notes: 'Notas', notesPlaceholder: 'Notas internas, condiciones, plazos…',
      eyebrow: 'Presupuestos', formTitle: 'Nuevo presupuesto', saveLabel: 'Crear presupuesto',
      chooseClient: 'Elige un cliente', addLine: 'Añade al menos una línea', created: 'Presupuesto creado',
    },
    invoices: {
      paid: 'Pagado', pending: 'Pendiente', overdue: 'Vencido', documents: 'Documentos', filterAll: 'Todos',
      thNumber: 'Número', thClient: 'Cliente', thStatus: 'Estado', thDueDate: 'Vencimiento', thTotal: 'Total', thPdfActions: 'PDF · Acciones',
      emptyTitle: 'Sin facturas', emptyDesc: 'Emite la primera factura con el botón de arriba.',
      markPaid: 'Marcar pagada', markedPaid: p => `Factura ${p.number} marcada como pagada`,
      dueDate: 'Vencimiento', quoteId: 'ID Presupuesto', quoteIdPlaceholder: 'ID del presupuesto asociado',
      eyebrow: 'Facturas', formTitle: 'Nueva factura', saveLabel: 'Emitir factura',
      chooseClient: 'Elige un cliente', enterDueDate: 'Indica la fecha de vencimiento', addLine: 'Añade al menos una línea', issued: 'Factura emitida',
    },
    lines: {
      client: 'Cliente', chooseClient: '— Elegir cliente —',
      services: 'Servicios', materials: 'Materiales', label: 'Líneas',
      colDescription: 'Descripción', colQty: 'Cant.', colUnit: 'Unid.', colPrice: 'Precio €',
      addEmpty: '+ Línea vacía', catalogPick: 'Catálogo · Servicios / Materiales', add: 'Añadir', total: 'Total',
      descPlaceholder: 'Descripción de la línea…', unitPlaceholder: 'ud', removeLine: 'Quitar línea', chooseCatalogItem: 'Elige un ítem del catálogo',
    },
    items: {
      services: 'Servicios', materials: 'Materiales', catalogTitle: 'Catálogo', tag: p => `${p.n} ítems`,
      thType: 'Tipo', thCategory: 'Categoría', thDescription: 'Descripción', thUnit: 'Unid.', thPrice: 'Precio', thActions: 'Acciones',
      emptyTitle: 'Catálogo vacío', emptyDesc: 'Añade servicios o materiales para reutilizar en presupuestos.',
      pillService: 'SERVICIO', pillMaterial: 'MATERIAL', editTitle: 'Editar', deleteTitle: 'Eliminar',
      idLabel: 'ID · slug', typeLabel: 'Tipo', service: 'Servicio', material: 'Material',
      categoryLabel: 'Categoría', descLabel: 'Descripción', unitLabel: 'Unidad', priceLabel: 'Precio (EUR)',
      phId: 'ej: srv-pintura-interior', phCategory: 'Ej: Pintura, Estructurales, Mano de obra…', phDesc: 'Descripción visible en presupuestos', phUnit: 'm², h, ud, rl…',
      editingHint: p => `Editando ${p.id} — los cambios se aplican a nuevos presupuestos.`,
      eyebrow: 'Ítems estándar', newTitle: 'Nuevo ítem de catálogo', editTitleFull: p => `Editar · ${p.id}`,
      saveChanges: 'Guardar cambios', createItem: 'Crear ítem',
      fillRequired: 'Rellena todos los campos obligatorios', updated: p => `Ítem actualizado · ${p.id}`, created: p => `Ítem creado · ${p.id}`,
      confirmTitle: '¿Eliminar ítem del catálogo?', confirmBody: p => `"${p.desc}" se eliminará. Los presupuestos ya emitidos no se verán afectados.`,
      confirmOk: 'Eliminar ítem', deleted: p => `Ítem eliminado · ${p.id}`,
    },
  },

  backoffice: {
    login: { eyebrow: 'thebots.lab / platform', title: 'Backoffice', desc: 'Acceso de operador para gestionar bots, tenants y equipos.', password: 'Contraseña', submit: 'Entrar', invalid: 'Acceso inválido' },
    cancel: 'Cancelar', save: 'Guardar', confirm: 'Confirmar', delete: 'Eliminar', loadError: 'Error al cargar',
    error: p => `Error: ${p.msg}`,
    kpiActive: 'Activos', kpiMessages: 'Mensajes', searchPlaceholder: 'Buscar tenant…', themeAria: 'Cambiar tema',
    logout: 'Salir', crumbRoot: 'Plataforma', drawerEyebrow: 'Tenant', brandSub: 'Plataforma · Tenants', closeAria: 'Cerrar',
    heroTitle: 'Tenants', heroDesc: 'Bots/clientes configurados en esta plataforma.',
    botsTitle: 'Bots',
    thName: 'Nombre', thSlug: 'Slug', thChannels: 'Canales', thAgent: 'Agente', thStatus: 'Estado', thMsgs: 'Msjs', thLastActivity: 'Última actividad', thActions: 'Acciones',
    emptyTenants: 'No se encontraron tenants',
    openDashboard: 'Abrir panel', users: 'Usuarios', edit: 'Editar', suspend: 'Suspender', activate: 'Activar', reload: 'Recargar',
    pipelineReloaded: 'Pipeline recargada',
    noToken: 'sin token', token: 'token',
    usersTitle: p => `Usuarios del panel · ${p.slug}`,
    thEmail: 'Email', thRole: 'Rol',
    noUsers: 'Sin usuarios', disable: 'Desactivar',
    emailLabel: 'Email', tempPassword: 'Contraseña temporal', roleLabel: 'Rol',
    createUser: 'Crear usuario', emailPasswordRequired: 'Email y contraseña obligatorios', userCreated: 'Usuario creado',
    userDisabled: 'Usuario desactivado', userActivated: 'Usuario activado',
    tenantNameLabel: 'Nombre', tenantSlugLabel: 'Slug', agentTypeLabel: 'Tipo de agente', languageLabel: 'Idioma',
    modelOverride: 'Modelo (override)', modelPlaceholder: 'vacío = por defecto',
    ratePerHour: 'Límite / hora', ratePerDay: 'Límite / día',
    modulesLabel: 'Módulos', modulesHint: 'Los módulos siempre activos quedan marcados. Los módulos CRM requieren el tipo de agente CRM_V1.',
    channelsLabel: 'Canales', connectWhatsApp: 'Conectar WhatsApp', connectInstagram: 'Conectar Instagram', addChannel: '+ Añadir canal',
    colPlatform: 'Plataforma', colExternalId: 'ID externo', colAccessToken: 'Token de acceso',
    channelsHint: 'El token de Instagram es obligatorio al añadir un canal. Al editar, deja el token vacío para conservar el existente.',
    chExternalPlaceholder: 'phone_number_id o ID de cuenta IG', chTokenUnchanged: 'sin cambios', chTokenPlaceholder: 'token de acceso', removeChannel: 'Quitar canal',
    editTenant: p => `Editar · ${p.slug}`, newTenant: 'Nuevo bot/cliente', saveChanges: 'Guardar cambios', createTenant: 'Crear tenant',
    nameRequired: 'Nombre obligatorio', addOneChannel: 'Añade al menos un canal', igNeedsToken: 'Instagram necesita un Page access token',
    tenantUpdated: 'Tenant actualizado', botCreated: 'Bot creado. Conecta los canales a la app de Meta y apunta el webhook.',
    suspendTitle: '¿Suspender tenant?', activateTitle: '¿Activar tenant?', tenantLine: p => `Tenant ${p.slug}`,
    deleteTitle: '¿Eliminar tenant?', deleteBody: p => `${p.slug} quedará marcado como DELETED. Los datos existentes no se borrarán.`,
    igSessionExpired: 'Sesión expirada', igNotConfigured: 'Instagram OAuth no configurado (IG_APP_ID)',
    igAllowPopups: 'Permite las ventanas emergentes para conectar Instagram', igConnected: 'Instagram conectado ✓', igFailed: p => `Instagram falló: ${p.reason || 'error'}`,
    waNotConfigured: 'WhatsApp Embedded Signup no configurado', waOpenPopup: 'Abre la ventana de Meta para conectar WhatsApp', waConnected: 'WhatsApp conectado',
    waCancelled: 'Conexión de WhatsApp cancelada', waMissingCode: 'Meta no devolvió el código de autorización',
    waTimeout: 'Tiempo agotado esperando el Embedded Signup', waSdkFailed: 'No se pudo cargar el SDK de Facebook', waFailed: p => `WhatsApp falló: ${p.msg}`,
  },
};
