package com.rfm.edubot.agents.templates

import com.rfm.edubot.tenant.model.TenantLocales

/**
 * Default names and messages of the built-in templates, per language. They are content the company
 * edits after creating the agent; the gallery's labels live in the dashboard catalogs.
 */
internal object TemplateCopy {
    private val en = mapOf(
        "invoice_due_reminder.name" to "Invoice due reminder",
        "invoice_due_reminder.message" to "Hi {{client.firstName}}, a friendly reminder that invoice {{invoice.number}} ({{invoice.amountDue}}) is due on {{invoice.dueDate}}. Thank you! {{company.name}}",
        "overdue_sequence.name" to "Overdue invoice follow-up",
        "overdue_sequence.first" to "Hi {{client.firstName}}, invoice {{invoice.number}} ({{invoice.amountDue}}) was due on {{invoice.dueDate}}. If you've already paid, please ignore this message. Thank you! {{company.name}}",
        "overdue_sequence.second" to "Hi {{client.firstName}}, invoice {{invoice.number}} ({{invoice.amountDue}}) is now {{invoice.daysOverdue}} days overdue. Could you let us know when we can expect payment? I'm sending the invoice again. {{company.name}}",
        "overdue_sequence.task" to "Call {{client.name}} about invoice {{invoice.number}} ({{invoice.daysOverdue}} days overdue)",
        "payment_thank_you.name" to "Payment thank-you",
        "payment_thank_you.message" to "Hi {{client.firstName}}, we've received the payment for invoice {{invoice.number}}. Thank you for your trust! {{company.name}}",
        "payables_digest.name" to "Payments due this week",
        "month_end_billing.name" to "Month-end billing",
        "month_end_billing.notify" to "Invoice {{steps.s1.output.number}} created for {{client.name}} from {{steps.s1.output.rows}} open services.",
        "weekly_cash_briefing.name" to "Weekly cash briefing",
        "quote_follow_up.name" to "Quote follow-up",
        "quote_follow_up.message" to "Hi {{client.firstName}}, did you get a chance to look at quote {{quote.number}} ({{quote.total}})? I'm happy to answer any questions. {{company.name}}",
        "quote_follow_up.task" to "Follow up with {{client.name}} on quote {{quote.number}}",
        "quote_expiring.name" to "Quote about to expire",
        "quote_expiring.message" to "Hi {{client.firstName}}, quote {{quote.number}} ({{quote.total}}) is valid until {{quote.validUntil}}. Shall we go ahead? {{company.name}}",
        "quote_accepted.name" to "Quote accepted: invoice it",
        "quote_accepted.notify" to "{{client.name}} accepted quote {{quote.number}}: invoice {{steps.s1.output.number}} is ready.",
        "new_lead_intake.name" to "New contact intake",
        "new_lead_intake.notify" to "New contact: {{contact.displayName}}.",
        "new_lead_intake.task" to "Get back to {{contact.displayName}}",
        "booking_confirmation.name" to "Booking confirmation",
        "booking_confirmation.message" to "Hi {{client.firstName}}, your booking for {{booking.serviceName}} is set for {{booking.start}}. See you then! {{company.name}}",
        "booking_reminder.name" to "Booking reminder",
        "booking_reminder.message" to "Hi {{client.firstName}}, a reminder of your {{booking.serviceName}} on {{booking.start}}. Reply if you need to change it. {{company.name}}",
        "unconfirmed_booking_alert.name" to "Unconfirmed booking alert",
        "unconfirmed_booking_alert.notify" to "The booking of {{booking.contactName}} for {{booking.serviceName}} on {{booking.start}} is still waiting for confirmation.",
        "post_service_follow_up.name" to "After-service thank-you",
        "post_service_follow_up.message" to "Hi {{client.firstName}}, thank you for choosing us for {{booking.serviceName}}! We hope to see you again soon. {{company.name}}",
        "post_service_follow_up.message_review" to "Hi {{client.firstName}}, thank you for choosing us for {{booking.serviceName}}! If you have a minute, a review would mean a lot: {reviewUrl} {{company.name}}",
        "no_show_recovery.name" to "Missed booking follow-up",
        "no_show_recovery.message" to "Hi {{client.firstName}}, we missed you for {{booking.serviceName}} today. Would you like to book another time? {{company.name}}",
        "daily_agenda.name" to "Daily agenda",
        "waiting_chat_alert.name" to "Chat waiting for an answer",
        "waiting_chat_alert.notify" to "{{conversation.contactName}} has been waiting {{conversation.waitingMinutes}} minutes for an answer.",
        "instagram_comment_triage.name" to "Instagram comment alert",
        "instagram_comment_triage.notify" to "New comment from @{{comment.fromUsername}}: {{comment.text}}",
        "reengagement.name" to "Check in with quiet clients",
        "reengagement.message" to "Hi {{client.firstName}}, it's been a while! If there's anything we can help with, just reply to this message. {{company.name}}",
        "weekly_data_check.name" to "Weekly client data check",
        "email_quote_when_sent.name" to "Email the quote when it's sent",
        "email_quote_when_sent.subject" to "Quote {{quote.number}} from {{company.name}}",
        "email_quote_when_sent.message" to "Hi {{client.firstName}},\n\nPlease find attached quote {{quote.number}} ({{quote.total}}), valid until {{quote.validUntil}}.\n\nDon't hesitate to reply with any questions.\n\n{{company.name}}",
        "email_invoice_when_created.name" to "Email new invoices",
        "email_invoice_when_created.subject" to "Invoice {{invoice.number}} from {{company.name}}",
        "email_invoice_when_created.message" to "Hi {{client.firstName}},\n\nPlease find attached invoice {{invoice.number}} ({{invoice.total}}), due on {{invoice.dueDate}}.\n\nThank you!\n\n{{company.name}}",
        "email_lead_capture.name" to "Email lead capture",
        "email_lead_capture.instructions" to "Read the email and decide whether it is a new request for work or for a quote (not a newsletter, an invoice, a notification or a reply about ongoing work). Find the sender's name and phone if they give one, and write a one-line summary of what they need.",
        "email_lead_capture.task" to "New request by email from {{email.fromName}}: {{steps.s1.output.summary}}",
        "email_lead_capture.detail" to "Name: {{steps.s1.output.name | default: not given}}\nPhone: {{steps.s1.output.phone | default: not given}}\nEmail: {{email.from}}\nSubject: {{email.subject}}",
        "supplier_bill_intake.name" to "Supplier bill intake",
        "supplier_bill_intake.instructions" to "Decide whether the email is a bill the company has to pay (not a quote, a receipt for something already paid, a statement or an advert). If it is, write a short description of what it is for, the amount to pay with its currency as written (e.g. €1,234.50) and the due date. The attached PDF isn't included: leave out what the email itself doesn't say.",
        "supplier_bill_intake.notify" to "Supplier bill from {{email.fromName}}: {{steps.s1.output.description}} · {{steps.s1.output.amount | default: amount not in the email}} · due: {{steps.s1.output.dueDate | default: not stated}}.",
        "supplier_bill_intake.task" to "Pay the bill from {{email.fromName}}: {{steps.s1.output.description}}",
        "supplier_bill_intake.detail" to "Amount: {{steps.s1.output.amount | default: not in the email}}\nDue: {{steps.s1.output.dueDate | default: not stated}}\nEmail: {{email.subject}} ({{email.from}})",
        "lead_qualifier.name" to "Qualify new chats",
        "lead_qualifier.instructions" to "Read the customer's latest message and sort it by what they want: a new request for work, a question, a complaint or other (greetings, spam, anything else). Write a one-line summary for the team.",
        "lead_qualifier.intent_new" to "new request",
        "lead_qualifier.intent_question" to "question",
        "lead_qualifier.intent_complaint" to "complaint",
        "lead_qualifier.intent_other" to "other",
        "lead_qualifier.notify" to "{{conversation.contactName}} ({{steps.s1.output.intent}}): {{steps.s1.output.summary}}",
        "lead_qualifier.task" to "Reply to {{conversation.contactName}}: {{steps.s1.output.summary}}",
    )

    private val pt = mapOf(
        "invoice_due_reminder.name" to "Lembrete de fatura a vencer",
        "invoice_due_reminder.message" to "Olá {{client.firstName}}, lembramos que a fatura {{invoice.number}} ({{invoice.amountDue}}) vence a {{invoice.dueDate}}. Obrigado! {{company.name}}",
        "overdue_sequence.name" to "Seguimento de faturas em atraso",
        "overdue_sequence.first" to "Olá {{client.firstName}}, a fatura {{invoice.number}} ({{invoice.amountDue}}) venceu a {{invoice.dueDate}}. Se já pagou, ignore esta mensagem. Obrigado! {{company.name}}",
        "overdue_sequence.second" to "Olá {{client.firstName}}, a fatura {{invoice.number}} ({{invoice.amountDue}}) está em atraso há {{invoice.daysOverdue}} dias. Pode indicar-nos quando conta pagar? Envio novamente a fatura. {{company.name}}",
        "overdue_sequence.task" to "Ligar a {{client.name}} sobre a fatura {{invoice.number}} ({{invoice.daysOverdue}} dias em atraso)",
        "payment_thank_you.name" to "Agradecimento de pagamento",
        "payment_thank_you.message" to "Olá {{client.firstName}}, recebemos o pagamento da fatura {{invoice.number}}. Obrigado pela confiança! {{company.name}}",
        "payables_digest.name" to "Pagamentos desta semana",
        "month_end_billing.name" to "Faturação de fim de mês",
        "month_end_billing.notify" to "Fatura {{steps.s1.output.number}} criada para {{client.name}} a partir de {{steps.s1.output.rows}} serviços em aberto.",
        "weekly_cash_briefing.name" to "Resumo semanal de tesouraria",
        "quote_follow_up.name" to "Seguimento de orçamentos",
        "quote_follow_up.message" to "Olá {{client.firstName}}, já teve oportunidade de ver o orçamento {{quote.number}} ({{quote.total}})? Estou disponível para qualquer dúvida. {{company.name}}",
        "quote_follow_up.task" to "Fazer seguimento com {{client.name}} do orçamento {{quote.number}}",
        "quote_expiring.name" to "Orçamento prestes a expirar",
        "quote_expiring.message" to "Olá {{client.firstName}}, o orçamento {{quote.number}} ({{quote.total}}) é válido até {{quote.validUntil}}. Avançamos? {{company.name}}",
        "quote_accepted.name" to "Orçamento aceite: faturar",
        "quote_accepted.notify" to "{{client.name}} aceitou o orçamento {{quote.number}}: a fatura {{steps.s1.output.number}} está pronta.",
        "new_lead_intake.name" to "Receção de novos contactos",
        "new_lead_intake.notify" to "Novo contacto: {{contact.displayName}}.",
        "new_lead_intake.task" to "Responder a {{contact.displayName}}",
        "booking_confirmation.name" to "Confirmação de marcação",
        "booking_confirmation.message" to "Olá {{client.firstName}}, a sua marcação de {{booking.serviceName}} ficou para {{booking.start}}. Até lá! {{company.name}}",
        "booking_reminder.name" to "Lembrete de marcação",
        "booking_reminder.message" to "Olá {{client.firstName}}, lembramos a sua marcação de {{booking.serviceName}} a {{booking.start}}. Responda se precisar de alterar. {{company.name}}",
        "unconfirmed_booking_alert.name" to "Alerta de marcação por confirmar",
        "unconfirmed_booking_alert.notify" to "A marcação de {{booking.contactName}} para {{booking.serviceName}} a {{booking.start}} continua por confirmar.",
        "post_service_follow_up.name" to "Agradecimento após o serviço",
        "post_service_follow_up.message" to "Olá {{client.firstName}}, obrigado por nos escolher para {{booking.serviceName}}! Até breve. {{company.name}}",
        "post_service_follow_up.message_review" to "Olá {{client.firstName}}, obrigado por nos escolher para {{booking.serviceName}}! Se tiver um minuto, a sua avaliação é muito importante para nós: {reviewUrl} {{company.name}}",
        "no_show_recovery.name" to "Seguimento de faltas",
        "no_show_recovery.message" to "Olá {{client.firstName}}, sentimos a sua falta em {{booking.serviceName}} hoje. Quer marcar outra hora? {{company.name}}",
        "daily_agenda.name" to "Agenda do dia",
        "waiting_chat_alert.name" to "Conversa à espera de resposta",
        "waiting_chat_alert.notify" to "{{conversation.contactName}} está à espera de resposta há {{conversation.waitingMinutes}} minutos.",
        "instagram_comment_triage.name" to "Alerta de comentários no Instagram",
        "instagram_comment_triage.notify" to "Novo comentário de @{{comment.fromUsername}}: {{comment.text}}",
        "reengagement.name" to "Contactar clientes inativos",
        "reengagement.message" to "Olá {{client.firstName}}, há algum tempo que não falamos! Se precisar de alguma coisa, basta responder a esta mensagem. {{company.name}}",
        "weekly_data_check.name" to "Verificação semanal de dados de clientes",
        "email_quote_when_sent.name" to "Enviar o orçamento por email",
        "email_quote_when_sent.subject" to "Orçamento {{quote.number}} de {{company.name}}",
        "email_quote_when_sent.message" to "Olá {{client.firstName}},\n\nSegue em anexo o orçamento {{quote.number}} ({{quote.total}}), válido até {{quote.validUntil}}.\n\nFico ao dispor para qualquer dúvida.\n\n{{company.name}}",
        "email_invoice_when_created.name" to "Enviar faturas novas por email",
        "email_invoice_when_created.subject" to "Fatura {{invoice.number}} de {{company.name}}",
        "email_invoice_when_created.message" to "Olá {{client.firstName}},\n\nSegue em anexo a fatura {{invoice.number}} ({{invoice.total}}), com vencimento a {{invoice.dueDate}}.\n\nObrigado!\n\n{{company.name}}",
        "email_lead_capture.name" to "Captar pedidos por email",
        "email_lead_capture.instructions" to "Leia o email e decida se é um novo pedido de trabalho ou de orçamento (e não uma newsletter, uma fatura, uma notificação ou uma resposta sobre um trabalho em curso). Encontre o nome de quem escreve e o telefone, se o indicar, e escreva um resumo de uma linha do que precisa.",
        "email_lead_capture.task" to "Novo pedido por email de {{email.fromName}}: {{steps.s1.output.summary}}",
        "email_lead_capture.detail" to "Nome: {{steps.s1.output.name | default: não indicado}}\nTelefone: {{steps.s1.output.phone | default: não indicado}}\nEmail: {{email.from}}\nAssunto: {{email.subject}}",
        "supplier_bill_intake.name" to "Receção de faturas de fornecedores",
        "supplier_bill_intake.instructions" to "Decida se o email é uma fatura que a empresa tem de pagar (e não um orçamento, um recibo de algo já pago, um extrato ou publicidade). Se for, escreva uma descrição curta do que se trata, o valor a pagar com a moeda, tal como está escrito (por exemplo, 1234,50 €), e a data de vencimento. O PDF anexo não está incluído: deixe de fora o que o próprio email não diz.",
        "supplier_bill_intake.notify" to "Fatura de fornecedor de {{email.fromName}}: {{steps.s1.output.description}} · {{steps.s1.output.amount | default: valor não indicado no email}} · vencimento: {{steps.s1.output.dueDate | default: não indicado}}.",
        "supplier_bill_intake.task" to "Pagar a fatura de {{email.fromName}}: {{steps.s1.output.description}}",
        "supplier_bill_intake.detail" to "Valor: {{steps.s1.output.amount | default: não indicado no email}}\nVencimento: {{steps.s1.output.dueDate | default: não indicado}}\nEmail: {{email.subject}} ({{email.from}})",
        "lead_qualifier.name" to "Qualificar novas conversas",
        "lead_qualifier.instructions" to "Leia a última mensagem do cliente e classifique-a pelo que pretende: um novo pedido de trabalho, uma pergunta, uma reclamação ou outro (cumprimentos, spam, qualquer outra coisa). Escreva um resumo de uma linha para a equipa.",
        "lead_qualifier.intent_new" to "novo pedido",
        "lead_qualifier.intent_question" to "pergunta",
        "lead_qualifier.intent_complaint" to "reclamação",
        "lead_qualifier.intent_other" to "outro",
        "lead_qualifier.notify" to "{{conversation.contactName}} ({{steps.s1.output.intent}}): {{steps.s1.output.summary}}",
        "lead_qualifier.task" to "Responder a {{conversation.contactName}}: {{steps.s1.output.summary}}",
    )

    private val es = mapOf(
        "invoice_due_reminder.name" to "Recordatorio de factura por vencer",
        "invoice_due_reminder.message" to "Hola {{client.firstName}}, te recordamos que la factura {{invoice.number}} ({{invoice.amountDue}}) vence el {{invoice.dueDate}}. ¡Gracias! {{company.name}}",
        "overdue_sequence.name" to "Seguimiento de facturas vencidas",
        "overdue_sequence.first" to "Hola {{client.firstName}}, la factura {{invoice.number}} ({{invoice.amountDue}}) venció el {{invoice.dueDate}}. Si ya la pagaste, ignora este mensaje. ¡Gracias! {{company.name}}",
        "overdue_sequence.second" to "Hola {{client.firstName}}, la factura {{invoice.number}} ({{invoice.amountDue}}) lleva {{invoice.daysOverdue}} días vencida. ¿Nos indicas cuándo podrás pagarla? Te envío de nuevo la factura. {{company.name}}",
        "overdue_sequence.task" to "Llamar a {{client.name}} por la factura {{invoice.number}} ({{invoice.daysOverdue}} días vencida)",
        "payment_thank_you.name" to "Agradecimiento de pago",
        "payment_thank_you.message" to "Hola {{client.firstName}}, hemos recibido el pago de la factura {{invoice.number}}. ¡Gracias por tu confianza! {{company.name}}",
        "payables_digest.name" to "Pagos de esta semana",
        "month_end_billing.name" to "Facturación de fin de mes",
        "month_end_billing.notify" to "Factura {{steps.s1.output.number}} creada para {{client.name}} a partir de {{steps.s1.output.rows}} servicios abiertos.",
        "weekly_cash_briefing.name" to "Resumen semanal de tesorería",
        "quote_follow_up.name" to "Seguimiento de presupuestos",
        "quote_follow_up.message" to "Hola {{client.firstName}}, ¿pudiste revisar el presupuesto {{quote.number}} ({{quote.total}})? Quedo a tu disposición para cualquier duda. {{company.name}}",
        "quote_follow_up.task" to "Hacer seguimiento con {{client.name}} del presupuesto {{quote.number}}",
        "quote_expiring.name" to "Presupuesto a punto de caducar",
        "quote_expiring.message" to "Hola {{client.firstName}}, el presupuesto {{quote.number}} ({{quote.total}}) es válido hasta el {{quote.validUntil}}. ¿Seguimos adelante? {{company.name}}",
        "quote_accepted.name" to "Presupuesto aceptado: facturar",
        "quote_accepted.notify" to "{{client.name}} aceptó el presupuesto {{quote.number}}: la factura {{steps.s1.output.number}} está lista.",
        "new_lead_intake.name" to "Recepción de nuevos contactos",
        "new_lead_intake.notify" to "Nuevo contacto: {{contact.displayName}}.",
        "new_lead_intake.task" to "Responder a {{contact.displayName}}",
        "booking_confirmation.name" to "Confirmación de reserva",
        "booking_confirmation.message" to "Hola {{client.firstName}}, tu reserva de {{booking.serviceName}} quedó para el {{booking.start}}. ¡Hasta entonces! {{company.name}}",
        "booking_reminder.name" to "Recordatorio de reserva",
        "booking_reminder.message" to "Hola {{client.firstName}}, te recordamos tu reserva de {{booking.serviceName}} el {{booking.start}}. Responde si necesitas cambiarla. {{company.name}}",
        "unconfirmed_booking_alert.name" to "Aviso de reserva sin confirmar",
        "unconfirmed_booking_alert.notify" to "La reserva de {{booking.contactName}} para {{booking.serviceName}} el {{booking.start}} sigue sin confirmar.",
        "post_service_follow_up.name" to "Agradecimiento tras el servicio",
        "post_service_follow_up.message" to "Hola {{client.firstName}}, ¡gracias por elegirnos para {{booking.serviceName}}! Esperamos verte pronto. {{company.name}}",
        "post_service_follow_up.message_review" to "Hola {{client.firstName}}, ¡gracias por elegirnos para {{booking.serviceName}}! Si tienes un minuto, tu reseña nos ayudaría mucho: {reviewUrl} {{company.name}}",
        "no_show_recovery.name" to "Seguimiento de ausencias",
        "no_show_recovery.message" to "Hola {{client.firstName}}, te echamos de menos hoy en {{booking.serviceName}}. ¿Quieres reservar otra hora? {{company.name}}",
        "daily_agenda.name" to "Agenda del día",
        "waiting_chat_alert.name" to "Conversación esperando respuesta",
        "waiting_chat_alert.notify" to "{{conversation.contactName}} lleva {{conversation.waitingMinutes}} minutos esperando respuesta.",
        "instagram_comment_triage.name" to "Aviso de comentarios en Instagram",
        "instagram_comment_triage.notify" to "Nuevo comentario de @{{comment.fromUsername}}: {{comment.text}}",
        "reengagement.name" to "Contactar clientes inactivos",
        "reengagement.message" to "Hola {{client.firstName}}, ¡hace tiempo que no hablamos! Si necesitas algo, responde a este mensaje. {{company.name}}",
        "weekly_data_check.name" to "Revisión semanal de datos de clientes",
        "email_quote_when_sent.name" to "Enviar el presupuesto por email",
        "email_quote_when_sent.subject" to "Presupuesto {{quote.number}} de {{company.name}}",
        "email_quote_when_sent.message" to "Hola {{client.firstName}},\n\nAdjunto el presupuesto {{quote.number}} ({{quote.total}}), válido hasta el {{quote.validUntil}}.\n\nQuedo a tu disposición para cualquier duda.\n\n{{company.name}}",
        "email_invoice_when_created.name" to "Enviar facturas nuevas por email",
        "email_invoice_when_created.subject" to "Factura {{invoice.number}} de {{company.name}}",
        "email_invoice_when_created.message" to "Hola {{client.firstName}},\n\nAdjunto la factura {{invoice.number}} ({{invoice.total}}), con vencimiento el {{invoice.dueDate}}.\n\n¡Gracias!\n\n{{company.name}}",
        "email_lead_capture.name" to "Captar solicitudes por email",
        "email_lead_capture.instructions" to "Lee el email y decide si es una nueva solicitud de trabajo o de presupuesto (y no una newsletter, una factura, una notificación o una respuesta sobre un trabajo en curso). Encuentra el nombre de quien escribe y el teléfono, si lo da, y escribe un resumen de una línea de lo que necesita.",
        "email_lead_capture.task" to "Nueva solicitud por email de {{email.fromName}}: {{steps.s1.output.summary}}",
        "email_lead_capture.detail" to "Nombre: {{steps.s1.output.name | default: no indicado}}\nTeléfono: {{steps.s1.output.phone | default: no indicado}}\nEmail: {{email.from}}\nAsunto: {{email.subject}}",
        "supplier_bill_intake.name" to "Recepción de facturas de proveedores",
        "supplier_bill_intake.instructions" to "Decide si el email es una factura que la empresa tiene que pagar (y no un presupuesto, un recibo de algo ya pagado, un extracto o publicidad). Si lo es, escribe una descripción breve de qué se trata, el importe a pagar con su moneda, tal como aparece (por ejemplo, 1234,50 €), y la fecha de vencimiento. El PDF adjunto no se incluye: deja fuera lo que el propio email no dice.",
        "supplier_bill_intake.notify" to "Factura de proveedor de {{email.fromName}}: {{steps.s1.output.description}} · {{steps.s1.output.amount | default: importe no indicado en el email}} · vencimiento: {{steps.s1.output.dueDate | default: no indicado}}.",
        "supplier_bill_intake.task" to "Pagar la factura de {{email.fromName}}: {{steps.s1.output.description}}",
        "supplier_bill_intake.detail" to "Importe: {{steps.s1.output.amount | default: no indicado en el email}}\nVencimiento: {{steps.s1.output.dueDate | default: no indicado}}\nEmail: {{email.subject}} ({{email.from}})",
        "lead_qualifier.name" to "Calificar nuevas conversaciones",
        "lead_qualifier.instructions" to "Lee el último mensaje del cliente y clasifícalo según lo que quiere: una nueva solicitud de trabajo, una pregunta, una queja u otro (saludos, spam, cualquier otra cosa). Escribe un resumen de una línea para el equipo.",
        "lead_qualifier.intent_new" to "nueva solicitud",
        "lead_qualifier.intent_question" to "pregunta",
        "lead_qualifier.intent_complaint" to "queja",
        "lead_qualifier.intent_other" to "otro",
        "lead_qualifier.notify" to "{{conversation.contactName}} ({{steps.s1.output.intent}}): {{steps.s1.output.summary}}",
        "lead_qualifier.task" to "Responder a {{conversation.contactName}}: {{steps.s1.output.summary}}",
    )

    /** [values] fill single-brace `{name}` placeholders at build time; `{{…}}` variables stay for the run. */
    fun t(locale: String, key: String, vararg values: Pair<String, String>): String {
        val text = catalog(locale)[key] ?: en[key] ?: key
        return values.fold(text) { result, (name, value) -> result.replace("{$name}", value) }
    }

    fun keys(locale: String): Set<String> = catalog(locale).keys

    private fun catalog(locale: String): Map<String, String> = when (TenantLocales.normalize(locale)) {
        "en" -> en
        "es" -> es
        else -> pt
    }
}
